### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by buggleston** [Bl4Cc4t/GoodTwitter2#1]
First off, huge thanks for this userscript.

I just installed Tampermonkey and activated your script (version 0.0.2), and search doesn't appear to be working. It sometimes triggers a page reload after pressing enter, and sometimes does nothing.

Anything I can do or try to help track down the issue?

**Comment by Bl4Cc4t** [comment]
Thanks for your interest in this project :)
I just noticed this issue too, I’m gonna look into it tomorrow!

**Comment by Bl4Cc4t** [comment]
it should work now, let me know if any other problems occur.
