### ISSUE TITLE
New Twitter Showing After Updates

### ISSUE THREAD

**Issue by Mel47** [Bl4Cc4t/GoodTwitter2#101]
I had to start over again from scratch after the newest Tampermonkey and GT2 updates. Tampermonkey had updated itself prior to starting over again, but it did not give me the Beta version (I'm on Firefox), so I removed it and got the Beta V.4.11.6114. I then reloaded GT2 v.20 by following the link you provided in the github info notes. I had already re-enabled the FF security flag earlier. I rebooted Firefox browser after all of that just in case. Went to Twitter and it's still New Twitter. 

Firefox 56.0.2
Windows 7
Tampermonkey Beta V.4.11.6114
GT2 v.20

**Comment by Mel47** [comment]
I pressed F12 with Twitter open on my screen and no error messages popped up. It opens to the Inspector tab, and I wasn't sure if you meant to look at the Console tab, so I looked there too and didn't seen any errors listed in that section. 

In the Inspector tab, it's all "grayed out" where some scripts are listed (the text is light blue and looks faded out), but not sure if that is normal or tells you anything? On the far right in that section there were two yellow exclamation icons having to do with scrollbars, but nothing else in there that indicates an error that I could tell. 

Let me know what else I need to do or tell you. 

Thanks!

**Comment by Bl4Cc4t** [comment]
> I wasn't sure if you meant to look at the Console tab,

Sure, the console tab, the other parts are not important.

> In the Inspector tab, it's all "grayed out" where some scripts are listed (the text is light blue and looks faded out), but not sure if that is normal or tells you anything? 

That is normal on Firefox.
Parts of the site that are not actually visible to the user are greyed out (which is a neat feature chromium should consider adopting).

> Let me know what else I need to do or tell you.

Well that was not really what I asked for, you could’ve just made a screenshot instead of explaining what you see :/

But since you did not see any errors, please confirm that it looks like this when you click on the tampermonkey icon: 
![image](https://user-images.githubusercontent.com/6740726/84372443-6510aa80-abdb-11ea-9b21-d7bbb1b3911e.png)

and a final question: does it work when you visit [`/home`](https://twitter.com/home)?

**Comment by Mel47** [comment]
Yes I am seeing it is enabled with green check mark and the button is green. And yes it is working when I click on the /home link you put above. And navigating around from the link you provided with it working, all still stays Legacy, except for when I click on the blue Twitter bird in top navbar, then it reverts back to New Twitter. 

Well, I spoke too soon. I closed out of the tab I opened from your link after it reverted back to New Twitter, and I went back to it via your link again, and now it opens as New Twitter. Just in case, I thought I'd try clearing my cache and then removed the twitter cookie, and I tried your link again, and it still is opening as New Twitter.

**Comment by Bl4Cc4t** [comment]
That’s pretty weird, there have to be some kind of errors if it is enabled but you don’t see anything. Can you please take a screenshot when that happens (with the console visible)?

**Comment by Mel47** [comment]
Ok, now there are errors showing! I used the link you provided to go to /home, and here is the screenshot of the dev tools with console tab results. Not all fit in the screenshot, but I think it was just more of the same that kept populating in there. 

![Twitter - F12 - Errors - 1](https://user-images.githubusercontent.com/66347232/84550780-649e0f80-acc0-11ea-8f12-ddecf87a5a08.png)

**Comment by Bl4Cc4t** [comment]
I am getting aall kinds of different results on older firefox versions.
48.0 now has a broken layout and 56.0 doesn’t work at all (like you said).
Can’t you just update? :D
JK, I hope I can fix this mess.

**Comment by Mel47** [comment]
Some day I'll have to update...but I'm stubborn. ;) Really do appreciate all of your hard work on all of this - not just my issues, but making the entire GT2 awesome for everyone. :) Let me know if there is any other info you need.

**Comment by Bl4Cc4t** [comment]
Okay, seems like this is CSP related.
Since you are on an older version, you already know about your security being at a risk.
Here is a way to disable it only for twitter.com:
- install [Header Editor](https://addons.mozilla.org/en-US/firefox/addon/header-editor/)
- Go to *Manage* -> *Export and Import*
- In the *Download rule* field, paste this:
```
https://gist.githubusercontent.com/Bl4Cc4t/267b4c732382c339cafb8ae83c104fa4/raw/3117f09fad560e13a0b7376ff44578bfb6152008/HE_2020-06-12T23-50-07Z.json
```
- Click the save button under the shown imported rule.

**Comment by Mel47** [comment]
That works! Thank you! :)

As a side note...is there a possibility you could eventually get it to work without that having to be disabled? May not be a priority with everything else you got going on...plus, I have no idea how complicated that sort of thing is to do, or if it's even possible for older versions of FF based on how they are built or such, but just asking out of curiosity.

**Comment by Bl4Cc4t** [comment]
Hey, I found another way! Use [Violentmonkey](https://addons.mozilla.org/de/firefox/addon/violentmonkey/) :D
That also works. Not too sure why though, but it works

**Comment by Mel47** [comment]
Sorry if this is a stupid question, but am I to use ViolentMonkey instead of Tampermonkey (and I add the GT2 script to that one instead)? And I can get rid of the Header Editor add-on too and not have to disable the Twitter CSP? Or do I just get rid of HM and keep both TM and VM? I don't know anything about script managers or stuff like that, so I just want to be sure.
