### ISSUE TITLE
Square avatar displayed is overwritten with a gray circle

### ISSUE THREAD

**Issue by dig-sw** [Bl4Cc4t/GoodTwitter2#102]
**Problem**
The square avatar image displayed is overwritten with a gray circle.
The problem occurs when the "Square Avatars" option is enabled.
This problem occurs all the time.

**Screenshots**

![img](https://user-images.githubusercontent.com/66514018/84229283-2d92f700-ab24-11ea-9abd-f0296aae45e3.png)

**Configuation**
 - Chrome : 83.0.4103.97
 - Tampermonkey : 4.10
 - GoodTwitter2 : 0.0.20

**Comment by dig-sw** [comment]
Thank you for your quick response.
The problem has been fixed.

Now the square avatar has a gray line around the edges.
I remember the square avatar at the time did not have a borderline.
Are you planning to do the same with a borderline less square avater design?

**Comment by Bl4Cc4t** [comment]
> Thank you for your quick response.
The problem has been fixed.

Hm, I just released the version with the fix (v0.0.21), are you a time traveller? :D

> Now the square avatar has a gray line around the edges.

Isn’t the gray line what you reported here?

> I remember the square avatar at the time did not have a borderline.
Are you planning to do the same with a borderline less square avater design?

By “borderline”, you mean the border of the avatar in the dashboard profile, do you?
![image](https://user-images.githubusercontent.com/6740726/84534524-59f87000-acea-11ea-863b-631329ba13ed.png)

**Comment by dig-sw** [comment]
> Hm, I just released the version with the fix (v0.0.21), are you a time traveller? :D

Probably due to the gap between posting time and software update time. Sorry.

> Isn’t the gray line what you reported here?

Yes, Description images uploaded.
avatar image : plain white(#ffffff) square image

> By “borderline”, you mean the border of the avatar in the dashboard profile, do you?

“borderline”, I mean the gray thin line of outside avatar image.
Please see the image I uploaded.

![img3](https://user-images.githubusercontent.com/66514018/84558570-daf94b00-ad6e-11ea-9164-f470d13386dc.png)

**Comment by Bl4Cc4t** [comment]
hm, this is only visible when using the white theme with a white avatar :D
I fixed it.

**Comment by dig-sw** [comment]
Thanks for the work.

These thin lines are easy to detect when the edges of the avatar image are light color. (white etc,)
This is the avatar I used in my report.

**Settings when uploading to the twitter**
upload file : png file , 500x500
Trimming images : none (max size)

[avatar image.zip](https://github.com/Bl4Cc4t/GoodTwitter2/files/4774821/avatar.image.zip)

**Comment by Bl4Cc4t** [comment]
Still couldn’t get that line to show up...
I changed some things, I hope it is gone with the next version :D
