### ISSUE TITLE
Version 0.0.21.1 not working on user's lists page

### ISSUE THREAD

**Issue by go2tom42** [Bl4Cc4t/GoodTwitter2#105]
**Please check the following before you continue**
- [X] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [X] Checked if the issue has not been reported before

Not working on lists page

![Lists_created_by_@go2tom42_Twitter_-_2020-06-12_16 43 23](https://user-images.githubusercontent.com/12462792/84544771-f2332c80-accb-11ea-8cc5-70d33ed73259.png)

**Your configuration**
 - Firefox 77.0.01
 - tampermonkey 4.11.6114
 - Version 0.0.21.1

**Comment by Bl4Cc4t** [comment]
cannot reproduce, works for me
what errors do you get in the console?

**Comment by go2tom42** [comment]
I assume firefox console, I don't know if tampermonkey has one
```

Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). common.js:2:319
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). content-hooks-frames.js:59:42
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). content_script.js:119:34
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified 4
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified 3
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified 2
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified 4
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: The page’s settings blocked the loading of a resource at data:i (“object-src”). main.0e61c304.js:14:40461
Source map error: Error: request failed with status 401
Resource URL: https://abs.twimg.com/responsive-web/web/main.0e61c304.js
Source Map URL: https://ton.twitter.com/responsive-web-internal/sourcemaps/web/main.0e61c304.js.map
Some cookies are misusing the recommended “sameSite“ attribute 3
Cookie “_ga” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite analytics.js:28:486
Cookie “_gid” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite analytics.js:28:486
Cookie “_gat” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite analytics.js:28:486
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
```

**Comment by Bl4Cc4t** [comment]
I am not getting these errors either...
have you disabled all other extensions except for TM?
does it work when you disable `security.csp.enable` in `about:config`?

**Comment by go2tom42** [comment]
This extension https://addons.mozilla.org/en-US/firefox/addon/universal-bypass/ was stopping it from working, but it does work with the extension and `security.csp.enable` disabled

**Comment by Bl4Cc4t** [comment]
I don’t get this error when using that extension...
Are there any special settings you have set? Or is it maybe another extension?

---

Also, please don’t disable `security.csp.enable` permanently, try some other things first:
- try Violentmonkey
- [disable CSP only for twitter.com](https://github.com/Bl4Cc4t/GoodTwitter2/issues/101#issuecomment-643525816)

**Comment by go2tom42** [comment]
No that was the only extension, I disabled all extensions but tampermoney then tried my other extensions one by one and universal-bypass was the only issue. 

For now I re-enabled `security.csp.enable` and disabled universal-bypass, I did not use it much anyway

I will try Violentmonkey later today

**Comment by PewnyPL** [comment]
I will add - in Chrome after updating to 0.0.21.1 the script also stopped loading using Tampermonkey. There are no errors different than when loading the page without the script enabled.
Using Violentmonkey the script loads fine.

**Comment by Bl4Cc4t** [comment]
@PewnyPL what versions do you use? What script version did you have before the update (if you can remember)

**Comment by PewnyPL** [comment]
Chrome: 83.0.4103.97 x64 (current newest)
Tampermonkey: 4.10 (current newest from chrome store)
Script version before update: 0.0.20 - I only knew the script was updating to 0.0.21.1 because of Tampermonkey popping up that new permission or something is required (something about connecting, assuming related to change log).

And actually seems I was wrong, I just went and reenabled GT2 in Tampermonkey, and there is one warning in console that I don't get with it disabled. I skipped through it previously because it seems similar to MANY other warnings I get from twitter. Here are screenshots:
Without GT2: https://i.gyazo.com/2da07a9e60ce526409f867f6f895b279.png
With GT2 (note the first warning): https://i.gyazo.com/47091bed49af7874850aee435835769c.png

**Comment by Bl4Cc4t** [comment]
That are indeed a lot of errors, over 800...
(funny how the site manages to violate its own stupid csp policy thingies)

The warning is not related to the script, it’s coming from [this extension](https://chrome.google.com/webstore/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd) you have installed.
A sourcemap missing is nothing to worry about, these things are only used for debugging anyways.

**Comment by PewnyPL** [comment]
Ooops, my bad there, I didn't check what the extension is and now I see it's there without GT2 as well, just order is different.
Well either way, there isn't any error in the console related to the script, it just seems as if Tampermonkey was failing to load it for some reason.

**Comment by Bl4Cc4t** [comment]
Well I have no idea why it is suddenly not working anymore.
You could try using the beta version of tampermonkey, would be interesting if that works.
Or just stick with VM for now, maybe this is tied to some higher forces
