### ISSUE TITLE
Have GIFS while searching

### ISSUE THREAD

**Issue by daleylife411** [Bl4Cc4t/GoodTwitter2#106]
GIFS used to play as you searched, so you could see exactly how they look and how long they play.
I understand why Twitter did away with this, but now I have to add a GIF directly to my tweet for it to play and I would like to be able to preview the motion before adding it to a tweet.

Is it possible to have GIFS play by clicking on them in the preview or just going back to the original way where they are all playing while you search?

**Comment by fid3lito** [comment]
You mean this?
![rec (02)](https://user-images.githubusercontent.com/66445863/84567848-dbcfb400-ad51-11ea-8775-1f489c544d49.gif)

**Comment by Bl4Cc4t** [comment]
Looks like this is resolved. Thanks @fid3lito!

**Comment by daleylife411** [comment]
Hmm. Sorry. Could have sworn that wasn't there when I made this post.

**Comment by Bl4Cc4t** [comment]
No problem. At least this one was easy to fix :D
