### ISSUE TITLE
Option to move/modify visibility of Translate Tweet on timeline Tweets

### ISSUE THREAD

**Issue by EmeliaK** [Bl4Cc4t/GoodTwitter2#113]
Currently, the Translate Tweet link appears on every single tweet in any timeline, which can be potentially bothersome. As well as consuming vertical space for every tweet, its actual element size covers the entire interior horizontal span of the tweet, which makes it easy to misclick (and, in many cases for some, likely do nothing).

Potential options could be to toggle this on/off, or perhaps be able to place it to the dropdown of the tweet in the upper-right if the user still desires the blanket functionality.

As an aside, the same link appearing on tweets' pages themselves could benefit from the same options, too.

**Comment by Bl4Cc4t** [comment]
> Currently, the Translate Tweet link appears on every single tweet in any timeline which can be potentially bothersome.

It only appears on tweets that are not in your language or can not be translated.
I don’t remember how it was on legacy, but I think it was the same.

> its actual element size covers the entire interior horizontal span of the tweet, which makes it easy to misclick

This is a definite fail and will be fixed, thanks for noticing

> (and, in many cases for some, likely do nothing).

I don’t really understand what you mean by that, please explain

> Potential options could be to toggle this on/off, or perhaps be able to place it to the dropdown of the tweet in the upper-right if the user still desires the blanket functionality.
>
> As an aside, the same link appearing on tweets' pages themselves could benefit from the same options, too.

Well I don’t really get how this feature could be not useful, but I’ll add a toggle to hide it if you really don’t want to see it ever.
Putting it in the dropdown definitely will not happen, that thing is already a mess in itself

**Comment by EmeliaK** [comment]
> It only appears on tweets that are not in your language or can not be translated.

Ah. My language on Twitter is set to British English. Setting it to just "English" seems to reveal that "British English" counts as its own separate language entity, and so any content in English is still registered as outside the language.

> I don’t really understand what you mean by that, please explain

This was just in reference to the redundant marking of tweets in the host language, which I now realise is because of the issue above. Apologies for that.

Thank you very, very much for your work in bringing this userscript to us.

**Comment by Bl4Cc4t** [comment]
> Ah. My language on Twitter is set to British English. Setting it to just "English" seems to reveal that "British English" counts as its own separate language entity, and so any content in English is still registered as outside the language.

Oh, I did not think of that, I added a check for that.

> This was just in reference to the redundant marking of tweets in the host language, which I now realise is because of the issue above. Apologies for that.

No problem, yet another small issue fixed!

> Thank you very, very much for your work in bringing this userscript to us.

Sure thing :)
