### ISSUE TITLE
Unwanted new messages box at bottom of screen?

### ISSUE THREAD

**Issue by cszabla** [Bl4Cc4t/GoodTwitter2#124]
Maybe this is more of a bug, but a new pop-up messages box has appeared at the bottom right of my interface. This box was not part of old Twitter or even the current interface and I would like it to go away (since we have access to messages via the top nav bar.)

**Comment by cszabla** [comment]
<img width="920" alt="twitter messages box" src="https://user-images.githubusercontent.com/66333281/85062898-51cf8300-b177-11ea-96c5-15699e34ac45.png">

**Comment by fid3lito** [comment]
Same here, it showed up out of nowhere and I don't even use DM that often for it to be useful

**Comment by Bl4Cc4t** [comment]
That was not added by this script, it’s a feature from twitter itself.
will definitely add a toggle to hide it, I do not like it either
