### ISSUE TITLE
Add Logout button to dropdown

### ISSUE THREAD

**Issue by daleylife411** [Bl4Cc4t/GoodTwitter2#126]
Can not find the logout button at all with the extension enabled. 
Where is it located?

**Comment by spodermenpls** [comment]
Click on the downward arrow to the right of your Twitter name and handle, in that context menu you'll find it. I had to search for a while too, when I started using this userscript. 😅

**Comment by Bl4Cc4t** [comment]
Hm, do you have some ideas on how to make it more obvious? I even had to search for it myself...

**Comment by Daviljoe193** [comment]
I'd suggest putting the logout button where Google put their logout button, right in the main dropdown menu, at the bottom. Only problem with this is that on smaller displays, the menu might end up becoming too big to fit onscreen if this were added.
![goodtwitter-suggestion1](https://user-images.githubusercontent.com/67191631/85201320-8c96ff80-b2cc-11ea-8bdc-2677377a81c6.jpg)

**Comment by Bl4Cc4t** [comment]
Yeah, it was just like you said. I suppose I can decrease the padding of the elements a bit to add some more buffer :D
![image](https://user-images.githubusercontent.com/6740726/85202113-5d03e980-b304-11ea-9b99-1d20fdde0935.png)

**Comment by daleylife411** [comment]
Just my two cents, now where I know where it is, it's fine. But yes, I didn't even think to look there.

**Comment by CJ040506** [comment]
I have no logout button. Neither in the drop-down menu on the right side (it ends with Settings & Privacy, Help Center & Display), nor in the one next to my user-icon. I also cannot add other accounts to my session, the user-icon drop-down menu only shows my active account. To log out I always have to use a bookmarked twitter logout page.

**Comment by Bl4Cc4t** [comment]
@CJ040506 can you please attach a screenshot of what you are seeing, I cannot do anything about it otherwise

**Comment by Poopooracoocoo** [comment]
This is what it looks like for me: 
![image](https://user-images.githubusercontent.com/51363864/95701834-55db5f80-0c96-11eb-9dca-3ff815b20716.png)

If I zoom out by 10% it looks like this: 
![image](https://user-images.githubusercontent.com/51363864/95701856-612e8b00-0c96-11eb-93d6-b918685a1dca.png)

zooming out isn't a nice experience

**Comment by Bl4Cc4t** [comment]
@Poopooracoocoo You can also log out using the dropdown on the left
![image](https://user-images.githubusercontent.com/6740726/95780530-55f65200-0ccc-11eb-9656-d464b9a3864e.png)
