### ISSUE TITLE
Readd the Ellipsis button when checking the list of likes/retweets or looking at Following or Followers lists

### ISSUE THREAD

**Issue by LifeLineRH** [Bl4Cc4t/GoodTwitter2#132]
When you looked at the list of people who, for example, retweeted and/or liked a given tweet, or the list of followers of a given Twitter account or a list of which people a Twitter account is following, there was an ellipses button where you could, among other things, mute, block or report a given person on that list of people who liked or retweeted something, _along_ with a follow button. If at all possible, I'd like for you to bring that kind of ellipsis button back (mostly because I just want to block more people whenever possible, not gonna lie).

**Comment by Bl4Cc4t** [comment]
I added this as a slighty modified feature: you can now quickblock people by hovering over the "Follow" button until it turns into "Block"

https://user-images.githubusercontent.com/6740726/103029002-292aaa80-4559-11eb-8883-34f11d696cb6.mp4
