### ISSUE TITLE
Gap when logged out and fixed sidebars enabled

### ISSUE THREAD

**Issue by spodermenpls** [Bl4Cc4t/GoodTwitter2#138]
**Please check the following before you continue**
- [X] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [X] Checked if the issue has not been reported before

**Describe the bug**
As mentioned in #135, having "Show trends on left sidebar" and "Show always 10 trends" activated only gets enforced/honored while being logged-out, while being logged-in, the "Trends" section only contains the title on a white canvas, with no actual trends underneath it, and still being on the right hand side.

On a side note, as this probably doesn't merit an extra issue: activating "Fixed sidebars" leads to a big gap between the center and right sidebar, while being logged-out (as seen on screen 2).

**Screenshots**
Settings:
![einst](https://user-images.githubusercontent.com/23747593/85319090-5cfd1880-b4c1-11ea-9ea3-b46027bba2f9.JPG)

While logged-out:
![loggedout](https://user-images.githubusercontent.com/23747593/85318495-5f12a780-b4c0-11ea-9ca8-2e637eeb8c90.JPG)

While logged-in:
![loggedin](https://user-images.githubusercontent.com/23747593/85318518-6a65d300-b4c0-11ea-84fe-2625949c6d0d.JPG)

**Your configuation**
 - Browser: Firefox 77.0.1 64bit on Windows 10 Pro
 - Userscript Manager: Violentmonkey 2.12.7
 - Potentially relevant extensions: uBlock Origin + uMatrix, Twitter Link Deobfuscator

**Comment by Bl4Cc4t** [comment]
I cannot reproduce this behavior. Have you tried reinstalling the script?
Does it work if you disable all other extensions?
What happens when you disable TM, reload and the enable it again and reload?

I also noticed that some places (e.g. smaller countries) have zero trends showing up and that looks just like that (even the cog is missing)

**Comment by spodermenpls** [comment]
Over night (with no changes on my part) the trends section at least moved to the left sidebar:
![lefthand](https://user-images.githubusercontent.com/23747593/85406750-87eb7900-b562-11ea-9583-9da78656536c.JPG)
I'll try your recommendations, give me a minute. I'll also try the latest VM Release Candidate, the "undefined-> GET" issue gets solved by it, for example.

That may be true, but doesn't apply here, since it displays nothing else but German trends (and the cog also back).

**Comment by spodermenpls** [comment]
Okay, this seems to have solved itself, I assume from switching back and forth between the "Raw export" workaround and the official script lots of times and repeated deleting of cookies and storage, the checkbox in the "trend" settings wasn't ticked anymore, leading to no trends being displays at all; now being ticked again, it displays "Trends: Germany" as it should. I have no idea where the sudden mood change concerning the right/left sidebar stems from, though..

Only thing remaining keeps the gap while logged-out, apparently. 😄 I checked the latest VM RC, it doesn't seem to change the functionality of this userscript for the worse or the better, as far as I can tell.

**Comment by Bl4Cc4t** [comment]
> I'll also try the latest VM Release Candidate, the "undefined-> GET" issue gets solved by it, for example.

Ah, that’s nice :D

> Okay, this seems to have solved itself, I assume from switching back and forth between the "Raw export" workaround from Issue 135 and the official script lots of times and repeated deleting of cookies and storage, the checkbox in the "trend" settings wasn't ticked anymore, leading to no trends being displays at all; now being ticked again, it displays "Trends: Germany" as it should. I have no idea where the sudden mood change concerning the right/left sidebar stems from, though..

Hm, that I can’t do much about. Glad it works now!

> The only thing remaining is the gap while logged-out, apparently.

The gap will be corrected soon. I don’t use twitter logged out, so I don’t stumble upon such issues that easily :/
