### ISSUE TITLE
Have the browser tab header show number of new tweets ready to be shown.

### ISSUE THREAD

**Issue by Araxnus** [Bl4Cc4t/GoodTwitter2#14]
Just like the old twitter layout, the browser tab header used to show how many new tweets are ready to be shown.
This was so useful on old twitter.
As now you have to be on the twitter page/focused on that tab to see this directly.

**Comment by Bl4Cc4t** [comment]
Since new tweets are only loaded when the page is focused, this isn’t really going to be useful...
I implemented it though, so the title updates when the page is focussed.

disablAutoRefresh is pretty unpredictable at the moment and I definitely have trouble creating a good routine. Some help would be nice.

**Comment by Araxnus** [comment]
Yeah, it's now just glitching and auto scrolling the timeline for me unfortunately.
I'll scroll and already seen tweets will pop up a number, then automatically move.
Might want to roll this update back until it can somehow be implemented better.

**Comment by yoboseo** [comment]
would it be impossible to bring back tweets loading without the window being in focus?

**Comment by Bl4Cc4t** [comment]
I think it is possible, but that require some more work.

**Comment by yoboseo** [comment]
would be amazing if you could. to me this is easily the most important feature that is no longer present in the new layout.

**Comment by pulsar30** [comment]
> would be amazing if you could. to me this is easily the most important feature that is no longer present in the new layout.

+1
