### ISSUE TITLE
Only 3 trends show in trends bar

### ISSUE THREAD

**Issue by jgk381** [Bl4Cc4t/GoodTwitter2#140]
The legacy twitter used to always have like 8-10 trends showing. Is there a way to get it to show more trending topics?

Thanks

![Untitled](https://user-images.githubusercontent.com/66537492/85344548-02ae8880-b4be-11ea-80c6-1af5f3e415f9.png)

**Comment by Bl4Cc4t** [comment]
What browser/user script manager are you using and at what versions?
Please don’t just delete everything from the template, that information is crucial
A bigger screenshot would also be nice to have.

**Comment by Bl4Cc4t** [comment]
I'll close this since I heard nothing back. Feel free to reply again if the issue still exists.
