### ISSUE TITLE
Every thing said "undefined" placeholders

### ISSUE THREAD

**Issue by MrMysteryMan** [Bl4Cc4t/GoodTwitter2#146]
Well, I just got back seeing the tweet said undefined instead, and everyone's had "undefined" text placeholders instead.

**Comment by Bl4Cc4t** [comment]
Is it possible to get some more details?
What are you using? What were you doing? 
Please provide screenshots

**Comment by Bl4Cc4t** [comment]
I'm gonna close this due to inactivity.
