### ISSUE TITLE
Legacy profile layout: Left tabs not disappearing

### ISSUE THREAD

**Issue by shootlazer** [Bl4Cc4t/GoodTwitter2#153]
**Please check the following before you continue**
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
Your own profile tab and trend tab should disappear when visiting a profile with the "legacy profile" option enabled.
Those tabs should only be visible at twitter.com/home

**Screenshots**
![image](https://user-images.githubusercontent.com/46911545/86554719-b1d37100-bf4e-11ea-9cdc-5a6275409445.png)

**Your configuation**
 - Opera 68
 - Tampermonkey 4.9

**Comment by Bl4Cc4t** [comment]
Why only with `legacyProfile` enabled? I think it makes more sense to hide it either way on other profile pages (btw, that’s how it was before too)

**Comment by shootlazer** [comment]
> Why only with `legacyProfile` enabled? I think it makes more sense to hide it either way on other profile pages (btw, that’s how it was before too)

Honestly, those tabs are always there. But with legacy profile it "blends" improperly

**Comment by shootlazer** [comment]
Almost fixed, but the trend tabs still appear on profile pages!

**Comment by Bl4Cc4t** [comment]
and that will not be changed, see https://github.com/Bl4Cc4t/GoodTwitter2/issues/156#issuecomment-657059417

**Comment by shootlazer** [comment]
> and that will not be changed, see [#156 (comment)](https://github.com/Bl4Cc4t/GoodTwitter2/issues/156#issuecomment-657059417)

Correction. Trends tab used to appear on the right side when visiting profiles.

At least on latest Twitter Web Client

So it shouldn't disappear, just be moved to the right side.
