### ISSUE TITLE
Setting to disable annoying "Home shows you top Tweets first" and similar popups

### ISSUE THREAD

**Issue by Daviljoe193** [Bl4Cc4t/GoodTwitter2#155]
So if you click on Home, you are currently either be forced to interact with a popup saying "Latest Tweets show up as they happen", or if you've clicked the the "Go back Home" button from that popup, a different popup will appear, saying "Home shows you top Tweets first", with a button saying "See latest Tweets instead" and clicking this button will make the first popup appear every time. This is annoying, and likely not something Twitter is going to add a setting for, so adding a GT2 setting to nuke it from orbit would be nice. I've tried writing a uBlock Origin rule for it, but it seems to be bypassing everything I try. Screenrecording (As a gif) below, sorry for the general slowness of it, my ping time is terrible ATM (Thanks Comcast).

![gt2-annoying-popup-disable-request](https://user-images.githubusercontent.com/67191631/86682859-fb63a080-bfce-11ea-86aa-d72f2a5e903d.gif)

**Comment by Handmedown222** [comment]
Since this popup problem started 2 days ago for me, I've had a problem with not being able to interact fully with tweets on my TL. I can only scroll down the page, retweet or like, and my cursor will not change to the hand icon when placed over a tweet. I cannot reply to or open up tweets, or do anything on the page except scroll. If I refresh, it will all work again until I interact with a tweet and then once again I can only scroll. If I do click on the page, it will refresh wiping out all the tweets I was looking at on the page. If I scroll to the top, I will find the popup that you show and if I choose any of its choices, again the page will refresh. 
The only way I can interact with a tweet and not cause the page to refresh, is to copy the link to that tweet and open it on a separate tab to interact with it. It seems to have to do with that popup staying open because when I first go to my Home page TL, the popup won't be open and everything will work fine, but once I interact with a tweet other than to simple retweet or like, then the problem with the page becoming unresponsive starts. I have to refresh it which wipes out where I was on my TL.

**Comment by buggleston** [comment]
I think this should be tagged as a bug, not enhancement. GoodTwitter2 properly hid the "Latest Tweets show up as they happen" popup prior to a couple of days ago.

**To mitigate issue until this is fixed:** In Settings & Privacy, go to the GoodTwitter2 section and disable "Force Latest." Then refresh the browser window. You will then have to manually switch back to Latest Tweets view whenever Twitter's capricious algorithm decides to mess with you again.

**To reproduce this issue:**
1. Have "Force Latest" enabled in GoodTwitter2 settings
2. Navigate to Home feed
3. Click anywhere to hide the "Latest Tweets show up as they happen" popup
4. Click into viewing a single Tweet
5. Click the back arrow at the top-left of the Tweet view
6. The "Latest Tweets..." popup is now back, which you can't even see if you've scrolled down. At this point, clicking anywhere in the window will instantly jump you to the top of the page when it hides that popup.

This is in Chrome 83.0.4103.116 on MacOS, using Tampermonkey, on version 0.0.23 of GoodTwitter2.

**Comment by Daviljoe193** [comment]
> I think this should be tagged as a bug, not enhancement. GoodTwitter2 properly hid the "Latest Tweets show up as they happen" popup prior to a couple of days ago.
> 
> **To mitigate issue until this is fixed:** In Settings & Privacy, go to the GoodTwitter2 section and disable "Force Latest." Then refresh the browser window. You will then have to manually switch back to Latest Tweets view whenever Twitter's capricious algorithm decides to mess with you again.
> 
> **To reproduce this issue:**
> 
>     1. Have "Force Latest" enabled in GoodTwitter2 settings
> 
>     2. Navigate to Home feed
> 
>     3. Click anywhere to hide the "Latest Tweets show up as they happen" popup
> 
>     4. Click into viewing a single Tweet
> 
>     5. Click the back arrow at the top-left of the Tweet view
> 
>     6. The "Latest Tweets..." popup is now back, which you can't even see if you've scrolled down. At this point, clicking anywhere in the window will instantly jump you to the top of the page when it hides that popup.
> 
> 
> This is in Chrome 83.0.4103.116 on MacOS, using Tampermonkey, on version 0.0.23 of GoodTwitter2.

Guess my expectations for Twitter were so low I didn't even think this was a bug, but just a Twitter thing.

**Comment by Handmedown222** [comment]
Thanks for getting back to me and trying to help. I have to ask, What GoodTwitter2 section? I've gone to the Settings and Privacy page and scrolled completely down it and don't see any "GoodTwitter2" section. I did so while using Chrome browser so the app was active. Should I try it in Firefox using the new Twitter layout without the GoodTwitter2 app running?

________________________________

**Comment by buggleston** [comment]
> Thanks for getting back to me and trying to help. I have to ask, What GoodTwitter2 section? I've gone to the Settings and Privacy page and scrolled completely down it and don't see any "GoodTwitter2" section. I did so while using Chrome browser so the app was active. Should I try it in Firefox using the new Twitter layout without the GoodTwitter2 app running?

Click your profile image in the top-right, then click "Settings and Privacy." Then in the left-hand column, select "GoodTwitter2," and you'll see the Force Latest setting. If you're not seeing the left-hand column in settings, your browser window size might be causing that section to not be visible - try zooming out in the browser window (cmd-minus on Mac, ctrl-minus on Windows) and see if that helps.

**Comment by Handmedown222** [comment]
Thank You so much. The zooming out did the trick.

________________________________

**Comment by Bl4Cc4t** [comment]
same with #157, they seem to have changed the DOM a bit so my selectors didn’t work anymore.
