### ISSUE TITLE
Smaller/no header gap between navigation bar when scrolling down (Legacy Profile layout)

### ISSUE THREAD

**Issue by MrCelroy** [Bl4Cc4t/GoodTwitter2#156]
**Describe the feature**
When scrolling down using the Legacy profile, the gap between the header and nav bar is quite substantial which results in a smaller area to read tweets on screen
![image](https://user-images.githubusercontent.com/66327074/87036587-a073b880-c21d-11ea-9018-d0f677de3150.png)

![image](https://user-images.githubusercontent.com/66327074/87037095-4e7f6280-c21e-11ea-98b2-9a4aa764c9d2.png)

Would it be possible to reduce that gap or eliminate it completely? 

Iirc there was no gap in the old twitter profile page

**Comment by MrCelroy** [comment]
![image](https://user-images.githubusercontent.com/66327074/87041553-fa2bb100-c224-11ea-9e34-a23a1d1d7fce.png)
It would also be nice if the Whats happening tab did not show up on the legacy profile

**Comment by Bl4Cc4t** [comment]
> When scrolling down using the Legacy profile, the gap between the header and nav bar is quite substantial which results in a smaller area to read tweets on screen

Yeah, I’ll remove the gap. I already had some complaints about it, just wanted to try it out.
I think it looks good but I totally agree that it wastes space.

> It would also be nice if the Whats happening tab did not show up on the legacy profile

enabling `Hide Trends` works for me. The trends were present in the old layout too, so there’s no real point in removing them from the profile pages exclusively imo.

**Comment by zetorplugger** [comment]
> It would also be nice if the Whats happening tab did not show up on the legacy profile

Why do you think the What's happening tab should not be there?
