### ISSUE TITLE
Twitter color of a few elements no longer changes despite selecting a different color 

### ISSUE THREAD

**Issue by MrCelroy** [Bl4Cc4t/GoodTwitter2#157]
**Describe the bug**
The color of a few elements no longer changes despite selecting a different color, in my case red
**Screenshots**
![image](https://user-images.githubusercontent.com/66327074/87043075-1e888d00-c227-11ea-9701-cd361693bf7a.png)
![image](https://user-images.githubusercontent.com/66327074/87043164-3a8c2e80-c227-11ea-822c-d12c7e2cb4b7.png)

**Your configuation**
 - Browser (Chrome Version 83.0.4103.116)

 - Userscript Manager (Tampermonkey v4.10)

**Comment by Bl4Cc4t** [comment]
They changed the DOM a bit for that modal, that’s why it stopped working
