### ISSUE TITLE
Timeline randomly scrolls up and down when I stop on a post

### ISSUE THREAD

**Issue by ultracoolboy** [Bl4Cc4t/GoodTwitter2#158]
Whenever I'm scrolling down my timeline next thing you know when clicking on a tweet or video or even stop scrolling to like or retweet a post  I automatically get sent a few post above or worse sent all the way back to the top of my timeline, it's been soooo annoying like this happens randomly as well so I cannot predict if it's going to happen nor can I re create if besides randomly scrolling down my twitter timeline.

**Comment by Bl4Cc4t** [comment]
do you have biggerImagePreviews enabled? Please disable it and see if it helps.

**Comment by ultracoolboy** [comment]
I did have it enabled and I did disable it, it made things worse after disabling it as one random click and I go back to the very top of my timeline every single time sometimes when I try to click on an image.

**Comment by ultracoolboy** [comment]
ok so after some more testing after disableing big image preview I was able to re create the problem, I would click on a tweet and then when I go back to the timeline and click anywhere if it's on the image or website it shoots me back up to the top of my timeline and this dose happen as well when I refresh my twitter timeline for and scroll down

**Comment by Bl4Cc4t** [comment]
Okay, I'll close this issue in favor of the new one you made. (#164)
Sorry btw for not replying for two weeks, I didn't have that much time for this project.
