### ISSUE TITLE
[Bug] Back from thread button scrolls away and disappears - inconvenient

### ISSUE THREAD

**Issue by Darthagnon** [Bl4Cc4t/GoodTwitter2#159]
**Describe the bug**
When viewing a Tweet's thread, the ⬅ Thread (back to main view) button/bar at the top scrolls away, meaning to return to the main view, you need to scroll all the way to the top again - I'd like to request that New Twitter's default be maintained here, where the ⬅ Thread (back to main view) button/bar stays at the top of the page while scrolling.

**Screenshots**
https://imgur.com/gallery/DtkqFzX

**Your configuation**
 - Browser: Edgium 85.0.552.1 (Official build) dev (64-bit)
 - Userscript Manager: ViolentMonkey 2.12.7

**Comment by Darthagnon** [comment]
@Bl4Cc4t Thank you for the fix for this issue. I just discovered, however, that it's still a problem on Twitter search pages - if you visit a Twitter search ```https://twitter.com/search?q=something``` then the back arrow and header disappear on scroll.

**Comment by Bl4Cc4t** [comment]
That is intentional and will probably not be changed.
I think someone mentioned that having more space on the search page would be nice and I liked it, so I added that feature

**Comment by Darthagnon** [comment]
@Bl4Cc4t 19/11/2020 This issue has reappeared - when scrolling the replies to a tweet, the "Back" bar scrolls away and you need to scroll for miles to get back to the top of the page to go back.

**Comment by Bl4Cc4t** [comment]
It seems like I accidentally changed the style for this page when fixing #213/#215 and didn't change it back :/
