### ISSUE TITLE
Version 0.0.23 not working when i update

### ISSUE THREAD

**Issue by utenax** [Bl4Cc4t/GoodTwitter2#160]
**Please check the following before you continue**
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
Not working when i update the new verison. I reinstall Google Chrome and tampermonkey again,but that didn't work.No problem before update.
![2020_07_11_04_57 48_看图王_看图王](https://user-images.githubusercontent.com/68128912/87204332-20da0c80-c337-11ea-9599-f6cc1ab7a87e.jpg)

**Screenshots**
For display issues, adding screenshots or even videos of your screen is recommended.

**Your configuation**
 -  chrome 83.0.4103.116
 - Tampermonkey v4.10
 - Version 0.0.23

**Comment by GottaSlay** [comment]
Same issue for me as well on 0.0.23.

**Comment by Bl4Cc4t** [comment]
I am not sure why that is, I do not get any errors when reinstalling the script. Can you please open the Developer Tools (press F12) and tell me if there are any errors in the Console popping up?

**Comment by GottaSlay** [comment]
I got two errors regarding GoodTwitter 2. I'll post them as screenshots due to them being weirdly formatted otherwise. 

[https://i.imgur.com/2rZJOHR.png](url)
 [https://i.imgur.com/nhXEDaY.png](url)

I'm using Firefox 78.0.2 with Tampermonkey v4.11.6114

**Comment by utenax** [comment]
I  got 39 errors regarding GoodTwitter 2. Sorry I won't record screen,I put them on the long picture. If there is anything I can upload, please tell me.
![2020_07_11_23_22 49_看图王](https://user-images.githubusercontent.com/68128912/87228000-f9d01900-c3d0-11ea-82f3-7cf362f7e610.jpg)
![2020_07_11_23_23 09_看图王](https://user-images.githubusercontent.com/68128912/87228007-005e9080-c3d1-11ea-887f-654dca886531.jpg)
![071123373554_02020_07_11_23_30 37_看图王](https://user-images.githubusercontent.com/68128912/87228012-03f21780-c3d1-11ea-82d8-7836729f08ee.jpg)

**Comment by Bl4Cc4t** [comment]
@GottaSlay you truncated the only part that could help me (second screen)
![image](https://user-images.githubusercontent.com/6740726/87247605-275ea600-c455-11ea-966d-88b5ab5dcaf0.png)

@utenax you can safely ignore these *warnings* in the TM editor.

**Comment by GottaSlay** [comment]
My bad, I missed that. It keeps saying `eval:6`

**Comment by utenax** [comment]
@Bl4Cc4t  sorry....I don't understand programming,what should I do.This script still does not work,please help me...

**Comment by Bl4Cc4t** [comment]
@GottaSlay That does not help me either

@GottaSlay @utenax Can you please do the following:
- open Google Chrome
- go to twitter.com
- press F12
- change the view to console
- make a screenshot of the whole console with the error messages visible.
  - @utenax  you can take a screenshot on Win10 by pressing <kbd>Win</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd>
- share it here

**Comment by HadesMiller** [comment]
https://i.imgur.com/jJUU789.png

Does this help at all?

**Comment by utenax** [comment]
@Bl4Cc4t Is that okay?
![2020_07_13_18_07 01_看图王](https://user-images.githubusercontent.com/68128912/87293818-6e23cd00-c535-11ea-84d5-a7c923668d1e.jpg)
![2020_07_13_18_07 18_看图王](https://user-images.githubusercontent.com/68128912/87293832-724fea80-c535-11ea-8937-f98cc1f11a02.jpg)

**Comment by GottaSlay** [comment]
[https://i.imgur.com/0yXJdNV.png](url)

**Comment by Bl4Cc4t** [comment]
@HadesMiller @GottaSlay These are all *warnings* which are not related to the script at all.

@GottaSlay There is a line which says `[init] explore`; that comes from my script. Is there really no error message (red) afterwards? 

@utenax I have never seen this error before... Can you access the url that is shown above the error messages directly? 
[https://code.jquery.com/jquery-3.5.1.min.js](https://code.jquery.com/jquery-3.5.1.min.js)

**Comment by GottaSlay** [comment]
I reinstalled the script and refreshed twitter and got the old layout back but images fail to load. Now I am consistently getting a message in my console saying `[init] home GoodTwitter 2 - Electric Boogaloo.user.js:2165:13`

Clicking on the message takes me to a debugger and highlights the line 2165 `console.log(`[${changeType}] ${path}`)

**Comment by utenax** [comment]
@Bl4Cc4t I visit according to that URL,then I allow the URL to make a network connection(There are tips on sites like this).Then the script can work successfully!!!Thank you very much. It helped me a lot. I don’t have to see the new twitter layout more.
Have a nice day. Thank you!!!

**Comment by Bl4Cc4t** [comment]
@GottaSlay Well the message is supposed to appear the first time you open twitter (or reload the page)
Not sure what caused your errors though, but I’m glad that it works now. Be sure to report back if something breaks again.

@utenax That sounds rather complex, do you know why that was? Are you using some kind of personal ad blocker or something similar? Glad that it worked either way for you as well.

I’m gonna close this, feel free to reopen if something breaks again.
