### ISSUE TITLE
Timeline keeps going back to the top 

### ISSUE THREAD

**Issue by ultracoolboy** [Bl4Cc4t/GoodTwitter2#164]
(sorta a follow up from the last time I reported this after some testing on both layouts) 

so every single time when I refresh my twitter page or open it up in a new tab, scroll down and click on a image/ video I get sent back up to the top of my timeline same thing happens if I were to click on a tweet and go back to my timeline (kinda hate how twitter got rid of the simple overlay and makes it a new tab).  

An interesting thing I did find out is that the same thing also happens when I click on the search bar except this issue seems to also be on twitter new default layout (the new one they were forcing us to use) it only takes me to the top of the timeline if I were to click on the search bar and then click off it by clicking any blank space next to my timeline, it dose not happen when I click on a tweet, image, or video ( Figured this last bit I found out might help you out with this current bug I been dealing with) 

also following your responseto your last post yes I have disabled the big image preview dose not really change much

**Comment by geyerbri** [comment]
Came back to report this issue as well. This is particularly annoying when I've scrolled a long way down.
