### ISSUE TITLE
Pop Ups Disable Screen Area

### ISSUE THREAD

**Issue by ratboypest** [Bl4Cc4t/GoodTwitter2#165]
Honestly not sure if this is GoodTwitter2 or just twitter being terrible, but whenever i get a "your tweet was sent" or similar popup (usually at the bottom of the screen) the entire width of the screen where the popup is gets disabled. 

E.g. if a popup is on the screen, i am unable to click to type into the message box in DMs, as it just straight up doesnt register the clicks at all. Same for if i'm on the timeline and trying to like a tweet, if the like button is in that area it's unusable, as are all the other buttons, until the popup disappears. 

**-Firefox 78.0.2 (64-bit)
-Tampermonkey 4.11.6114**

**Comment by Bl4Cc4t** [comment]
Seems like this is not caused by the script, very weird behavior indeed.
Pretty easily fixable with two CSS rules :D
