### ISSUE TITLE
[bug] Search results + Legacy Profile Layout

### ISSUE THREAD

**Issue by goonis** [Bl4Cc4t/GoodTwitter2#167]
**Please check the following before you continue**
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**

Search links like https://twitter.com/search?q=string with checked option "Legacy Profile Layout" brings page with large empty place before tweets.

**Screenshots**
![image](https://user-images.githubusercontent.com/8069033/87929566-4978a980-ca8f-11ea-9be4-b45d09a9145c.png)

**Your configuation**
 - Chrome 84.0.4147.89 (Official Build) (64-bit)
 - Tampermonkey v4.10
 - GoodTwitter2 0.0.23

**Comment by Bl4Cc4t** [comment]
should be fixed in https://github.com/Bl4Cc4t/GoodTwitter2/commit/6f4d921f68b036652d044daf5c0e7a14009d2f7a

**Comment by goonis** [comment]
Yes, thank you.
