### ISSUE TITLE
Disabling "Sticky Sidebars" doesn't work on right-hand sidebar

### ISSUE THREAD

**Issue by buggleston** [Bl4Cc4t/GoodTwitter2#17]

**Comment by Bl4Cc4t** [comment]
also works for me, please elaborate on what site you were visiting when this happens, attach some screenshots etc.
I can’t really fix something that works on my end

**Comment by buggleston** [comment]
If I'm understanding the intended functionality, unchecking "Sticky Sidebars" should allow both the left and right sidebars to scroll completely out of view, leaving just the center feed visible. The left sidebar properly scrolls out of view, but the right sidebar only scrolls down a small distance before sticking in view. This can be seen in this video: https://imgur.com/a/iJND2Sp

**Comment by Bl4Cc4t** [comment]
This is some very weird behavior I have not seen before.
It seems like this only happens on chrome...
Setting `position: sticky` results in different outcomes depending on your browser.
