### ISSUE TITLE
After reinstalling the layout

### ISSUE THREAD

**Issue by Mikantsumikiwi** [Bl4Cc4t/GoodTwitter2#170]
Hey there, i been having a issue relating to reinstalling to good twitter. 

It happened when i updated to the latest version of chrome 84 and goodtwitter 2 for some strange reason stopped working. 

Stick to the new twitter UI.

So i decided to reinstall goodtwitter 2 and now the layout ended up like this.

![Good Twitter 2 Bug Report Screenshot](https://user-images.githubusercontent.com/67087732/88250940-332d4200-cc77-11ea-9953-6bf9ce6dc913.png)

I don't know if anyone else is having this issue right now, i can't see my DMs nor my notifications. 

I refuse to use the new twitter tbh.

**Comment by Bl4Cc4t** [comment]
closing in favor of #169
