### ISSUE TITLE
Missing items in classic view

### ISSUE THREAD

**Issue by dollhaus** [Bl4Cc4t/GoodTwitter2#171]
The classic view generated by the tool is missing the "tweet to \<user>" when browsing a user's profile. Additionally, profile pictures aren't managed properly on the same page. Attached is an image of a well-known user.

When browsing a user's page, the logged-in user's details shouldn't appear anywhere other than the titlebar. Additionally, it is necessary to scroll down the page by 300px to accomodate for the shutter hiding of the user's banner image.
![Capture](https://user-images.githubusercontent.com/33754407/88295132-ec7e2d00-ccf4-11ea-8d79-4c63cea73f45.PNG)

**Comment by Bl4Cc4t** [comment]
> The classic view generated by the tool is missing the "tweet to <user>" when browsing a user's profile. 

I have no idea where that button was and how it looked. Please attach an image if you can find one.

> Additionally, profile pictures aren't managed properly on the same page.

Are talking about them being sometimes stretched? That's fixed in https://github.com/Bl4Cc4t/GoodTwitter2/commit/dcf2b90ba6959fc8e437157ce6318629ed9dbdd3

> When browsing a user's page, the logged-in user's details shouldn't appear anywhere other than the titlebar.

See #153

> Additionally, it is necessary to scroll down the page by 300px to accomodate for the shutter hiding of the user's banner image.

See #156

**Comment by dollhaus** [comment]
@Bl4Cc4t Sorry I didn't get back to you sooner. 

I have no image of the "Tweet to" button, but it was the same structure as the "tweet" button in the top right hand corner of my first image. The button was, IIRC, in the left column about where the top of that red highlighted box is now. The differences were in width, which was adjusted to make the button as wide as the column itself. The action was opening a modal window with a pre-filled text input, which contained the twitter handle of the page being viewed.

**Comment by Bl4Cc4t** [comment]
Seems like I forgot to reply here, I'm sorry.
You can just press the "Tweet" button in the top right when on a profile, this automatically adds their handle at the beginning of the tweet.
