### ISSUE TITLE
Legacy Profile Layout: Multimedia should be moved to the left side

### ISSUE THREAD

**Issue by shootlazer** [Bl4Cc4t/GoodTwitter2#179]
**Please check the following before you continue**
- [x] Checked if the feature has not been requested before

**Describe the feature**
According to the old design, this tab on the right

![image](https://user-images.githubusercontent.com/46911545/89081121-f1914b00-d38a-11ea-8c06-9fb341af0b2f.png)

Should be here, on the left side

![image](https://user-images.githubusercontent.com/46911545/89081150-04a41b00-d38b-11ea-9f98-8a984719e452.png)

Reference:
![image](https://user-images.githubusercontent.com/46911545/89081180-15ed2780-d38b-11ea-86d3-93c18ffa61a9.png)

**Comment by HeIsAChar** [comment]
bump, this would improve my twitter experience a lil bit

**Comment by Bl4Cc4t** [comment]
Should be added in the next version!

**Comment by sugo512** [comment]
Just have an option to remove the video links and expand the width of the main content!

**Comment by Bl4Cc4t** [comment]
> Just have an option to remove the video links and expand the width of the main content!

I don't understand what you want. What video links? What main content? Is this even related to this issue?

**Comment by sugo512** [comment]
> 
> 
> > Just have an option to remove the video links and expand the width of the main content!
> 
> I don't understand what you want. What video links? What main content? Is this even related to this issue?

The subject of this issue is to move the multimedia links to the left. I ask that the multimedia links instead be hidden, then the center column can be wider.

![InkedCapture_LI (2)](https://user-images.githubusercontent.com/30544426/104140900-12fe5600-5371-11eb-8fee-5a8823cfa076.jpg)

**Comment by Bl4Cc4t** [comment]
Sorry, but that won't happen. I won't make the center column wider and hide other columns.

**Comment by HeIsAChar** [comment]
still waiting for this

**Comment by Bl4Cc4t** [comment]
Argh, guess I forgot this one. I'll go through all the open issues when I'm less busy in 1-2 weeks or so.
Sorry for the wait.

**Comment by Bl4Cc4t** [comment]
I made this into a toggle, so it can be used without the LPL as well. Sorry again for the wait.
