### ISSUE TITLE
Suggestion: Add option to hide/remove right-hand sidebar

### ISSUE THREAD

**Issue by buggleston** [Bl4Cc4t/GoodTwitter2#18]
I personally never use the "What's Happening" and "Who to Follow" features, so it would be great to just hide that column entirely and have the remaining content be centered in the window.

**Comment by Bl4Cc4t** [comment]
what about image panes on profiles and the search filters on `/search`?
what should happen to those?

**Comment by buggleston** [comment]
Great point - I neglected to consider how the right-hand sidebar is used in views other than the home feed.
