### ISSUE TITLE
Save images not in actual size

### ISSUE THREAD

**Issue by piyarad27** [Bl4Cc4t/GoodTwitter2#180]
**Describe the bug**
Usually when the user of the twitter R-mouse click and save image the image would save as full size but when I save image in this GoodTwitter2 v0.0.24 the image was same in small size. Like the actual size = 1920x1080, but save size = 680x489. For the full size I need to click the image to enlarge it which is a hassle. So can you fix it?

**Screenshots**
save image without enlarge the image
![ScreenHunter2](https://user-images.githubusercontent.com/58059329/89094167-dbc55b00-d375-11ea-97f5-632855ac4577.png)
save image after enlarge the image
![ScreenHunter_1](https://user-images.githubusercontent.com/58059329/89094119-b1739d80-d375-11ea-883e-a241db402870.png)

**Your configuation**
 - Browser (e.g. Firefox 53)
 - Userscript Manager (e.g. Tampermonkey v4.10)

**Comment by Bl4Cc4t** [comment]
Sorry for the late reply.

I won't change the preview images to show the full resolution ones, that would be very odd for people with limited traffic. 
Sorry, but downloading images or tweets from twitter has nothing to do with this project.
