### ISSUE TITLE
Script not working anymore?

### ISSUE THREAD

**Issue by cszabla** [Bl4Cc4t/GoodTwitter2#182]
Seems to have completely reverted to new Twitter? On vers .24 in Chrome

**Comment by MillhioreF** [comment]
Confirming, Twitter is throwing 401s on all its source maps causing the extension to fail to load.

**Comment by kfdz277** [comment]
patiently waiting for a fix for this. im on win 10 2004/firefox 79 and having the same issue

**Comment by Bl4Cc4t** [comment]
Please send your console output here, I do not have any issues with Firefox 79.0 and Chrome 84.0.4147.125.

Also @MillhioreF, source maps don't have anything to do with a failing script, they are in fact useless to the end consumer. Don't worry about them missing, you wouldn't get any benefits with them loading correctly anyways.
They are only used to navigate faster in the CSS source code when developing the styles of a site.

**Comment by cszabla** [comment]
FYI I updated Chrome from .105 to .125 and this fixed the issue. For those who need to, go to Settings -> About and you should be able to relaunch the browser in the latest version.

**Comment by Bl4Cc4t** [comment]
very weird. why did it break on firefox though?

**Comment by spriteclad** [comment]
Yeah it's still broken for me on Firefox 79.0.

**Comment by kfdz277** [comment]
dunno if this will help 
![image](https://user-images.githubusercontent.com/55974345/90076197-1fe92180-dccd-11ea-88a7-44078e72d07b.png)

**Comment by Bl4Cc4t** [comment]
I can't see any errors related to this project. Are there more below?
Please try it with Violentmonkey, maybe that works.

**Comment by spriteclad** [comment]
Just tested it with Violentmonkey and it seems to work just fine. Must be a bug in Tampermonkey, then...

**Comment by Bl4Cc4t** [comment]
I have no idea what causes this. Maybe it is a particular combination of Firefox settings that confuses Tampermonkey or something, idk. 
@spriteclad If you could share your console output too, that would be helpful. Maybe it contains some error messages that are useful.

**Comment by spriteclad** [comment]
> 
> 
> I have no idea what causes this. Maybe it is a particular combination of Firefox settings that confuses Tampermonkey or something, idk.
> @spriteclad If you could share your console output too, that would be helpful. Maybe it contains some error messages that are useful.

![image](https://user-images.githubusercontent.com/11656143/90301271-bb0c0380-de53-11ea-86af-6afe9856c060.png)

**Comment by kfdz277** [comment]
i still dont know what caused this but earlier today i had an issue with cytube's google drive script and nothing i could do with tampermonkey fixed _that_ issue, but i switched to violentmonkey and _this_ works now. it must be a tampermonkey issue then

**Comment by Bl4Cc4t** [comment]
@spriteclad looks like it loaded correctly. Did you use TM at that time?

I think the best idea is just to switch to VM for the time being, it tends to do better on Firefox at least.
