### ISSUE TITLE
Old reply layout

### ISSUE THREAD

**Issue by Aridow** [Bl4Cc4t/GoodTwitter2#188]
Well, now that Twitter changed the conversation layout, I think it would be better like it was in Legacy Twitter.

**Comment by Bl4Cc4t** [comment]
More details would be neat. I have no idea what you want :)

**Comment by Aridow** [comment]
Sure, here what the replies under a tweet look like for me now : 
![image](https://user-images.githubusercontent.com/65539338/91466934-214f4800-e890-11ea-9730-016172930f76.png)
There is no more line to separate the tweets and the vertical line at the left are different. 
While before the update, it was like that (screenshot from tweetdeck) : 
![image](https://user-images.githubusercontent.com/65539338/91469157-54470b00-e893-11ea-83d0-61142729dbc1.png)
When we click on a reply, the layout is also different, and it un-focuses when we click outside the reply : 
![image](https://user-images.githubusercontent.com/65539338/91469239-6c1e8f00-e893-11ea-8902-f5a109dd3c70.png)

**Comment by Bl4Cc4t** [comment]
That looks pretty damn disgusting. However, I do not have that change on my side, hence I cannot do anything about it (yet)

**Comment by bighairydaddy** [comment]
bumping this, because the new reply system is practiaclly **unusable** it makes me sick

**Comment by Bl4Cc4t** [comment]
I'm sorry, there is nothing I can do about it. I do not have that change yet.

**Comment by Aridow** [comment]
I don't have this new layout anymore. I don't know if it will be temporary or not...

**Comment by Bl4Cc4t** [comment]
Let's just hope you were a lucky tester and they scrapped it again!
