### ISSUE TITLE
Unable to scroll down to see all right-hand sidebar content

### ISSUE THREAD

**Issue by buggleston** [Bl4Cc4t/GoodTwitter2#19]
The right-hand column only scrolls down a small distance before "sticking." On my laptop, I'm unable to see the "Show more" button under "Who to Follow" or see the copyright box without zooming out to 80%.

**Comment by Bl4Cc4t** [comment]
works fine on my end, even when resizing the window. attach some screenshots please

**Comment by buggleston** [comment]
This appears to be working on my end now. Not sure if the issue was with Twitter or my computer/browser, but I will close this.

**Comment by buggleston** [comment]
Sorry, this still is broken when Sticky Sidebars is unchecked. I'm working on capturing and uploading a video to show the issue.

**Comment by buggleston** [comment]
Video of issue: https://imgur.com/a/iJND2Sp

**Comment by Bl4Cc4t** [comment]
please check if the issue still persists on your end
