### ISSUE TITLE
Stopped working with Tampermonkey

### ISSUE THREAD

**Issue by A7medme** [Bl4Cc4t/GoodTwitter2#191]
Stopped working with Tampermonkey couple weeks ago, tested today it's still working with Violentmonkey

**Your configuation**
 - Version 85.0.4183.83 (Official Build) (64-bit)
 - Tampermonkey v4.10

**Comment by Bl4Cc4t** [comment]
Is this #182? Since it works fine for me, I cannot offer any help without a log or something, please provide more information.
You also omitted your browser.

**Comment by A7medme** [comment]
Not sure if it's the same but there was no error in the console, removing the Tampermonkey extension and reinstalling it again in Chrome fixed it for me and the script loading now in Twitter 

Note: backup your scripts before you reinstall Tempermokney in Chrome, I lost all my scripts

**Comment by Bl4Cc4t** [comment]
Weird. Probably an issue with TM then, glad it works again!
