### ISSUE TITLE
Direct message notifications are not working

### ISSUE THREAD

**Issue by liseronberry** [Bl4Cc4t/GoodTwitter2#193]
**Describe the bug**
When I receive a new direct message, the notification is not working.
However, direct message notifications are working fine if I'm not using GoodTwitter2.

I'm sorry if it's a known issue or the procedure to report is incorrect.
I am using google translation.

**Your configuation**
 - Browser - Chrome 85.0.4183.83（Official Build）
 - Userscript Manager - Tampermonkey v4.10

**Comment by Bl4Cc4t** [comment]
What notifications do you mean? The little number in the navigation bar?
![image](https://user-images.githubusercontent.com/6740726/92392909-4ad56280-f11f-11ea-8558-6749869e040e.png)

Currently, it won't appear until you refresh the page or navigate somewhere else. However, I think I can probably change that.

**Comment by liseronberry** [comment]
I tried again.
Notifications were working on one of my accounts, but not on the other.
This seems to be a problem on Twitter.
I'm sorry, thank you for your quick response.

**Comment by Bl4Cc4t** [comment]
Okay then!
