### ISSUE TITLE
Timeline option popping up automatically

### ISSUE THREAD

**Issue by Pisfool** [Bl4Cc4t/GoodTwitter2#194]
From some point, the timeline option started automatically popping out on the left side whenever I load home. I erased cookies before this started happening, so I assume it might have something to do with that.

![gt2bug](https://user-images.githubusercontent.com/71142593/92948581-86ac5700-f494-11ea-93f7-240725e4bd5f.png)

 - Browser : Microsoft Edge Dev 87.0.634.0
 - Userscript Manager : Tampermonkey v4.10

**Comment by Aridow** [comment]
I also have this bug on Firefox, but not on Chrome.
