### ISSUE TITLE
Cropped image bug and horizontal scrollbar

### ISSUE THREAD

**Issue by Aridow** [Bl4Cc4t/GoodTwitter2#195]
Here are some bug that suddenly appeared today (Chrome, Firefox and Tampermonkey are up to date) : 
On Chrome/Firefox, when I click on an image, the upper part of the image is cropped : 
![image](https://user-images.githubusercontent.com/65539338/92950535-146c5000-f45d-11ea-95b9-4386c1d4100a.png)
When I close the image, there is an empty horizontal scrollbar that appears at the bottom of the page : 
![image](https://user-images.githubusercontent.com/65539338/92950675-5ac1af00-f45d-11ea-8c4c-16773d8b30bd.png)

This bug appeared at the same time as this one : #194

**Comment by Pisfool** [comment]
Yeah, I had this bug on the latest version of Microsoft Egde Dev too.
