### ISSUE TITLE
Header gone after new update, again

### ISSUE THREAD

**Issue by KudaKeil** [Bl4Cc4t/GoodTwitter2#199]
This is an old issue that is now back, the old one having been closed with a note to repost if it happened again.

After new update, UI currently looks like this.
https://i.imgur.com/YUR0D7Q.png
(I have trends and suggested follows hidden intentionally)

As you can see, the header's gone again. Earlier I got it to show up by opening a tab via a direct link to a tweet, but that doesn't seem to work every time. Refreshing and hard refreshing down't fix it.

Newest Firefox, primarily ViolentMonkey but with TamperMonkey as a backup. Having both on, or one off and the other on, makes no difference, but if I have TamperMonkey on by itself then refreshing takes me to the actual normal Twitter layout until I refresh again. If that matters.

**Comment by Bl4Cc4t** [comment]
Having both TM and VM usually causes issues, you should only use one manager.
Try to disable all your extensions except for one user script manager.

Can you please provide some screenshots of the console log? I can't reproduce this issue.

**Comment by KudaKeil** [comment]
I'll be real, I'm not sure how to get to the console log. I turned off
TM, hard refreshed, and still have the issue.

**Comment by Bl4Cc4t** [comment]
Simply press F12 and click on `Console` in the top part of the panel.
There should be some error messages (red, not yellow). You can paste the image here directly instead of linking to it, makes it a bit easier to keep track of things

**Comment by KudaKeil** [comment]
![firefox_Y5mSf7itCU](https://user-images.githubusercontent.com/45819723/93687799-39c51380-fa86-11ea-8c08-3853768e80d0.png)
Yeah, I see the issue. I'm not sure what it's referring to, and this isn't all of it (it was still adding errors as I took this), but it looks like solving one would solve all of them.

**Comment by Bl4Cc4t** [comment]
All other extensions are disabled?

Hm, these errors are not related to the script and it seems to be running.
If this is yet a again a CORS related issue, using Violentmonkey should do the trick.

If that does not help, you can try either of these things:
- use Chrome
- try these steps: https://github.com/Bl4Cc4t/GoodTwitter2/issues/101#issuecomment-643525816

**Comment by KudaKeil** [comment]
So, the Header Editor step didn't work and I'm not going to switch browsers for a single website, but I thought maybe deleting and re-enabling the script in VM would work. It didn't, so I switched to TM again, hard refreshed, and... suddenly it works again? I have no idea why it stopped working or why it started again.

**Comment by Bl4Cc4t** [comment]
Would've been interesting to see if chrome would've worked for you, but oh well.
So it probably is not CORS related, if the header editor did not work.
I cannot think of a reason why that all happened either, let's hope it stays that way.
Like last time, please reopen this issue if it happens again
