### ISSUE TITLE
Profile card section

### ISSUE THREAD

**Issue by shootlazer** [Bl4Cc4t/GoodTwitter2#20]
Profile section (on timeline) seems slightly off when choosing a smaller font on Twitter.

Old:
![image](https://user-images.githubusercontent.com/46911545/83306122-4df8b280-a202-11ea-9fc0-5d2129ef87aa.png)

Script version + smaller font:
![image](https://user-images.githubusercontent.com/46911545/83306135-52bd6680-a202-11ea-81b5-5459bf3de02b.png)

On the other side, the "Home, Notifications, Messages" tab buttons seem too close.
Maybe they could be set to a fixed size so it doesn't affect it?

**Comment by Bl4Cc4t** [comment]
Thank you for noticing these small things!

The font sizes in the dashboard profile is exactly the same as in the legacy version. But it looks like you selected a smaller font in the display settings.

**Comment by Bl4Cc4t** [comment]
Please update to `0.0.14` and tell me if it looks how you want it :)

**Comment by shootlazer** [comment]
> Thank you for noticing these small things!
> 
> The font sizes in the dashboard profile are exactly the same as in the legacy version. But it looks like you selected a smaller font in the display settings.

Yep, I just noticed that.
I selected a smaller font to try to match the old one, although I don't notice anything new on 0.0.14.

Maybe it those sizes could be "forced"?

**Comment by shootlazer** [comment]
> Thank you for noticing these small things!
> 
> The font sizes in the dashboard profile are exactly the same as in the legacy version. But it looks like you selected a smaller font in the display settings.

Yep, I just noticed it was due to being using a smaller font.
I selected a smaller font on my twitter to try to match the old global font (the new one font looks too big for me), although I don't notice anything new on 0.0.14.

Maybe those sizes could be "forced"?

**Comment by Bl4Cc4t** [comment]
I used the legacy sizes on the center setting (50%).
Should I decrease that? So that 25% has the legacy sizes for these parts?

**Comment by shootlazer** [comment]
> I used the legacy sizes on the center setting (50%).
> Should I decrease that? So that 25% has the legacy sizes for these parts?

I don't know if most people is decreasing the font size as well. So maybe the solution is adding an optional toggle for it.

**Comment by Bl4Cc4t** [comment]
a toggle? There is already an option to decrease the font size :D
I think this is more of a personal preference you have, but I increased the `font-size` for the stats by 1px.

**Comment by shootlazer** [comment]
> a toggle? There is already an option to decrease the font size :D
> I think this is more of a personal preference you have, but I increased the `font-size` for the stats by 1px.

I meant a toggle for having a bigger profile section font while having a smaller font overall!

**Comment by shootlazer** [comment]
> a toggle? There is already an option to decrease the font size :D
> I think this is more of a personal preference you have, but I increased the `font-size` for the stats by 1px.

I meant a toggle for having a fixed size profile section, while having a smaller font overall.
It looks slightly better now, but now it looks worse for the people who use the default font

**Comment by Bl4Cc4t** [comment]
> I meant a toggle for having a fixed size profile section, while having a smaller font overall.

Sorry, but I don’t think this is a feature worth making.

The text fits better after I increased it imo

**Comment by shootlazer** [comment]
> > I meant a toggle for having a fixed size profile section, while having a smaller font overall.
> 
> Sorry, but I don’t think this is a feature worth making.
> 
> The text fits better after I increased it imo

Ah, I see. But if you still wanted to make it 100% like the original, just move them a bit and it will be identical

**Comment by Bl4Cc4t** [comment]
To be precise. the items in the legacy version actually are a little closer to each other:
![image](https://user-images.githubusercontent.com/6740726/83565003-ea31fa80-a51d-11ea-8ad6-a0f9b0c853ad.png)
script:
![image](https://user-images.githubusercontent.com/6740726/83564994-e69e7380-a51d-11ea-85b8-106238295ffe.png)

**Comment by shootlazer** [comment]
True, I actually meant joining them juuuustttttt a little, don't know why I said separating them.
![image](https://user-images.githubusercontent.com/46911545/83572033-261e8d00-a529-11ea-88cc-3347456c4428.png)

**Comment by shootlazer** [comment]
I know it's a really minor thing, but for some reason feels really off to me, like something is unbalanced or something.

**Comment by Bl4Cc4t** [comment]
okay, how’s this?
![image](https://user-images.githubusercontent.com/6740726/83794802-cea22d80-a69e-11ea-928a-fbbf185bb27f.png)
