### ISSUE TITLE
It suddenly stopped working today

### ISSUE THREAD

**Issue by bighairydaddy** [Bl4Cc4t/GoodTwitter2#201]
Everything was working perfectly a few hours ago, but now it seems like the script doesnt work at all. Ive tried reinstalling it, clearing cache etc, but it just doesnt seem to work. Im sorry if im just stupid and its something on my side but i just cant get it to work again

Im using Chrome 85.0.4183.102
Tampermonkey v4.10
and the latest version of GoodTwitter2

![image](https://user-images.githubusercontent.com/34811552/93666373-65e09480-fa86-11ea-8086-7bca502a5cd7.png)

**Comment by bighairydaddy** [comment]
![image](https://user-images.githubusercontent.com/34811552/93666424-c8d22b80-fa86-11ea-8c5d-9c9c2b0e3e35.png)
not showing in the settings, which is basically proof that its not working altogether :(

**Comment by Bl4Cc4t** [comment]
No issues on my side.
Please disable all other extensions apart from TM.
Then, press F12 and navigate to the console tab. Make a screenshot of that and send it here

**Comment by bighairydaddy** [comment]
its.. back to normal now, i havent touched anything whatsoever i left my computer and came back now and its working properly, i am absolutely clueless as to how it returned to normal lol
