### ISSUE TITLE
Blue checkmark is missing on legacy profile layout

### ISSUE THREAD

**Issue by HeIsAChar** [Bl4Cc4t/GoodTwitter2#204]
**Please check the following before you continue**
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)

- [x] Checked if the issue has not been reported before

**Describe the bug**
There should've been a checkmark next to the name.

**Screenshots**
![Check](https://user-images.githubusercontent.com/40420649/95953708-bb8c3080-0de9-11eb-934d-b259599069d4.png)

**Your configuation**
 - Firefox
 - Violentmonkey

**Comment by Bl4Cc4t** [comment]
Ah yeah, I added the `follows you` part a while back, seems like I forgot that thing too...
