### ISSUE TITLE
Ugh. Looks like GoodTwitter is in the jeopardy again :(

### ISSUE THREAD

**Issue by Mavoy** [Bl4Cc4t/GoodTwitter2#209]
![Zrzut ekranu (424)](https://user-images.githubusercontent.com/21195105/96883130-576c0b00-1480-11eb-9777-08f994b5e324.png)

I'm getting this window every time opening Twitter in a new card now. Obviously, I could probably hide it with UBO for now, but that's definitely a sign that Twitter won't quit trying to make GoodTwitter2 unusable. "Disable the extension which masks your browser" - they don't even pretend what this is about.  Shameless (and almost synchronically with Facebook making new changes)

I use the website much less than I used to, anyway, relying on third party mobile app and Tweetdeck, but sometimes you just have to use it....

**Comment by Bl4Cc4t** [comment]
You have to disable GoodTwitter (not GT2) or any other user agent switcher to hide that window ([as noted in the readme](https://github.com/Bl4Cc4t/GoodTwitter2#installation))
