### ISSUE TITLE
I Can Only See the New Layout

### ISSUE THREAD

**Issue by Grip555** [Bl4Cc4t/GoodTwitter2#21]
I enabled the Tampermonkey extension and followed all of the instructions, but I can't get Twitter to go back to the old layout. I also changed security.csp.enable flag to false, so I don't know what I'm doing wrong.

**Comment by Bl4Cc4t** [comment]
To clarify: does it look like this when you click on the tampermonkey icon?
![image](https://user-images.githubusercontent.com/6740726/83363641-4ddfea80-a39b-11ea-9dc1-555b9d77fa78.png)

**Comment by Grip555** [comment]
Yes it does.

**Comment by Bl4Cc4t** [comment]
Hm, I’m pretty curious what the issue is.
Please open the Developer Tools (press F12) and go to “Console”. 
Reload the page and take a screenshot please (and send it here ofc).

**Comment by Grip555** [comment]
![image](https://user-images.githubusercontent.com/33988522/83364044-25a1bd00-a396-11ea-827a-b79246c55fc6.png)
It looks like this. The UI is more wonky that I remembered.

**Comment by Bl4Cc4t** [comment]
Okay, then please install the script again by clicking this [link](https://github.com/Bl4Cc4t/GoodTwitter2/raw/userinfo-error/twitter.gt2eb.user.js).
On `/home`, open the console and copy the part under `userInformation` and paste it here

**Comment by Grip555** [comment]
Thanks, it seems to be working now.

**Comment by Bl4Cc4t** [comment]
Well it is not fixed by that, I still need that information from you :)

**Comment by playing232** [comment]
> Okay, then please install the script again by clicking this [link](https://github.com/Bl4Cc4t/GoodTwitter2/raw/userinfo-error/twitter.gt2eb.user.js).
> On `/home`, open the console, copy the part under `userInformation` and paste it here

I was having the same issue. That link fixed it for me.

Is this the info you're asking for?
![Screenshot from 2020-05-31 19-16-40](https://user-images.githubusercontent.com/26071735/83370209-8a97eb80-a373-11ea-9b95-84bf365866c1.png)
```
userInformation:
{
  "bannerUrl": "",
  "avatarUrl": "https://pbs.twimg.com/profile_images/949260132654841856/yJIFDGGz_normal.jpg",
  "screenName": "svicidalbug",
  "name": "SvicidalBug",
  "stats": {
    "tweets": "30",
    "followers": "4",
    "following": "48"
  }
}
```

**Comment by Bl4Cc4t** [comment]
Yes, thank you. You seem to have no banner on your profile, that is what causes the issue.
