### ISSUE TITLE
Twitter profile pages - no tweets

### ISSUE THREAD

**Issue by dollhaus** [Bl4Cc4t/GoodTwitter2#214]
Ref: https://github.com/Bl4Cc4t/GoodTwitter2/issues/212

Using the dev branch, tweets still don't load properly.
![Capture](https://user-images.githubusercontent.com/33754407/97065907-c2b0fc80-15a8-11eb-85d0-2b0c0a55afb2.PNG)

**Comment by Bl4Cc4t** [comment]
Please do not use the code from the dev branch yourself unless you know what you're doing.
The compiled CSS is not yet uploaded, you have to compile `twitter.gt2eb.style.scss` with SASS first and replace the CSS in Tampermonkey yourself to see style changes.
