### ISSUE TITLE
Legacy layout fucked up badly

### ISSUE THREAD

**Issue by HeIsAChar** [Bl4Cc4t/GoodTwitter2#215]
**Please check the following before you continue**
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
I went on Twitter, saw GoodTwitter updated and suddenly it broke on me. I have no idea why.

**Screenshots**
![broken](https://user-images.githubusercontent.com/40420649/97464271-998dc480-1938-11eb-8ded-2711ed7464b9.png)

**Your configuation**
 - Firefox 68
 - Violentmonkey

**Comment by Bl4Cc4t** [comment]
Seems like they reverted https://github.com/Bl4Cc4t/GoodTwitter2/commit/488dff0b29a12bea768ba5ea673a8f148f1df14a again, was probably an accident

**Comment by Handmedown222** [comment]
Yes, it is happening again with me as well. Same problem they had before the update which makes me wonder if it is something Twitter is doing to mess up the app.

**Comment by HeIsAChar** [comment]
Okay, so the banner, profile pic, name, description etc are back but the tweets are still gone.
