### ISSUE TITLE
Twitter sending bad browser message

### ISSUE THREAD

**Issue by Handmedown222** [Bl4Cc4t/GoodTwitter2#218]
Now I'm getting a message when I go to twitter that my browser is no longer accepted or to remove the app that is masking my browser. Twitter is trying to get rid of your app I think. I tried deactivating it but still get the message on refreshing the page. I can close out the message and still use twitter, for now. I have Google Chrome browser and updated it today.
![image](https://user-images.githubusercontent.com/68014036/97791604-2c7d6780-1ba2-11eb-914f-2ab8e401bab3.png)

**Comment by Handmedown222** [comment]
Can anyone tell me why I am seeing this message whenever I click on the Tamper monkey icon at the upper right side of my screen? I am still getting the message that my browser in no longer supported even though I have Google Chrome and it is up to date. 
![image](https://user-images.githubusercontent.com/68014036/98015402-5a40f700-1dc2-11eb-851b-4f05e8ffb07f.png)

**Comment by Bl4Cc4t** [comment]
Same here as #209, this script does not mask your browser. You have to disable any other extensions that do this.
You could try this

**Comment by Bl4Cc4t** [comment]
I'll close this since I heard nothing back. Feel free to reply again if the issue still exists.
