### ISSUE TITLE
"K" and "M" doesn't appear in Legacy Profile

### ISSUE THREAD

**Issue by Aridow** [Bl4Cc4t/GoodTwitter2#220]
**Please check the following before you continue**
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before (but I hope I'm not mistaken)

**Describe the bug**
In Legacy Profile, the "K" for thousands and "M" for millions doesn't appear in "Followers". I think screenshots are better than words.

**Screenshots**
With Legacy : "17"
![image](https://user-images.githubusercontent.com/65539338/99073365-0dc19c80-25b6-11eb-8e99-17d44a18e2bf.png)
Without Legacy : "17,7 **k**"
![image](https://user-images.githubusercontent.com/65539338/99073406-229e3000-25b6-11eb-9103-c64f151cb64c.png)
With Legacy : "1"
![image](https://user-images.githubusercontent.com/65539338/99073469-39dd1d80-25b6-11eb-8b96-ae88c7f70c78.png)
Without Legacy : "1,1 **M**"
![image](https://user-images.githubusercontent.com/65539338/99073515-52e5ce80-25b6-11eb-907e-8c13c53f7a81.png)

**Your configuation**
- Last GoodTwitter2 version
 - Firefox 82.0.3/Chrome 86
 - Tampermonkey 4.11

**Comment by Bl4Cc4t** [comment]
Interesting, this issue comes from the thousands separator being a space with a french locale, I didn't know that.
Thanks for reporting.
