### ISSUE TITLE
Profile Pages Broken

### ISSUE THREAD

**Issue by Kosouda** [Bl4Cc4t/GoodTwitter2#227]
As of a couple days ago, profile info on the left and the header on the top no longer display with this script.  You can still scroll down as if the header was there.  Everything else displays and behaves normally.

Didn't a similar issue happen just a month or two ago?  God, it's like they go back and forth on this just to mess up this script.  It feels just like Steam and Youtube trying to force their utterly horrible styles on everyone.

**Comment by Bl4Cc4t** [comment]
I'm guessing this is #226. Please update the script to v0.0.27.

**Comment by Kosouda** [comment]
Yep, works perfectly now, yay!
