### ISSUE TITLE
Blocked and muted accounts not visible

### ISSUE THREAD

**Issue by BluSpring** [Bl4Cc4t/GoodTwitter2#228]
**Please check the following before you continue**
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
Basically, the blocked and muted accounts part of Twitter is hidden, and to see it again you have to open Inspect Element, or just be very, very zoomed out

**Screenshots**

![image](https://user-images.githubusercontent.com/20620191/101234158-09415d00-36f8-11eb-91af-774c6bad47bc.png)
![image](https://user-images.githubusercontent.com/20620191/101234141-f3339c80-36f7-11eb-8ae6-ee735af5f7e1.png)

**Your configuation**
 -  Google Chrome v87.0.4280.88
 - Tampermonkey v4.11

**System Models with screen resolutions, if that helps**
- MacBook Air 2017, with screen resolution of **1440x900** (screenshots taken using this)
- ASUS K55VD, with screen resolution of **1366x768**
  + SHARP LED TV with screen resolution of **1360x768**

**Comment by Bl4Cc4t** [comment]
Thanks for noticing, I found the issue and improved the css for the settings page overall.
