### ISSUE TITLE
Clicking "Home" no longer returns to top of timeline

### ISSUE THREAD

**Issue by geyerbri** [Bl4Cc4t/GoodTwitter2#229]
**Please check the following before you continue**
- [X] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [X] Checked if the issue has not been reported before

**Describe the bug**
Prior to 0.0.27, clicking on "Home" in navigation returned the reader to the top of their timeline in all cases. After updating to 0.0.27, this no longer works. (small update: if scrolled only a few tweets down, clicking "Home" does jump back to the top without any scrolling animation that it previously displayed. But after scrolling far enough, this no longer happens.)

**Screenshots**
n/a

**Your configuation**
 - Browser: Opera 72.0.3815.400
 - Userscript Manager: Tampermonkey 4.11.6120

**Comment by Bl4Cc4t** [comment]
Looks like I forgot to add a check for `/search` and `/explore`. Autoscrolling should now work everywhere, except on those two pages.

### Explanation
Why not there? Try the following:
- disable the script
- search for something
- scroll down
- click on the search bar
- click somewhere else

You may notice that it scrolls you all the way back up :/
I think this behavior is pretty annoying, so I disabled it. I hope this explains it a bit

**Comment by geyerbri** [comment]
Many thanks!
