### ISSUE TITLE
Bring back the legacy fullscreen profile header

### ISSUE THREAD

**Issue by bonkmaykrQ** [Bl4Cc4t/GoodTwitter2#230]
**Please check the following before you continue**
- [x] Checked if the feature has not been requested before

**Describe the feature**
In classic 2018 Twitter, the identity of the user profile covered the full page with the bio underneath on the left column next to the tweets.

### Current Result
![Screenshot_20201207_114733](https://user-images.githubusercontent.com/42302831/101385890-02465600-3882-11eb-8a07-9fd8aa1ae9f3.png)

### Desired Result
![unnamed (1)](https://user-images.githubusercontent.com/42302831/101385977-20ac5180-3882-11eb-9b31-e06e4b1bb24c.jpg)

**Comment by Bl4Cc4t** [comment]
Have you actually read the readme? Or looked at the screenshots? This already is a feature, you just have to turn it on in the settings.

**Comment by bonkmaykrQ** [comment]
> Have you actually read the readme? Or looked at the screenshots? This already is a feature, you just have to turn it on in the settings.

My bad >.< I'm a little hasty when i write issues.

Thanks for clarifying.
