### ISSUE TITLE
The Sidebar's emojis are pulled from plain text, not Twitter's SVG files.

### ISSUE THREAD

**Issue by clausies** [Bl4Cc4t/GoodTwitter2#234]
**Please check the following before you continue**
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
Twitter uses SVG files for their emojis, when displayed on profiles and such they're fine! But due to the implementation of Emoji 13.0, they don't show up in the preview sidebar.
For me it's actually always showed Microsoft's emojis there when I had older emojis and since Microsoft hasn't implemented 13.0's emojis yet it makes sense why it's not showing up! But I suppose I was curious if it would make more sense to keep it as Microsoft's emojis or use Twitter's SVGs for a more uniform look.
Inspect Element shows that it's using plain text for the sidebar vs my actual profile which pulls from Twitter's SVGs on their css sheet.
Also not a bug, but thanks for all the work you do on this extension. It's a lifesaver and I've been meaning to comment more on this repository since forever but I kept forgetting/lurking lol.

**Screenshots**
<img src="https://user-images.githubusercontent.com/50381214/102411683-53f88a00-3fc0-11eb-8198-a36519b6c939.PNG" width="344px"> <img src="https://user-images.githubusercontent.com/50381214/102411700-578c1100-3fc0-11eb-8925-8f2f9dbbd83c.PNG" width="460px">

**Your configuration**
- Chrome 87.0.4280.88
- Tampermonkey v4.11
- Windows 10 Home

**Comment by Bl4Cc4t** [comment]
Good point! I never thought about that. That was a very small change :D
And thanks for your kind words.
