### ISSUE TITLE
Header shows up while viewing image in fullscreen

### ISSUE THREAD

**Issue by MrCelroy** [Bl4Cc4t/GoodTwitter2#235]
**Describe the bug**
When viewing an image post in expanded view, the header shows up.
**Screenshots**
![image](https://user-images.githubusercontent.com/66327074/102601956-d073a000-415b-11eb-80b8-edc3f0b0b96d.png)
![image](https://user-images.githubusercontent.com/66327074/102602339-5db6f480-415c-11eb-8e37-ae2bc83858c6.png)

**Your configuation**
 - Google Chrome Version 87.0.4280.88 
 - Tampermonkey v4.11

**Comment by zetorplugger** [comment]
I have the same problem 
![image](https://user-images.githubusercontent.com/66390092/102646850-0bc69c80-4165-11eb-8766-82b566ccf834.png)

**Comment by nanakisan** [comment]
Also happening with me

![image](https://user-images.githubusercontent.com/2136875/102675249-82f03680-414d-11eb-99de-f93db65572ed.png)

Firefox 77.0.1
Tampermonkey v4.12.6123

**Comment by Bl4Cc4t** [comment]
Interesting. They moved some styles from the `body` to the `html` node.
