### ISSUE TITLE
Color theme not changing through settings menu

### ISSUE THREAD

**Issue by Jertzukka** [Bl4Cc4t/GoodTwitter2#24]
![image](https://user-images.githubusercontent.com/28263033/83444401-00738400-a454-11ea-8928-f1828b9be918.png)

First I tried to change the color theme from the Settings -> Display menu, but couldn't manage to get it work. After that only did I find out you can change it separately from clicking your profile picture and going to "Display". If there is a way to detect the theme change from the settings menu, that would be really good.

**Comment by Bl4Cc4t** [comment]
Oh, this is supposed to be working. Seems like I broke something at a certain point! Thank you for noticing.
