### ISSUE TITLE
Logout page refresh loop

### ISSUE THREAD

**Issue by frozenpandaman** [Bl4Cc4t/GoodTwitter2#243]
**Please check the following before you continue**
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
When clicking the log out confirmation button, I get taken to a URL `https://twitter.com/?logout=[epoch timestamp]` which refreshes/reloads repeatedly.

**Your configuration** (FYI this is typo'd as "configuation" in the GitHub issue template)
 - Chrome 87.0.4280.88
 - Tampermonkey 4.11

**Comment by Bl4Cc4t** [comment]
Thank you for your report! I never logout, so I guess I would've never seen this happen...
I also corrected the template, thanks for mentioning this as well.
