### ISSUE TITLE
Support for Chromium

### ISSUE THREAD

**Issue by geyerbri** [Bl4Cc4t/GoodTwitter2#25]
This is just a request for future full support for Chromium-based browsers like Opera.

Currently, the layout appears like this in Opera 68:

![Capture3](https://user-images.githubusercontent.com/5496867/83458317-57676200-a430-11ea-9f44-727700538276.PNG)

(this is obviously just the top portion)

Settings page does not load properly:

![Capture5](https://user-images.githubusercontent.com/5496867/83457138-07d46680-a42f-11ea-8150-22e57567a868.PNG)

Just wanted to throw this idea out there.

**Comment by arturo182** [comment]
I'm on Opera 68.0.3618.125 on Windows and everything looks good to me, maybe you have some extra userscripts or usercss enabled?

**Comment by Bl4Cc4t** [comment]
This issue is not related to your browser and has been reported before (from what I can tell).
Possible dupe: https://github.com/Bl4Cc4t/GoodTwitter2/issues/33

Please update to v`0.0.16` and try again.

**Comment by geyerbri** [comment]
Using information from #33, I have confirmed, the issue was my window width for the main page. I mistakenly assumed that, because old Twitter did not adjust the layout until the window was much narrower, that would be the case with this tool as well. Apologies. 

Updating to current version fixed the settings menu.
