### ISSUE TITLE
Clicking home doesn't scroll all the way to the top of the feed

### ISSUE THREAD

**Issue by buggleston** [Bl4Cc4t/GoodTwitter2#253]
**Please check the following before you continue**
- [X] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [X] Checked if the issue has not been reported before

**Describe the bug**
Expected behavior upon clicking "Home" link is to scroll to the very top of the feed. Currently, clicking Home only scrolls up partway. I tried toggling all of the GoodTwitter2 options, which had no apparent effect on this bug.

**Your configuation**
 - GoodTwitter2 0.0.28
 - Chrome 88.0.4324.96 (arm64)
 - MacOS 11.1
 - Tampermonkey v4.11

**Comment by Bl4Cc4t** [comment]
I cannot reproduce this. 
Does this happen with all other extensions except TM turned off? Is there some console output (I doubt it though)?

Does this happen everytime you scroll down and then click the home button? Regardless of the distance scrolled? How much does it scroll, if only partly?

similar issue (but not related): #229

**Comment by buggleston** [comment]
I just restarted Chrome, and now can't reproduce either. Sorry, could have sworn I'd tried that already.

**Comment by Bl4Cc4t** [comment]
Very weird. Be sure to report back if it happens again!
