### ISSUE TITLE
bar along top of screen when viewing images in full screen

### ISSUE THREAD

**Issue by ratboypest** [Bl4Cc4t/GoodTwitter2#256]
When viewing images in the fullscreen view (clicking on the image to expand it) there is a dark bar across the top of the page, blocking part of the image. Images that are not square and are taller than wider have more content covered. The bar is always in the same place, it does not adjust to the top of the image being shown.

Edit: I was using Tampermonkey BETA as initially the alpha did not work on firefox. I've reinstalled it on the alpha, and the issue seems to now be gone in both versions. I'll close this bug report, but leave it in case others ever experience this.

Screenshots
![image](https://user-images.githubusercontent.com/66927274/108589186-f4946d00-73a8-11eb-8553-c345ec703e7e.png)
![image](https://user-images.githubusercontent.com/66927274/108589349-9e73f980-73a9-11eb-9498-7490bfbc4327.png)
![image](https://user-images.githubusercontent.com/66927274/108589404-d0855b80-73a9-11eb-88d9-317152fbb502.png)

Configuration
 - Firefox 85.0.2 (64-bit)
 - Windows 10
 - Tampermonkey BETA v4.12.6127

**Comment by Bl4Cc4t** [comment]
> Edit: I was using Tampermonkey BETA as initially the alpha did not work on firefox. I've reinstalled it on the alpha, and the issue seems to now be gone in both versions. I'll close this bug report, but leave it in case others ever experience this.

Okay, I'm glad it fixed itself.

related: #235
