### ISSUE TITLE
It's so slow at processing

### ISSUE THREAD

**Issue by TweaFN** [Bl4Cc4t/GoodTwitter2#258]
**Please check the following before you continue**
- [ ] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [ ] Checked if the issue has not been reported before

**Describe the bug**
Slow Loading

**Screenshots**
For display issues, adding screenshots or even videos of your screen is recommended.

**Your configuation**
 - Microsoft Edge
 - Tampermonkey v4.10

**Comment by Bl4Cc4t** [comment]
I do not have any speed issues, I'm pretty sure this is not related to this project.
Can you confirm this behavior does not change when you turn the script off?
