### ISSUE TITLE
Use the Arial font

### ISSUE THREAD

**Issue by Diyamund** [Bl4Cc4t/GoodTwitter2#264]
**Please check the following before you continue**
- [*] Checked if the feature has not been requested before

The old Twitter used the Arial font. However, if you have it installed, the new Twitter uses Segoe UI.
I would like to have Twitter in Arial again.

**Comment by Bl4Cc4t** [comment]
With the next update, you will be able to set a custom font.
Then you can use whatever font you want, including Arial or even Comic Sans:
<details>
<summary>Twitter with Comic Sans</summary>

![image](https://user-images.githubusercontent.com/6740726/111869608-b1fe8a00-8980-11eb-85b8-c087cb1cd165.png)
</details>

(Please don't use Comic Sans though.)

**Comment by Diyamund** [comment]
Awesome! 👍
