### ISSUE TITLE
White Follow buttons

### ISSUE THREAD

**Issue by MistressAshai** [Bl4Cc4t/GoodTwitter2#266]
For some reason, Twitter rolled out silent tests for full white Follow buttons instead of whatever color the user has selected in the settings. However, this only happens on **_some_** accounts. If you could restore this, that would be fantastic!

![whytwitter](https://user-images.githubusercontent.com/8222603/111910588-36074f00-8a1f-11eb-8f1b-9bc60d56a143.png)

**Comment by Diyamund** [comment]
This happens on mine. I really don't like it. Please do this!

**Comment by Bl4Cc4t** [comment]
Already fixed this in https://github.com/Bl4Cc4t/GoodTwitter2/commit/b4e68f81d866fc007d9afdbb1844584269713c97.
Expect a new version this week, maybe tomorrow

**Comment by MistressAshai** [comment]
Thanks for the quick fix, however the "Edit Profile" button on your own profile is still white
