### ISSUE TITLE
Topics to follow hide 

### ISSUE THREAD

**Issue by nohar7** [Bl4Cc4t/GoodTwitter2#267]
pls add a hide to follow option ![image](https://user-images.githubusercontent.com/66399211/112401763-0ad97400-8d2d-11eb-8af7-b6353cf1975e.png)

**Comment by Bl4Cc4t** [comment]
I don't get this when using the site. Does enabling the "Hide Who to Follow" option remove this? 
If not, please go ahead and do the following:
- on the page this appears, press <kbd>F12</kbd>
- go to the tab "Console"
- paste `$("[data-testid=sidebarColumn]")` there and hit enter
- right click the response and choose the option "Copy -> Copy outerHTML" as shown below:
![image](https://user-images.githubusercontent.com/6740726/112516440-94259080-8d97-11eb-9f63-beb73ab44ce9.png)
- paste the result here and enclose it like this:
  ````
  ```content```
  ````

**Comment by NoThanksPal** [comment]
'''<div class="css-1dbjc4n r-aqfbo4 r-zso239 r-1hycxz" data-testid="sidebarColumn"><div class="css-1dbjc4n r-1pi2tsx" style="min-height: 1113px;"><div class="css-1dbjc4n" style="margin-top: 0px;"></div><div class="css-1dbjc4n r-gtdqiz r-1hycxz" style="top: 36.8px;"><div class="css-1dbjc4n r-1adg3ll"><div class="css-1dbjc4n"><div class="css-1dbjc4n r-vacyoi r-ttdzmv"><div class="gt2-dashboard-profile">
        <a href="/jeffrstone" class="gt2-banner" style="background-image: url(https://pbs.twimg.com/profile_banners/36969475/1509133353/600x200);"></a>
        <div>
          <a href="/jeffrstone" class="gt2-avatar">
            <img src="https://pbs.twimg.com/profile_images/778648911699468288/3Ty9WXnJ_bigger.jpg">
          </a>
          <div class="gt2-user">
            <a href="/jeffrstone" class="gt2-name">Jeff Stone</a>
            <a href="/jeffrstone" class="gt2-screenname">
              @<span>jeffrstone</span>
            </a>
          </div>
          <div class="gt2-toggle-acc-switcher-dropdown">
            <div></div>
            
      <svg class="gt2-svg" viewBox="0 0 24 24">
        <g><path d="M20.207 8.147c-.39-.39-1.023-.39-1.414 0L12 14.94 5.207 8.147c-.39-.39-1.023-.39-1.414 0-.39.39-.39 1.023 0 1.414l7.5 7.5c.195.196.45.294.707.294s.512-.098.707-.293l7.5-7.5c.39-.39.39-1.022 0-1.413z"></path></g>
      </svg>
          </div>
          <div class="gt2-stats">
            <ul>
              <li>
                <a href="/jeffrstone">
                  <span>Tweets</span>
                  <span>1,593</span>
                </a>
              </li>
              <li>
                <a href="/jeffrstone/following">
                  <span>Following</span>
                  <span>135</span>
                </a>
              </li>
              <li>
                <a href="/jeffrstone/followers">
                  <span>Followers</span>
                  <span>67</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div><div class="css-1dbjc4n r-1h3ijdo"></div><div class="css-1dbjc4n r-1ihkh82 r-1in3vh1 r-1867qdf r-1phboty r-rs99b7 r-1ifxtd0 r-1udh08x"><div class="css-1dbjc4n"><section aria-labelledby="accessible-list-12" role="region" class="css-1dbjc4n"><h1 aria-level="1" dir="auto" role="heading" class="css-4rbku5 css-901oao r-4iw3lz r-1xk2f4g r-109y4c4 r-1udh08x r-wwvuq4 r-u8s1d r-92ng3h" id="accessible-list-12"></h1><div aria-label="Timeline: " class="css-1dbjc4n"><div class="css-1dbjc4n"><div class="css-1dbjc4n r-1adg3ll r-1ny4l3l"></div><div class="css-1dbjc4n r-j7yic r-qklmqi r-1adg3ll r-1ny4l3l"><div class="css-1dbjc4n r-1wtj0ep r-ymttw5 r-1f1sjgu"><h2 aria-level="2" role="heading" class="css-4rbku5 css-1dbjc4n r-18u37iz"><div class="css-1dbjc4n r-k200y r-z80fyv r-1777fci r-1bymd8e"></div><div dir="auto" class="css-901oao css-cens5h r-18jsvk2 r-1qd0xha r-adyw6z r-1vr29t4 r-135wba7 r-bcqeeo r-qvutc0" style="-webkit-line-clamp: 3;"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Topics to follow</span></div></h2></div></div><div class="css-1dbjc4n r-j7yic r-qklmqi r-1adg3ll r-1ny4l3l"><a aria-labelledby="topic15 topic-name15 topic-description15 topic-follow-button15 topic-not-interested-button15" href="/i/topics/1303047383169736705" role="link" data-focusable="true" class="css-4rbku5 css-18t94o4 css-1dbjc4n r-1habvwh r-1loqt21 r-18u37iz r-1wtj0ep r-1ny4l3l r-ymttw5 r-1f1sjgu r-o7ynqc r-6416eg"><div class="css-1dbjc4n r-1awozwy r-18u37iz r-1wbh5a2 r-1hvjb8t"><div aria-label="Topic" class="css-1dbjc4n" id="topic15"></div><div class="css-1dbjc4n r-1wbh5a2"><div dir="auto" class="css-901oao r-18jsvk2 r-1qd0xha r-a023e6 r-b88u0q r-rjixqe r-bcqeeo r-qvutc0" id="topic-name15"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">$SPCE</span></div><div dir="auto" class="css-901oao css-cens5h r-m0bqgq r-1qd0xha r-a023e6 r-16dba41 r-rjixqe r-bcqeeo r-qvutc0" id="topic-description15" style="-webkit-line-clamp: 2;"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Stocks</span></div></div></div><div class="css-1dbjc4n r-1kihuf0 r-18u37iz r-1m04atk"><div class="css-1dbjc4n r-bcqeeo"><div role="button" data-focusable="true" tabindex="0" class="css-18t94o4 css-1dbjc4n r-1niwhzg r-1bs4hfb r-sdzlij r-1phboty r-rs99b7 r-1w2pmg r-15ysp7h r-gafmid r-1ny4l3l r-1fneopy r-o7ynqc r-6416eg r-lrvibr" id="topic-follow-button15"><div dir="auto" class="css-901oao r-1awozwy r-18jsvk2 r-6koalj r-18u37iz r-16y2uox r-1qd0xha r-a023e6 r-b88u0q r-1777fci r-rjixqe r-dnmrzs r-bcqeeo r-q4m81j r-qvutc0"><span class="css-901oao css-16my406 css-bfa6kz r-poiln3 r-bcqeeo r-qvutc0"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Follow</span></span></div></div></div><div aria-label="Set as not interested" role="button" data-focusable="true" tabindex="0" class="css-18t94o4 css-1dbjc4n r-1niwhzg r-42olwf r-sdzlij r-1phboty r-rs99b7 r-1w2pmg r-13hce6t r-15ysp7h r-4wgw6l r-1ny4l3l r-mk0yit r-o7ynqc r-6416eg r-lrvibr" id="topic-not-interested-button15"><div dir="auto" class="css-901oao r-1awozwy r-13gxpu9 r-6koalj r-18u37iz r-16y2uox r-1qd0xha r-n6v787 r-b88u0q r-1777fci r-1cwl3u0 r-dnmrzs r-bcqeeo r-q4m81j r-qvutc0"><svg viewBox="0 0 24 24" class="r-m0bqgq r-4qtqp9 r-yyyyoo r-1q142lx r-50lct3 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1srniue"><g><path d="M13.414 12l5.793-5.793c.39-.39.39-1.023 0-1.414s-1.023-.39-1.414 0L12 10.586 6.207 4.793c-.39-.39-1.023-.39-1.414 0s-.39 1.023 0 1.414L10.586 12l-5.793 5.793c-.39.39-.39 1.023 0 1.414.195.195.45.293.707.293s.512-.098.707-.293L12 13.414l5.793 5.793c.195.195.45.293.707.293s.512-.098.707-.293c.39-.39.39-1.023 0-1.414L13.414 12z"></path></g></svg><span class="css-901oao css-16my406 css-bfa6kz r-poiln3 r-bcqeeo r-qvutc0"></span></div></div></div></a></div><div class="css-1dbjc4n r-j7yic r-qklmqi r-1adg3ll r-1ny4l3l"><a aria-labelledby="topic16 topic-name16 topic-description16 topic-follow-button16 topic-not-interested-button16" href="/i/topics/1313525755347787776" role="link" data-focusable="true" class="css-4rbku5 css-18t94o4 css-1dbjc4n r-1habvwh r-1loqt21 r-18u37iz r-1wtj0ep r-1ny4l3l r-ymttw5 r-1f1sjgu r-o7ynqc r-6416eg"><div class="css-1dbjc4n r-1awozwy r-18u37iz r-1wbh5a2 r-1hvjb8t"><div aria-label="Topic" class="css-1dbjc4n" id="topic16"></div><div class="css-1dbjc4n r-1wbh5a2"><div dir="auto" class="css-901oao r-18jsvk2 r-1qd0xha r-a023e6 r-b88u0q r-rjixqe r-bcqeeo r-qvutc0" id="topic-name16"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">$NIO</span></div><div dir="auto" class="css-901oao css-cens5h r-m0bqgq r-1qd0xha r-a023e6 r-16dba41 r-rjixqe r-bcqeeo r-qvutc0" id="topic-description16" style="-webkit-line-clamp: 2;"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Stocks</span></div></div></div><div class="css-1dbjc4n r-1kihuf0 r-18u37iz r-1m04atk"><div class="css-1dbjc4n r-bcqeeo"><div role="button" data-focusable="true" tabindex="0" class="css-18t94o4 css-1dbjc4n r-1niwhzg r-1bs4hfb r-sdzlij r-1phboty r-rs99b7 r-1w2pmg r-15ysp7h r-gafmid r-1ny4l3l r-1fneopy r-o7ynqc r-6416eg r-lrvibr" id="topic-follow-button16"><div dir="auto" class="css-901oao r-1awozwy r-18jsvk2 r-6koalj r-18u37iz r-16y2uox r-1qd0xha r-a023e6 r-b88u0q r-1777fci r-rjixqe r-dnmrzs r-bcqeeo r-q4m81j r-qvutc0"><span class="css-901oao css-16my406 css-bfa6kz r-poiln3 r-bcqeeo r-qvutc0"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Follow</span></span></div></div></div><div aria-label="Set as not interested" role="button" data-focusable="true" tabindex="0" class="css-18t94o4 css-1dbjc4n r-1niwhzg r-42olwf r-sdzlij r-1phboty r-rs99b7 r-1w2pmg r-13hce6t r-15ysp7h r-4wgw6l r-1ny4l3l r-mk0yit r-o7ynqc r-6416eg r-lrvibr" id="topic-not-interested-button16"><div dir="auto" class="css-901oao r-1awozwy r-13gxpu9 r-6koalj r-18u37iz r-16y2uox r-1qd0xha r-n6v787 r-b88u0q r-1777fci r-1cwl3u0 r-dnmrzs r-bcqeeo r-q4m81j r-qvutc0"><svg viewBox="0 0 24 24" class="r-m0bqgq r-4qtqp9 r-yyyyoo r-1q142lx r-50lct3 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1srniue"><g><path d="M13.414 12l5.793-5.793c.39-.39.39-1.023 0-1.414s-1.023-.39-1.414 0L12 10.586 6.207 4.793c-.39-.39-1.023-.39-1.414 0s-.39 1.023 0 1.414L10.586 12l-5.793 5.793c-.39.39-.39 1.023 0 1.414.195.195.45.293.707.293s.512-.098.707-.293L12 13.414l5.793 5.793c.195.195.45.293.707.293s.512-.098.707-.293c.39-.39.39-1.023 0-1.414L13.414 12z"></path></g></svg><span class="css-901oao css-16my406 css-bfa6kz r-poiln3 r-bcqeeo r-qvutc0"></span></div></div></div></a></div><div class="css-1dbjc4n r-j7yic r-qklmqi r-1adg3ll r-1ny4l3l"><a aria-labelledby="topic17 topic-name17 topic-description17 topic-follow-button17 topic-not-interested-button17" href="/i/topics/1306651376743714816" role="link" data-focusable="true" class="css-4rbku5 css-18t94o4 css-1dbjc4n r-1habvwh r-1loqt21 r-18u37iz r-1wtj0ep r-1ny4l3l r-ymttw5 r-1f1sjgu r-o7ynqc r-6416eg"><div class="css-1dbjc4n r-1awozwy r-18u37iz r-1wbh5a2 r-1hvjb8t"><div aria-label="Topic" class="css-1dbjc4n" id="topic17"></div><div class="css-1dbjc4n r-1wbh5a2"><div dir="auto" class="css-901oao r-18jsvk2 r-1qd0xha r-a023e6 r-b88u0q r-rjixqe r-bcqeeo r-qvutc0" id="topic-name17"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">$ROKU</span></div><div dir="auto" class="css-901oao css-cens5h r-m0bqgq r-1qd0xha r-a023e6 r-16dba41 r-rjixqe r-bcqeeo r-qvutc0" id="topic-description17" style="-webkit-line-clamp: 2;"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Stocks</span></div></div></div><div class="css-1dbjc4n r-1kihuf0 r-18u37iz r-1m04atk"><div class="css-1dbjc4n r-bcqeeo"><div role="button" data-focusable="true" tabindex="0" class="css-18t94o4 css-1dbjc4n r-1niwhzg r-1bs4hfb r-sdzlij r-1phboty r-rs99b7 r-1w2pmg r-15ysp7h r-gafmid r-1ny4l3l r-1fneopy r-o7ynqc r-6416eg r-lrvibr" id="topic-follow-button17"><div dir="auto" class="css-901oao r-1awozwy r-18jsvk2 r-6koalj r-18u37iz r-16y2uox r-1qd0xha r-a023e6 r-b88u0q r-1777fci r-rjixqe r-dnmrzs r-bcqeeo r-q4m81j r-qvutc0"><span class="css-901oao css-16my406 css-bfa6kz r-poiln3 r-bcqeeo r-qvutc0"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Follow</span></span></div></div></div><div aria-label="Set as not interested" role="button" data-focusable="true" tabindex="0" class="css-18t94o4 css-1dbjc4n r-1niwhzg r-42olwf r-sdzlij r-1phboty r-rs99b7 r-1w2pmg r-13hce6t r-15ysp7h r-4wgw6l r-1ny4l3l r-mk0yit r-o7ynqc r-6416eg r-lrvibr" id="topic-not-interested-button17"><div dir="auto" class="css-901oao r-1awozwy r-13gxpu9 r-6koalj r-18u37iz r-16y2uox r-1qd0xha r-n6v787 r-b88u0q r-1777fci r-1cwl3u0 r-dnmrzs r-bcqeeo r-q4m81j r-qvutc0"><svg viewBox="0 0 24 24" class="r-m0bqgq r-4qtqp9 r-yyyyoo r-1q142lx r-50lct3 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1srniue"><g><path d="M13.414 12l5.793-5.793c.39-.39.39-1.023 0-1.414s-1.023-.39-1.414 0L12 10.586 6.207 4.793c-.39-.39-1.023-.39-1.414 0s-.39 1.023 0 1.414L10.586 12l-5.793 5.793c-.39.39-.39 1.023 0 1.414.195.195.45.293.707.293s.512-.098.707-.293L12 13.414l5.793 5.793c.195.195.45.293.707.293s.512-.098.707-.293c.39-.39.39-1.023 0-1.414L13.414 12z"></path></g></svg><span class="css-901oao css-16my406 css-bfa6kz r-poiln3 r-bcqeeo r-qvutc0"></span></div></div></div></a></div><div class="css-1dbjc4n r-j7yic r-qklmqi r-1adg3ll r-1ny4l3l"><a aria-labelledby="topic18 topic-name18 topic-description18 topic-follow-button18 topic-not-interested-button18" href="/i/topics/1313831294237773825" role="link" data-focusable="true" class="css-4rbku5 css-18t94o4 css-1dbjc4n r-1habvwh r-1loqt21 r-18u37iz r-1wtj0ep r-1ny4l3l r-ymttw5 r-1f1sjgu r-o7ynqc r-6416eg"><div class="css-1dbjc4n r-1awozwy r-18u37iz r-1wbh5a2 r-1hvjb8t"><div aria-label="Topic" class="css-1dbjc4n" id="topic18"></div><div class="css-1dbjc4n r-1wbh5a2"><div dir="auto" class="css-901oao r-18jsvk2 r-1qd0xha r-a023e6 r-b88u0q r-rjixqe r-bcqeeo r-qvutc0" id="topic-name18"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">$PLTR</span></div><div dir="auto" class="css-901oao css-cens5h r-m0bqgq r-1qd0xha r-a023e6 r-16dba41 r-rjixqe r-bcqeeo r-qvutc0" id="topic-description18" style="-webkit-line-clamp: 2;"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Stocks</span></div></div></div><div class="css-1dbjc4n r-1kihuf0 r-18u37iz r-1m04atk"><div class="css-1dbjc4n" style="min-width: 78px;"><div role="button" data-focusable="true" tabindex="0" class="css-18t94o4 css-1dbjc4n r-1niwhzg r-1bs4hfb r-sdzlij r-1phboty r-rs99b7 r-1w2pmg r-15ysp7h r-gafmid r-1ny4l3l r-1fneopy r-o7ynqc r-6416eg r-lrvibr" id="topic-follow-button18"><div dir="auto" class="css-901oao r-1awozwy r-18jsvk2 r-6koalj r-18u37iz r-16y2uox r-1qd0xha r-a023e6 r-b88u0q r-1777fci r-rjixqe r-dnmrzs r-bcqeeo r-q4m81j r-qvutc0"><span class="css-901oao css-16my406 css-bfa6kz r-poiln3 r-bcqeeo r-qvutc0"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Follow</span></span></div></div></div><div aria-label="Set as not interested" role="button" data-focusable="true" tabindex="0" class="css-18t94o4 css-1dbjc4n r-1niwhzg r-42olwf r-sdzlij r-1phboty r-rs99b7 r-1w2pmg r-13hce6t r-15ysp7h r-4wgw6l r-1ny4l3l r-mk0yit r-o7ynqc r-6416eg r-lrvibr" id="topic-not-interested-button18"><div dir="auto" class="css-901oao r-1awozwy r-13gxpu9 r-6koalj r-18u37iz r-16y2uox r-1qd0xha r-n6v787 r-b88u0q r-1777fci r-1cwl3u0 r-dnmrzs r-bcqeeo r-q4m81j r-qvutc0"><svg viewBox="0 0 24 24" class="r-m0bqgq r-4qtqp9 r-yyyyoo r-1q142lx r-50lct3 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1srniue"><g><path d="M13.414 12l5.793-5.793c.39-.39.39-1.023 0-1.414s-1.023-.39-1.414 0L12 10.586 6.207 4.793c-.39-.39-1.023-.39-1.414 0s-.39 1.023 0 1.414L10.586 12l-5.793 5.793c-.39.39-.39 1.023 0 1.414.195.195.45.293.707.293s.512-.098.707-.293L12 13.414l5.793 5.793c.195.195.45.293.707.293s.512-.098.707-.293c.39-.39.39-1.023 0-1.414L13.414 12z"></path></g></svg><span class="css-901oao css-16my406 css-bfa6kz r-poiln3 r-bcqeeo r-qvutc0"></span></div></div></div></a></div><div class="css-1dbjc4n r-j7yic r-qklmqi r-1adg3ll r-1ny4l3l"><a aria-labelledby="topic19 topic-name19 topic-description19 topic-follow-button19 topic-not-interested-button19" href="/i/topics/1306701659146301440" role="link" data-focusable="true" class="css-4rbku5 css-18t94o4 css-1dbjc4n r-1habvwh r-1loqt21 r-18u37iz r-1wtj0ep r-1ny4l3l r-ymttw5 r-1f1sjgu r-o7ynqc r-6416eg"><div class="css-1dbjc4n r-1awozwy r-18u37iz r-1wbh5a2 r-1hvjb8t"><div aria-label="Topic" class="css-1dbjc4n" id="topic19"></div><div class="css-1dbjc4n r-1wbh5a2"><div dir="auto" class="css-901oao r-18jsvk2 r-1qd0xha r-a023e6 r-b88u0q r-rjixqe r-bcqeeo r-qvutc0" id="topic-name19"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">$PENN</span></div><div dir="auto" class="css-901oao css-cens5h r-m0bqgq r-1qd0xha r-a023e6 r-16dba41 r-rjixqe r-bcqeeo r-qvutc0" id="topic-description19" style="-webkit-line-clamp: 2;"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Stocks</span></div></div></div><div class="css-1dbjc4n r-1kihuf0 r-18u37iz r-1m04atk"><div class="css-1dbjc4n r-bcqeeo"><div role="button" data-focusable="true" tabindex="0" class="css-18t94o4 css-1dbjc4n r-1niwhzg r-1bs4hfb r-sdzlij r-1phboty r-rs99b7 r-1w2pmg r-15ysp7h r-gafmid r-1ny4l3l r-1fneopy r-o7ynqc r-6416eg r-lrvibr" id="topic-follow-button19"><div dir="auto" class="css-901oao r-1awozwy r-18jsvk2 r-6koalj r-18u37iz r-16y2uox r-1qd0xha r-a023e6 r-b88u0q r-1777fci r-rjixqe r-dnmrzs r-bcqeeo r-q4m81j r-qvutc0"><span class="css-901oao css-16my406 css-bfa6kz r-poiln3 r-bcqeeo r-qvutc0"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Follow</span></span></div></div></div><div aria-label="Set as not interested" role="button" data-focusable="true" tabindex="0" class="css-18t94o4 css-1dbjc4n r-1niwhzg r-42olwf r-sdzlij r-1phboty r-rs99b7 r-1w2pmg r-13hce6t r-15ysp7h r-4wgw6l r-1ny4l3l r-mk0yit r-o7ynqc r-6416eg r-lrvibr" id="topic-not-interested-button19"><div dir="auto" class="css-901oao r-1awozwy r-13gxpu9 r-6koalj r-18u37iz r-16y2uox r-1qd0xha r-n6v787 r-b88u0q r-1777fci r-1cwl3u0 r-dnmrzs r-bcqeeo r-q4m81j r-qvutc0"><svg viewBox="0 0 24 24" class="r-m0bqgq r-4qtqp9 r-yyyyoo r-1q142lx r-50lct3 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1srniue"><g><path d="M13.414 12l5.793-5.793c.39-.39.39-1.023 0-1.414s-1.023-.39-1.414 0L12 10.586 6.207 4.793c-.39-.39-1.023-.39-1.414 0s-.39 1.023 0 1.414L10.586 12l-5.793 5.793c-.39.39-.39 1.023 0 1.414.195.195.45.293.707.293s.512-.098.707-.293L12 13.414l5.793 5.793c.195.195.45.293.707.293s.512-.098.707-.293c.39-.39.39-1.023 0-1.414L13.414 12z"></path></g></svg><span class="css-901oao css-16my406 css-bfa6kz r-poiln3 r-bcqeeo r-qvutc0"></span></div></div></div></a></div><div class="css-1dbjc4n r-1adg3ll r-1ny4l3l"><a href="/i/topics/picker/home" role="link" data-focusable="true" class="css-4rbku5 css-18t94o4 css-1dbjc4n r-1loqt21 r-1ny4l3l r-ymttw5 r-1yzf0co r-o7ynqc r-6416eg"><div dir="auto" class="css-901oao r-13gxpu9 r-1qd0xha r-a023e6 r-16dba41 r-rjixqe r-bcqeeo r-qvutc0"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Show more</span></div></a></div></div></div></section></div></div><div class="css-1dbjc4n r-1niwhzg r-1gm7m50 r-1867qdf r-1phboty r-1yadl64 r-1ifxtd0 r-1udh08x"><nav aria-label="Footer" role="navigation" class="css-1dbjc4n r-18u37iz r-1w6e6rj r-ymttw5"><a href="https://twitter.com/tos" target="_blank" dir="auto" role="link" data-focusable="true" class="css-4rbku5 css-18t94o4 css-901oao r-m0bqgq r-1loqt21 r-1qd0xha r-n6v787 r-16dba41 r-1cwl3u0 r-hrzydr r-bcqeeo r-j2kj52 r-qvutc0" rel=" noopener noreferrer"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Terms of Service</span></a><a href="https://twitter.com/privacy" target="_blank" dir="auto" role="link" data-focusable="true" class="css-4rbku5 css-18t94o4 css-901oao r-m0bqgq r-1loqt21 r-1qd0xha r-n6v787 r-16dba41 r-1cwl3u0 r-hrzydr r-bcqeeo r-j2kj52 r-qvutc0" rel=" noopener noreferrer"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Privacy Policy</span></a><a href="https://support.twitter.com/articles/20170514" target="_blank" dir="auto" role="link" data-focusable="true" class="css-4rbku5 css-18t94o4 css-901oao r-m0bqgq r-1loqt21 r-1qd0xha r-n6v787 r-16dba41 r-1cwl3u0 r-hrzydr r-bcqeeo r-j2kj52 r-qvutc0" rel=" noopener noreferrer"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Cookie Policy</span></a><a href="https://business.twitter.com/en/help/troubleshooting/how-twitter-ads-work.html" target="_blank" dir="auto" role="link" data-focusable="true" class="css-4rbku5 css-18t94o4 css-901oao r-m0bqgq r-1loqt21 r-1qd0xha r-n6v787 r-16dba41 r-1cwl3u0 r-hrzydr r-bcqeeo r-j2kj52 r-qvutc0" rel=" noopener noreferrer"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Ads info</span></a><div aria-expanded="false" aria-haspopup="true" aria-label="More" role="button" data-focusable="true" tabindex="0" class="css-18t94o4 css-1dbjc4n r-hrzydr r-j2kj52"><div dir="auto" class="css-901oao r-m0bqgq r-1qd0xha r-n6v787 r-16dba41 r-1cwl3u0 r-bcqeeo r-qvutc0">More<svg viewBox="0 0 24 24" class="r-4qtqp9 r-yyyyoo r-ip8ujx r-dnmrzs r-1p4rafz r-bnwqim r-1plcrui r-lrvibr"><g><circle cx="5" cy="12" r="2"></circle><circle cx="12" cy="12" r="2"></circle><circle cx="19" cy="12" r="2"></circle></g></svg></div></div><div dir="auto" class="css-901oao r-m0bqgq r-1qd0xha r-n6v787 r-16dba41 r-1cwl3u0 r-hrzydr r-bcqeeo r-j2kj52 r-qvutc0"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">© 2021 Twitter, Inc.</span></div></nav></div></div></div></div></div></div></div>'''

**Comment by NoThanksPal** [comment]
I've also been getting the 'Topics to Follow' showing since the latest update earlier today/yesterday.  Enabling the "Hide Who to Follow" option doesn't remove this.  I've posted what you had requested from nohar7; let me know if you need anything else. Thanks.

**Comment by Bl4Cc4t** [comment]
@NoThanksPal thank you for posting this. I renamed the option "Hide Who to Follow" to "Hide Follow Suggestions", which now should include topics as well.
