### ISSUE TITLE
explore button only appears in mini window

### ISSUE THREAD

**Issue by itay10000** [Bl4Cc4t/GoodTwitter2#268]
the explore buttons only appears in the mini window, when in full screen it gets replaced by a search bar

![2021-03-25 (1)](https://user-images.githubusercontent.com/81339028/112406163-4ddf1b80-8d1c-11eb-8abc-534a6b04f425.png)

![2021-03-25 (2)](https://user-images.githubusercontent.com/81339028/112406168-5172a280-8d1c-11eb-8781-4ea909c2ab61.png)

**Comment by Bl4Cc4t** [comment]
This is expected behavior. The link to the explore page can be found in the dropdown menu on large screens.

**Comment by itay10000** [comment]
> This is expected behavior. The link to the explore page can be found in the dropdown menu on large screens.

no it doesn't
![2021-03-25 (4)](https://user-images.githubusercontent.com/81339028/112530914-a3183d00-8daf-11eb-8663-5685021dec61.png)

**Comment by Bl4Cc4t** [comment]
weird... it should be there. I'll look into this

**Comment by itay10000** [comment]
Maybe the new newsletter button replaced it in the february update...
