### ISSUE TITLE
Twitter search bar not appearing when searching and scrolling

### ISSUE THREAD

**Issue by Aridow** [Bl4Cc4t/GoodTwitter2#27]
On Twitter.com/home, there is the twitter search bar in the top right corner. But in twitter.com/hashtag or twitter.com/search*, the search bar doesn't appear there, and it's inconvenient when we scroll down since we have to go to the top of the page to use the search bar again.

**Comment by Bl4Cc4t** [comment]
what do you think, should that whole part stay on top for `/search`?
![image](https://user-images.githubusercontent.com/6740726/84026528-c7746b80-a98d-11ea-9e6f-1024ff47afd2.png)

**Comment by Aridow** [comment]
I think it would be good if the search bar was sticky, like on twitter.com/home or on users' profile.

**Comment by Aridow** [comment]
I think the new update is great, but the /home design (with the searchbar on the same bar as Home/Notifications/Messages, at the right) would be better because as is it, it hides a little of the page.

**Comment by Bl4Cc4t** [comment]
The box now hides when you scroll down, I hope that’s fine with you

**Comment by Aridow** [comment]
Is there a way to update the script to see the changes ?

**Comment by Bl4Cc4t** [comment]
I’ll release the new version tomorrow, I wanted to wait until #121 was resolved, sorry

**Comment by Aridow** [comment]
It seems the search bar doesn't appear anymore when we scroll up (I updated GoodTwitter2).

**Comment by Bl4Cc4t** [comment]
should be fixed in https://github.com/Bl4Cc4t/GoodTwitter2/commit/05a84b9194bf23c3bc70c84d9ad0ba9222409163
