### ISSUE TITLE
Make "Show More Tweets" more noticeable

### ISSUE THREAD

**Issue by arturo182** [Bl4Cc4t/GoodTwitter2#271]
It would be great if there was an option to make the "Show More Tweets" section more noticeable, maybe by changing the background color or adding arrow emojis around the text. It's way too easy to scroll past it and miss many tweets.

![image](https://user-images.githubusercontent.com/249082/112610186-b44b6300-8e1c-11eb-9343-9bf09ebb48da.png)

**Comment by Bl4Cc4t** [comment]
Managed to stumble across one, I think I managed to make it look a bit better:
![image](https://user-images.githubusercontent.com/6740726/115850134-e9e86980-a425-11eb-87f7-0a072a527f0a.png)
I added an additional padding of `30px` and made the text bold.

Here is the html for future reference:
```html
<div style="position: absolute; width: 100%; transform: translateY(17192px); transition: opacity 0.3s ease-out 0s;">
  <div class="css-1dbjc4n r-1ila09b r-qklmqi r-1adg3ll r-1ny4l3l">
    <div role="button" tabindex="0" class="css-18t94o4 css-1dbjc4n r-1777fci r-1pl7oy7 r-1ny4l3l r-o7ynqc r-6416eg r-13qz1uu">
      <div class="css-1dbjc4n r-16y2uox r-1wbh5a2 r-1777fci">
        <div dir="auto" class="css-901oao r-1n1174f r-1qd0xha r-a023e6 r-16dba41 r-rjixqe r-bcqeeo r-q4m81j r-qvutc0"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Show more Tweets</span></div>
      </div>
    </div>
  </div>
</div>
```

**Comment by Bl4Cc4t** [comment]
Funnily enough, this change makes this button on tweet pages also bigger:
![image](https://user-images.githubusercontent.com/6740726/115907708-8aac4880-a469-11eb-9e4c-b83c68a981d3.png)

I doubt this is needed, is it?

**Comment by arturo182** [comment]
Thanks for looking into this :) Yeah, the "show more replies" doesn't have to be larger but if there's no way to have just one be larger than I think we can live with both being large :D

**Comment by Bl4Cc4t** [comment]
Oh, this can easily be done on `/home` only. I'm not sure if "Show more tweets" also appears on `/search` and `/explore`, I added all 3 just in case.
