### ISSUE TITLE
Bunch up icons in non-selected tweets

### ISSUE THREAD

**Issue by Diyamund** [Bl4Cc4t/GoodTwitter2#278]
- [*] Checked if the feature has not been requested before

On the old twitter layout, the like, retweet, and reply buttons were more bunched up than they are now. I want this back on Twitter.

![image](https://user-images.githubusercontent.com/44238627/113498133-d190c900-94cf-11eb-8a02-a5818fbec298.png)

Note: The share button doesn't appear because I'm logged out (Twitter removed all signed in old layout pages)
It doesn't affect spacing. It's just to the side.

**Comment by Bl4Cc4t** [comment]
This was easy to do.

Now I noticed you wrote "non-selected tweets", but what should happen on the tweet pages?
![image](https://user-images.githubusercontent.com/6740726/114549847-d0933080-9c61-11eb-9904-3e75d03528f1.png)
old style:
![image](https://user-images.githubusercontent.com/6740726/114550245-44353d80-9c62-11eb-9939-2de1b9d4eb63.png)

I would need to send a request for every tweet to get the number of replies though. 
The other numbers would be shown twice, I feel like changing this would be useless, what do you think?
