### ISSUE TITLE
Scroll bar issue

### ISSUE THREAD

**Issue by Aridow** [Bl4Cc4t/GoodTwitter2#28]
On twitter.com/search*, when I scroll, my scroll bar is displayed weirdly, going randomly up and down. I'm on firefox.

**Comment by Bl4Cc4t** [comment]
Cannot reproduce on the latest version.
Please update to the latest version and try again. 
I’m fixing things left and right and don’t really know what exact version you were using...

**Comment by Aridow** [comment]
I updated to the latest version and it seems I don't have this issue anymore.

**Comment by Bl4Cc4t** [comment]
That’s good to hear!
