### ISSUE TITLE
"The Media could not be played"

### ISSUE THREAD

**Issue by Sora-yx** [Bl4Cc4t/GoodTwitter2#295]
Hello,
I had this strange bug for a while now. Basically, I cannot watch video from my own tweets. It tries to play it and show the first image for like one second, then immediately display an error saying "The media could not be played".
If I click on "Reload" it simply repeats the exact same process: show one image, then display the same error.

![0](https://user-images.githubusercontent.com/50106301/117220138-ec27cc00-ae06-11eb-9359-f22fe4f70115.PNG)

This seems to only happen with my own tweets as I can watch video from other people fine. Also, it doesn't happen immediately, like, when I send a new tweet which contains a video, I can watch it fine for like a few minutes. Eventually, I start getting this error, then I can no longer play it properly. It works fine if I turn off the add-on though.

 - Browser: Firefox 88.0.1 (64 bits)
 - Userscript Manager: Tapermonkey v4.13.6137

Thank you for this Userscript btw, I've been using it since pretty much the beginning, really awesome work.

**Comment by Bl4Cc4t** [comment]
I just noticed them too on my end. However, I do get them with media from other profiles as well, and also with photos.
These issues seem to not be related to the script though, I get them as well when it is disabled.
Could you please check if you get these issues when using [the mobile layout](https://mobile.twitter.com)?

And thanks for your kind words, I appreciate it!

**Comment by Sora-yx** [comment]
Turns out I did jump to conclusion a bit fast. I thought this was the script because I got video working fine when trying with Edge instead of Firefox. However, you were right, the issue also happens to both mobile layout and also when the script is disabled, so my mistake. This isn't something new, I had this for like months now, so I don't think it's gonna be fixed anytime soon. Anyway, sorry for the inconvenience.

**Comment by Bl4Cc4t** [comment]
For months? Hm, I don't really know how to help you with this, maybe your video got corrupted. 
Sometimes, a certain resolution of a video gets corrupted and stops playing after a few seconds. I don't know how that happens, but the lower res version are usually still fine.
