### ISSUE TITLE
RT/Like counter text is rendered very poorly at 110% zoom when logged in

### ISSUE THREAD

**Issue by sukerokushin** [Bl4Cc4t/GoodTwitter2#299]
**Please check the following before you continue**
- [X] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [X] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
For some reason, it looks like the text for the retweet and like counters are very poorly emboldened when both Firefox and Edge on my machine are at 110% zoom. I thought it was a quirk of MacType (an alternative text renderer for Windows) at first, but I uninstalled it and it still persisted. I even changed the font with GT2's custom setting and it still looked borked at 110%, but while i was writing this, I realized it only happens when logged in. For some reason, after you log in, that bold heading-like face changes from Segoe UI to TwitterChirp, and the latter is what looks like ass. I've no idea what to make of this.

**Screenshots**
Firefox at 100% zoom
![image](https://user-images.githubusercontent.com/55974345/118607016-19209b00-b786-11eb-89b8-f24c8adcbad7.png)

Firefox at 110% zoom
![image](https://user-images.githubusercontent.com/55974345/118607048-2178d600-b786-11eb-92ca-d247fec88afe.png)

**Your configuration**
 - Firefox 88.0.1 and Microsoft Edge 88.0.705.81
 - Violentmonkey 2.13.0 (FF) and Tampermonkey 4.13.6138 (Edge)
 - Microsoft Windows 10, version 20H2, build 19042.985
 - 1080p display, scaling at 100%, default text size

**Comment by Bl4Cc4t** [comment]
I cannot reproduce this issue. As usual with these, I suspect this change to be something that's likely depending on where you live (or some other random criteria). I do think this was a mistake on twitter's side though, but I can try to fix it if it persists.

Btw: if you look closely, all elements that are not added by this script have their font changed.

First off, can you inspect some element (maybe the bold retweet count) and tell me what font-family it has?
Please take a screenshot like this: 
![image](https://user-images.githubusercontent.com/6740726/118633567-e8665300-b7d1-11eb-9c49-dc7ac08d6eab.png)
Please repeat the process for a custom font you set.

On another note, when I set TwitterChirp as font, it looks different from your image.
![image](https://user-images.githubusercontent.com/6740726/118635405-d4bbec00-b7d3-11eb-8fa3-a8c6fe62f7c5.png)
Your glyphs are a bit flatter, looks like they cahnged the font itself too...

**Comment by sukerokushin** [comment]
lmfao I had a feeling it was gonna be something crazy specific and unrepeatable, and also probably twitter's fault.
That image of you setting TwitterChirp manually is how it always used to look, but I got my laptop back from repairs just yesterday after 3 months and it just started borking in that way

here's what no override looks like
![image](https://user-images.githubusercontent.com/55974345/118660276-088b1780-b7bc-11eb-9b6d-0b6119837066.png)

and here's what it looks like with a custom font override (i just put lucida console for the heck of it)
![image](https://user-images.githubusercontent.com/55974345/118660160-f01afd00-b7bb-11eb-9f3c-ac1fb36cbc6c.png)

For what it's worth, the rt/like counter text looked exactly the same on either run, and the inspector shows the override being greyed out (though I don't know what that implies)

**Comment by Bl4Cc4t** [comment]
[you can try to add this css](https://gist.github.com/Bl4Cc4t/f75ba5aeaa7fc845cd44e6e898f8b2de/raw/1e8545c8c350e42f98e1ec3f63feaedb10d5e6c8/gt2.css.2020-05-19), I added the class to the list require font changing.
If you don't know how to do that, take a look at the spoiler in this comment: https://github.com/Bl4Cc4t/GoodTwitter2/issues/272#issuecomment-808587850

I have to one feature for v0.0.30, then I can probably release it. Sorry if I'm being so lazy with the project...

**Comment by sukerokushin** [comment]
uhhhhh I can't figure out to do this on Violentmonkey, sorry

But you don't need to feel bad for "being lazy"! You're doing fine lol, I'd personally only have a problem if the script just straight up broke for days on end.

**Comment by Bl4Cc4t** [comment]
Oh, this can only be done with Tampermonkey. You would need to use that for testing, you can uninstall it afterwards again.
If you do that, please make sure not have both TM and VM running the script at the same time.

I also update the file I linked again, I think it had some errors before.

If something breaks completely, I always try to fix it as soon as possible with an update :)

**Comment by sukerokushin** [comment]
Didn't fix anything, sadly.
![image](https://user-images.githubusercontent.com/55974345/119246792-6fa92300-bb52-11eb-967f-b0a821fad1ff.png)
Extremely positive I did everything correctly too, so idk what's up. Used the new version of the file you linked and everything.

**Comment by Bl4Cc4t** [comment]
Okay, how about [this one](https://gist.github.com/Bl4Cc4t/f75ba5aeaa7fc845cd44e6e898f8b2de/raw/7402ca878bb8254a75f1d8c3212b3f9e098c980c/gt2.css.2020-05-23)?

**Comment by sukerokushin** [comment]
Seems fixed now, the font is Segoe UI instead of TwitterChirp. I'll keep using it for a couple hours to see if it somehow breaks but, looks good!

**Comment by sukerokushin** [comment]
Been A/B testing with Violentmonkey and also a freshly installed version of the script in Tampermonkey and there's not a single issue. 

Funnily enough, it also changes something (for the better) that I didn't even notice until now. Twitter originally used the default system font for Japanese text (in Windows's case, Meiryo), but it now uses my browser's default Japanese font. That definitely works out for me and probably won't change anyone else's experience. Hell, it might even be the actual intended behavior lol

**Comment by Bl4Cc4t** [comment]
Oh okay, interesting... Thanks for the update!
