### ISSUE TITLE
The inside of the Follow buttons is still black.

### ISSUE THREAD

**Issue by Pisfool** [Bl4Cc4t/GoodTwitter2#327]
Before I updated my Goodtwitter to the recent version, I have applied the custom color in v0.0.3.0, not aware that the fix wasn't in that version. Instead of what I wanted happening, it has only changed the outline's color, making it even harder to see. Upon realizing that, I have updated it to v0.0.3.1, but the problem is still there. The inside is still black with the custom colored outlines. 

Is there any fix to this?
![image](https://user-images.githubusercontent.com/71142593/129348646-c668cf3f-0609-4aa2-9088-489edc2b8a6b.png)

Config:
 - Brave 1.28.105 Chromium: 92.0.4515.131 (64-bit)
 - Tampermonkey v4.13

**Comment by Bl4Cc4t** [comment]
This should be fixed now in v0.0.31.1, you just need to update.
