### ISSUE TITLE
GoodTwitter2 settings not showing up

### ISSUE THREAD

**Issue by Gestrid** [Bl4Cc4t/GoodTwitter2#33]
As you can see, they're nowhere to be found in my Twitter settings page.  The sidebar on the left seems to be missing.  (I've edited out my personal info from the screenshot.)
![image](https://user-images.githubusercontent.com/6199046/83468889-2137db80-a44c-11ea-9e16-8ff8bb20eba6.png)

The sidebar becomes visible if I do something like open up my display settings.  (Again, I've edited out my personal info.)
![image](https://user-images.githubusercontent.com/6199046/83469106-c652b400-a44c-11ea-8aac-0f66393bcbdc.png)

**Comment by thinkpad4** [comment]
Yeah, I can't find the settings either

**Comment by brownbob9889** [comment]
check the bottom left of your 2nd image lol

**Comment by phlummox** [comment]
Same issue - my browser details are:

&nbsp;&nbsp;Browser: Google Chrome on amd64 Linux
&nbsp;&nbsp;Version: 83.0.4103.61-1

and this is with version 0.0.14 of the script.

My workaround: for the moment, I've added a bookmark to https://twitter.com/settings/gt2 to my bookmarks bar, so I can get to the GT2 settings easily.

**Comment by Bl4Cc4t** [comment]
This problem only appeared on screens smaller than 1350px. Should be fixed now!
