### ISSUE TITLE
Revert of font of unselected tabs

### ISSUE THREAD

**Issue by Diyamund** [Bl4Cc4t/GoodTwitter2#332]
**Please check the following before you continue**
- [*] Checked if the feature has not been requested before

**Describe the feature**
The font weight (and maybe color? I don't know) of unselected tabs was changed in the new Twitter update.
![image](https://user-images.githubusercontent.com/44238627/129426646-f7ec9d6a-6a65-4ff4-b588-81e25874b5d5.png)
Please revert this change.

**Comment by Bl4Cc4t** [comment]
good spot!
