### ISSUE TITLE
Revert look of account suspended/doesn't exist page

### ISSUE THREAD

**Issue by Diyamund** [Bl4Cc4t/GoodTwitter2#333]
**Please check the following before you continue**
- [*] Checked if the feature has not been requested before

**Describe the feature**
Twitter decided it was a good idea to make the font size of the suspended/doesn't exist page huge, and to left align it.
![image](https://user-images.githubusercontent.com/44238627/129426753-63717afd-4e91-4bcd-ae22-b896fc967a90.png)
Please revert this.

**Comment by Bl4Cc4t** [comment]
![image](https://user-images.githubusercontent.com/6740726/135630600-04b962fd-5746-4941-9922-0593679ecdfa.png)
I changed a few things, is this look okay?
