### ISSUE TITLE
No Follow button

### ISSUE THREAD

**Issue by dimdenGD** [Bl4Cc4t/GoodTwitter2#337]
There is no follow and message button:  
![sc](https://lune.dimden.dev/0426c7cef4.png)
  
For some reason `gt2-legacy-profile-nav-right` has `style="display: none !important;"` and when I try to remove it, it just appears back immediately.  
![anim](https://lune.dimden.dev/0c7722d6ac.gif)

having latest tampermonkey and goodtwitter versions, i also have my own style on (u can see it on screenshot) but even when it's disabled it still happens

**Comment by dimdenGD** [comment]
HUH?? Apparently my adblocker was blocking it.... No idea why !

**Comment by Bl4Cc4t** [comment]
that's indeed very weird. what adblocker do you use?

**Comment by dimdenGD** [comment]
AdGuard, i had to add that button to whitelist

**Comment by Bl4Cc4t** [comment]
interesting, I'll try reproducing it.
