### ISSUE TITLE
Large image previews appear distorted on chrome + scroll glitch

### ISSUE THREAD

**Issue by Toshino-Kyoko** [Bl4Cc4t/GoodTwitter2#34]
![image](https://user-images.githubusercontent.com/66244793/83470600-94dbe780-a450-11ea-9a2d-2b9df7bd5a76.png)

scroll glitch
https://www.youtube.com/watch?v=GvIevfjb2AQ

**Comment by AkiraJkr** [comment]
Can confirm this.
![image](https://user-images.githubusercontent.com/27028529/83485581-b99a8400-a47d-11ea-87b7-8399db2f090d.png)

**Comment by arturo182** [comment]
Disabling "Bigger Image Previews" fixes this for now.
![image](https://user-images.githubusercontent.com/249082/83508002-9ac1df00-a4c9-11ea-97c6-6a720a6b373e.png)

**Comment by Bl4Cc4t** [comment]
This is some pretty funky stuff!
Firefox does not seem to be affected by this, that’s probably why I overlooked that.
Only one value needs to be changed!
