### ISSUE TITLE
Good Twitter Script.... Broke?

### ISSUE THREAD

**Issue by mechobree** [Bl4Cc4t/GoodTwitter2#341]
**Describe the bug**
After first installing the script, it worked perfectly, then after I set my settings to what I preferred, everything just suddenly broke and a lot of features are missing. There's no drop down menu for accounts anymore, and there's no navigation bar options anymore.

**Screenshots**
![firefox_08 29 21 09 51](https://user-images.githubusercontent.com/29335214/131252947-f6528431-e360-4c8c-9488-b37c10efdf79.png)

**Your configuration**
 - Browser Firefox 91.0.2 (64-bit)
 - Userscript Manager Tampermonkey v4.13.6136

**Comment by Bl4Cc4t** [comment]
Hm, weird. The script thinks that you're logged out, that's why it looks that way.
It does that by checking if the `twid` cookie is set. Are you blocking cookies or something on twitter perhaps?
If not, I may need to think of another way of checking if the use is logged in...

**Comment by mechobree** [comment]
Nope, I don't believe I'm blocking any cookies.

**Comment by mechobree** [comment]
Ah I'm very sorry, but after you said that the error was because the script thought I was logged out, I tested if logging out and then in again fixed it, which it did.

**Comment by mechobree** [comment]
If it's able to be fixed by just relogging, I think there's a high chance it was a once in awhile glitch that's more on my side rather than anything wrong with your script. :>
