### ISSUE TITLE
"Show more Tweets" button doesn't always work

### ISSUE THREAD

**Issue by MegpoidGUMI** [Bl4Cc4t/GoodTwitter2#342]
**Please check the following before you continue**
- [*] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [*] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [*] Checked if the issue has not been reported before

**Describe the bug**
There's a couple of weird behaviors with the "Show more Tweets" button as of late. Sometimes clicking the button will load a few more tweets (around 3 or 4), but often times it will hang for a bit and then not load anything (see screenshot). Other times instead of loading new tweets, clicking the button will instead scroll you back up to the top of your timeline.

**Screenshots**
![Image](https://i.imgur.com/QS95A4u.gif)

**Your configuration**
 - Browser: Brave version 1.25.72
 - Userscript Manager: Tampermonkey v4.13

**Comment by MegpoidGUMI** [comment]
Closed since this appears to be fixed now, must have been an issue on Twitter's end

**Comment by Bl4Cc4t** [comment]
Hm, this indeed sounds like an issue on the site itself. 
I imagine it's possible to get timeouts when clicking that button after leaving the timeline for a while.
Good that it fixed itself at least.
