### ISSUE TITLE
Threads broken (Started in the last 24h)

### ISSUE THREAD

**Issue by 40469420** [Bl4Cc4t/GoodTwitter2#344]
**Describe the bug**
Twitter threads on timeline are "blocked out"? I dont know how to properly explain it if you check the screenshots you can see what i mean. It was fine yesterday and i just woke up and checked and the timeline has lines separating threads and not classifying replies as replies

**Screenshots**

![7utDRC81cJ](https://user-images.githubusercontent.com/15026269/132807896-71133add-c044-4125-8cd9-c859522d3db3.gif)

**Your configuration**
 - Browser: Firefox. Havent restarted my firefox in days so it hasnt updated.
 - Userscript Manager: Tampermonkey

**Comment by 40469420** [comment]
Disabling goodtwitter2 removes the lines and classifies replies as replies again. Forgot to add that part so i dont know if it was a twitter update or a GT2 update that broke something.

**Comment by 40469420** [comment]
Good twitter OFF (Default Twitter looks so FUGLY MAN) no line threw replies
![gw31ubCQZN](https://user-images.githubusercontent.com/15026269/132809493-517aa02f-40a4-484b-be18-aed52f75ff85.gif)


Good Twitter on (Line threw my reply to my own tweet)
![DriIKc1lqB](https://user-images.githubusercontent.com/15026269/132809666-15bc01d3-0880-4ed7-b8cb-5d70012a196c.gif)

**Comment by Bl4Cc4t** [comment]
they removed these dividers completely at first with the new "design change" they did a bit ago, now they got added again I guess.

there is however another issue I see now in your screenshots

![image](https://user-images.githubusercontent.com/6740726/133271309-07d7b195-7879-4717-aa8d-39ef5c2ea9ba.png)
![image](https://user-images.githubusercontent.com/6740726/133271284-7b0fbe6f-415d-4c77-b4b8-822d90b478e0.png)

the new font allows you to use symbols that most other fonts do not support. I have to find a solution for that.

**Comment by Bl4Cc4t** [comment]
ah... now I know why I added this.
![image](https://user-images.githubusercontent.com/6740726/133274192-45f64daa-7794-4bc8-be30-88273ff7728b.png)

**Comment by 40469420** [comment]
fixed mine by just downloading the new font and setting it in goodtwitter2's font settings so it shows the icons. The icons are in there could prob add them by default to goodtwitter2 somehow.

(Got the file from here https://twitter.com/ecnepsnai/status/1425506533484412937 and converted it to TTF)

![n3khpWiId0](https://user-images.githubusercontent.com/15026269/133281894-7d9aac2b-67c6-45dd-91f0-e696e0e2f9fd.png)

**Comment by 40469420** [comment]
Had to update my reply because i didn't see your other comment my bad <3

**Comment by Bl4Cc4t** [comment]
you do not need to download and install the font to use the new one. just use "TwitterChirp" as name in the custom font field.
I'll try to exclude these two symbols and use chirp for them so they show up. see #346

**Comment by Bl4Cc4t** [comment]
while I fixed the initial error here, I haven't released the update yet, you have to wait a bit I'm afraid.

I took a pretty long break and have lots of things to fix here, so the next update will fix this with a lot of other things!
