### ISSUE TITLE
Images on Feed Cropped

### ISSUE THREAD

**Issue by TheFlippedSides** [Bl4Cc4t/GoodTwitter2#345]
Images on my feed are being cropped despite the Bigger Image Previews option being checked. Not sure if this a wide-spread issue, but it's happening on two different computers within the past day.  

**Your configuration**
 - Browser: Firefox v92
 - Userscript Manager: Tampermonkey v4.13.6136

**Comment by sukerokushin** [comment]
happened to me too, accidentally thought it was that extension's fault because it was also broken by whatever recent twitter change broke this lol

**Comment by Biggiepax** [comment]
Having the same issue as well.

Using Chrome and Tempermonkey

**Comment by allstar299** [comment]
The same issue happens to me too.

**Comment by sukerokushin** [comment]
awesome! thanks
