### ISSUE TITLE
Can't install on Violentmonkey because the emojiRegex resource doesn't exist anymore

### ISSUE THREAD

**Issue by puyoxyz** [Bl4Cc4t/GoodTwitter2#352]
**Please check the following before you continue**
- [x] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
Can't install on Violentmonkey because the emojiRegex resource doesn't exist anymore

[emojiRegex](https://github.com/mathiasbynens/emoji-regex/raw/main/es2015/index.js) from `// @resource      emojiRegex https://github.com/mathiasbynens/emoji-regex/raw/main/es2015/index.js` is a 404

**Screenshots**
![image](https://user-images.githubusercontent.com/15311104/135712839-d6013f4e-0519-42e1-9983-67d26c26f8da.png)

**Your configuration**
 - Browser: LibreWolf (fork of Firefox) 92.0.1
 - Userscript Manager: Violentmonkey v2.13.0

**Comment by Bl4Cc4t** [comment]
I just released v0.0.32, please try updating. It should fix this issue!

**Comment by puyoxyz** [comment]
Yep, it works now
