### ISSUE TITLE
Timeline randomly becomes jello (Threads jiggling specifically tied to any long images or long gifs)

### ISSUE THREAD

**Issue by 40469420** [Bl4Cc4t/GoodTwitter2#353]
**Describe the bug**
Playing with the new update (Fixed 99% of all the bugs we have had good job and thank you!) and noticed that long images turn the timeline into jello. Any type of long image will jiggle most of the time. Example gif is included this isnt just a single pic ive noticed it on a few different threads and in some replies it was just the easiest to gif without accidentally putting porn in the gif.
(mutuals need to stop retweeting porn on my TL lol)

**Screenshots**
[Uncompressed gif](https://www.baka.wtf/u/ObpEwyDzAT.gif)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/15026269/135734519-8bd6bc37-0007-4d30-a056-de9dfab5288b.gif)

**Your configuration**
 - Firefox (latest)
 - Tampermonkey

(Doesnt happen on base non modded twitter checking the same threads over)

**Comment by 40469420** [comment]
Also just from my POV it seems to be tied to QRT but i could be completely off the mark. I've noticed it more on any QRT of and image that also includes and image but ive seen it in replies with images attached as well.

**Comment by Bl4Cc4t** [comment]
Hm, I cannot reproduce this bug. Maybe you're right and expanding the images in quote retweets breaks something... Could you please test if this style fixes it for you?

Here is how to change it: https://github.com/Bl4Cc4t/GoodTwitter2/issues/272#issuecomment-808587850
And here is the new style: https://gist.github.com/Bl4Cc4t/6f3c1c50e05b7bb7614467d955f29198/raw/dd845c87163ddeb9f37be12c4951d231f3c484f7/gt2.css.2021-10-03
