### ISSUE TITLE
Seperate follow suggestions option

### ISSUE THREAD

**Issue by alice945** [Bl4Cc4t/GoodTwitter2#354]
**Please check the following before you continue**
- [x] Checked if the feature has not been requested before

**Describe the feature**
The "Hide Follow Suggestions" option should be seperated for the timeline and the sidebar. I'd like to be able to see user follow suggestions in the sidebar, but have no suggestions in the timeline.

**Comment by Bl4Cc4t** [comment]
Good idea. How does this look?
![image](https://user-images.githubusercontent.com/6740726/135749824-ced8689b-aa93-4992-af1c-7c31d9ad0c07.png)

**Comment by alice945** [comment]
Looks good, thank you.
