### ISSUE TITLE
Timeline stopped auto-loading

### ISSUE THREAD

**Issue by arturo182** [Bl4Cc4t/GoodTwitter2#358]
I've been running v0.0.32 since it was released a few days ago, I haven't changed any settings in the last days or made any changes to the script itself and yet today suddenly my timeline instead of auto-loading new tweets, it started showing this:

![image](https://user-images.githubusercontent.com/249082/137036893-993d91de-c7b3-4cfe-b1e0-ece3548a7fc8.png)

I tried playing around with the "Disable Auto Refresh" and "Keep Tweets" settings, but none of the ways they can be enabled/disabled changes this behaviour.

It would be less annoying if the page stayed scrolled to the position where it was when I clicked the Show Tweets prompt, but instead, it always jumps to the top.

Since I haven't changed anything regarding GT2, it seems to be a change done by Twitter themselves.

**Comment by Bl4Cc4t** [comment]
Another weird bug I cannot replicate...

How does this happen specifically, when you go to home and do nothing? Is the tab focused?
Or do you scroll down to some extent?

For me activating the "Disable Auto Refresh" toggle doesn't do anything anymore, it just reloads new tweets.

Also, this big box is not created by the script, it's from Twitter. Do you also have that issue without the script activated?

**Comment by arturo182** [comment]
It seems to be a recent change by Twitter, maybe it's not enabled for everyone but it's definitely pissing a lot of people off: https://twitter.com/search?q="show%20x%20tweets"&src=recent_search_click&f=live

It's always on the home page, doesn't matter if the tab is focused or not, if the page is scrolled to the top or not, it will just keep increasing the number as new tweets are added but I need to press the box to show the tweets. At that point, it loads the tweets and scrolls all the way up. So you have to either remember what was the top tweet before you click it or take note of the number the box shows and then count down that many tweets from the top. It's like they're trying to see if they can break their users...

It's the same with and without the script.

**Comment by arturo182** [comment]
Would it be possible to have GT2 remember the current position and go back to it when the box is pressed, that would make Twitter many times more usable at the moment.
