### ISSUE TITLE
script not working properly

### ISSUE THREAD

**Issue by narcoticcoin** [Bl4Cc4t/GoodTwitter2#359]
twitter has done something to mess up the script when i first go to the page it is back to the new twitter layout like the script isnt working if i reload to get it back to how i want it [this](https://imgur.com/a/d7Wmqv0) is what it looks like all the top buttons are gone except explore

**Comment by Bl4Cc4t** [comment]
reminds me of #341, can you test if you have the cookie `twid` set?
Instructions are here: https://github.com/Bl4Cc4t/GoodTwitter2/issues/341#issuecomment-928298148

**Comment by Bl4Cc4t** [comment]
just paste it again in the console

**Comment by narcoticcoin** [comment]
twid=u%3D19210222; ct0= dnt=1; personalization_id="v1_RBPu
