### ISSUE TITLE
Please bring back the green retweet and red hearts when expanding an image

### ISSUE THREAD

**Issue by brownbobbrownbob** [Bl4Cc4t/GoodTwitter2#36]
![image](https://i.imgur.com/GIVVglY.png)

When you see an image (all good for me on videos), without expanding by clicking on it, you get green retweets and red hearts.

When you expand it, the retweets and hearts are white.

Can you make it so that when you expand it, the retweet and hearts have their respective colors?

**Comment by brownbobbrownbob** [comment]
I have 3 files of old twitter web pages and 3 screenshots if you need references. Please ask if you need them, making it exactly like old twitter would be perfect

**Comment by Bl4Cc4t** [comment]
I keep forgetting about this, I wanted to add that a lot sooner :D
Thanks for reminding me. Will be added for sure!

**Comment by Bl4Cc4t** [comment]
Try it out and let me know if this is to your liking.
