### ISSUE TITLE
Messages button disappears when refreshing in a Direct Message

### ISSUE THREAD

**Issue by BluSpring** [Bl4Cc4t/GoodTwitter2#364]
**Please check the following before you continue**
- [x] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
When you directly load or refresh in a DM page, the Messages button will just disappear even in other screens, and it will only come back if you refresh outside of the DM page.

**Screenshots**
https://user-images.githubusercontent.com/20620191/139698451-7f54d383-feb0-4358-951c-fe82f516d7ae.mp4

**Your configuration**
 - Chrome 95.0.4638.54
 - Tampermonkey v4.13

**Comment by Bl4Cc4t** [comment]
good job spotting that one, thanks
