### ISSUE TITLE
Drop-Down Navigation Padding Issues + No See X New Tweets

### ISSUE THREAD

**Issue by salromano** [Bl4Cc4t/GoodTwitter2#37]
A couple of issues.

I noticed that outside of the home page, the padding in the drop-down menu navigation isn't applied:

![Untitled-1](https://user-images.githubusercontent.com/6616923/83478265-66b3d300-a463-11ea-93d3-6abd35a63abd.png)

Also I noticed in your preview here, you have "Show 1 New Tweet":

![68747470733a2f2f692e696d6775722e636f6d2f67786738435545722e706e67](https://user-images.githubusercontent.com/6616923/83478325-9367ea80-a463-11ea-903c-3ee29e290df9.png)

How do I activate that display on my end? Is that part of the experimental "Disable Auto Refresh" feature? (If so I guess it's just not working for me.)

Finally, a request: Can we remove the number of notifications from the title and instead have it show the number of new tweets for whatever page we're on?

![Untitled-2](https://user-images.githubusercontent.com/6616923/83478422-c9a56a00-a463-11ea-8444-65550989d5f5.png)

For example, if I'm on a list and it says "See 7 new tweets," the title bar would say "(7)"

Thanks!

**Comment by Bl4Cc4t** [comment]
> I noticed that outside of the home page, the padding in the drop-down menu navigation isn't applied:

Not sure why that is, please try it again with v`0.0.16`, maybe I already fixed that?

> How do I activate that display on my end? Is that part of the experimental "Disable Auto Refresh" feature? (If so I guess it's just not working for me.)

Yeah, pretty much. It is a bit more complicated to achieve this feature in comparison to changing some styles on the site, sadly...

> Finally, a request: Can we remove the number of notifications from the title and instead have it show the number of new tweets for whatever page we're on?

This has already been requested here: https://github.com/Bl4Cc4t/GoodTwitter2/issues/14
I added the feature, see the issue for details.
Although I did use square brackets to differentiate between notifications.
