### ISSUE TITLE
Low quality profile picture legacy twitter

### ISSUE THREAD

**Issue by NeucomRa** [Bl4Cc4t/GoodTwitter2#371]
I can't upload a good quality profile picture no matter what i try, it seems to be stuck this way and I have to refresh manually because the changing is really slow (I even have to press f5 a few times), happened to one new account I had once and I couldn't fix it so i made a new account (it's been two months without this issues) then it suddenly started to happen again.
![image](https://user-images.githubusercontent.com/94105626/141269535-ec9bf75b-f23e-4b63-9dba-f022244b8051.png)
Example of low quality:
![image](https://user-images.githubusercontent.com/94105626/141269728-2778715a-1827-4092-9c66-6b03ce0b8398.png)

For some reason the quality looks fine in the normal twitter (even if it shows the blurry one with GoodTwitter2), I don't exactly know what this is but, apparently the URL of all the blurry pictures with GoodTwitter2 are named the same:
![image](https://user-images.githubusercontent.com/94105626/141269175-aa8a2b87-77ee-415b-b5de-8ab2cfcc01d3.png)
![image](https://user-images.githubusercontent.com/94105626/141269915-65a09c89-7ff4-4e5e-a1f5-effb7954a878.png)

This is the URL that I can get from my twitter profile without GoodTwitter2 (much better)
![image](https://user-images.githubusercontent.com/94105626/141270051-e57b4fce-293b-4180-9521-dba72da1c828.png)

I don't know what kind of glitch is this but it might have happen during canceling the uploading too soon or something like that? Like it glitched forever now and I really can't fix it, I reinstalled and deleted all cookies a few times, but the glitch persist, not sure if it happens only on the legacy twitter layout but seems like it's displaying the wrong size, please help.
Forgive me for my bad and unformal english, It's not my native language.

**Comment by NeucomRa** [comment]
I figured a strange way to fix it? Now I see what caused the problem, I needed to delete the website displayed on my profile (when you are editing it), it wasn't the website and the way I typed it, basically any info written on there bugs the profile picture, it goes to normal (high quality) as soon as I left the space empty... what? . It should still be fixed tho, I can't have a website on profile anymore, it is weird because I've had one in other accounts !!!

**Comment by Bl4Cc4t** [comment]
the `reasonably_small` part of the picture is causing these problems you have. I didn't even knew that such a size existed up until now...
it should be fixed for the next update which I'll release later today/maybe tomorrow
