### ISSUE TITLE
doesn't work on safari with userscripts

### ISSUE THREAD

**Issue by peepee** [Bl4Cc4t/GoodTwitter2#372]
**Please check the following before you continue**
- [X] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [X] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
the script entirely doesn't work on safari using userscripts

**Screenshots**
![image](https://user-images.githubusercontent.com/49787675/141601791-cbeb6066-0ae0-45e9-89b5-6e4e4bf481a2.png)

**Your configuration**
 - Browser: safari 15.1
 - Userscript Manager: userscripts 3.3.1

**Comment by Bl4Cc4t** [comment]
The user script manager you are using does not work for me at all.
Also, from what I have read it does not support the GM_* functions. These are a vital part of almost all (larger) userscripts (including this one), rendering this extension very useless.
I saw that Tampermonkey has safari extension as well, you might want to try that out. It didn't work for me either but maybe you have more luck.

When it comes to Safari, browser extensions are very restricted and weird. 
I suggest you change your browser to Firefox or something else if you want a bit more freedom on how you want the sites you visit to look.

**Comment by peepee** [comment]
tampermonkey for safari costs money, so i was hoping that userscripts would work as it's free. I'd rather pay for tampermonkey than switch to firefox of all things, though. thanks for your help

**Comment by Bl4Cc4t** [comment]
Tampermonkey is free. Just download it from the [official website](https://www.tampermonkey.net/?ext=dhdg&browser=safari)

You can switch to any other browser you want basically. Safari will always be like this, there is nothing we can do about Apple restricting it sadly.

**Comment by peepee** [comment]
it's not free. for safari 12 and higher, you must buy it. i'm using safari 15

**Comment by Bl4Cc4t** [comment]
ah well, I didn't saw that sorry.
