### ISSUE TITLE
profile highlight colors

### ISSUE THREAD

**Issue by rekvui** [Bl4Cc4t/GoodTwitter2#375]
- [x] Checked if the feature has not been requested before

I think the highlight colors could when in proflie view could match the profile's main color (as in 2nd picture)
example:
![Screenshot_11](https://user-images.githubusercontent.com/93687310/143481387-614a3a90-f560-4694-b44c-6dc58d875fc4.png)
![Screenshot_12](https://user-images.githubusercontent.com/93687310/143481397-add5df07-24ee-4868-9197-27d9148ba272.png)

**Comment by Bl4Cc4t** [comment]
these custom profile colors were a feature of the old design. it is not possible to get them anymore sadly, so I can't do anything about it. sorry.
