### ISSUE TITLE
"One tab away" feature I don't want

### ISSUE THREAD

**Issue by Hatobird01** [Bl4Cc4t/GoodTwitter2#376]
![tab](https://user-images.githubusercontent.com/95081486/143573986-e97f4ec2-9451-46cd-b1ce-a7c6d60c9f73.PNG)
![tab](https://user-images.githubusercontent.com/95081486/143574024-ab3b9760-4dd6-4a9e-8827-4572642ece41.PNG)

Twitter has forced the display of the "Home" tab even in the "Latest Tweets" state.
Want you to remove the tab.

**Comment by Bl4Cc4t** [comment]
I do not have that feature on my end yet, can't fix it until I have it. sorry.

**Comment by Hatobird01** [comment]
My other account doesn't have this tab, so it might be an a / b test. Thank you for your reaction.

**Comment by Bl4Cc4t** [comment]
alright, let's hope it goes away by itself then

**Comment by Bl4Cc4t** [comment]
fixed in 90abe521b65ca64ece7934db69d895002b1fa039
