### ISSUE TITLE
Hide the "Promote" button

### ISSUE THREAD

**Issue by arturo182** [Bl4Cc4t/GoodTwitter2#377]
Just today Twitter started showing a "Promote" button under all my tweets and it's quite annoying, would love if it was possible to hide it:

![image](https://user-images.githubusercontent.com/249082/144457087-e8498842-b9b4-4c9b-b379-a2500f1f29b2.png)

Here's the Inspector view of it:
![image](https://user-images.githubusercontent.com/249082/144457755-d8955451-7390-44df-bfa4-f0d6e39c4da3.png)

**Comment by Bl4Cc4t** [comment]
hm, I do not have that just yet, these country/user restricted rollouts are getting worse and worse. At least this was an easy one to implement.

**Comment by arturo182** [comment]
Thank you :)
