### ISSUE TITLE
Broken square avatars, again

### ISSUE THREAD

**Issue by nanopulga** [Bl4Cc4t/GoodTwitter2#379]
![image](https://user-images.githubusercontent.com/28354083/145406748-1e2cad21-234a-4bf0-8c57-7f10887213d1.png)
Twitter broke square avatars once again. On the latest version for stable and I didn't see the bug report with the new version.

Wish they stopped changing their site to keep the square pfps, which always look way better.

Thank you as always for this extensios, I love it and been using it ever since the old design was completely removed.

**Comment by TheFlippedSides** [comment]
From what I can tell, it looks like Twitter introduced a new convoluted masking method. Hope this helps towards a solution.
![Untitled](https://user-images.githubusercontent.com/90468556/145413267-04688ae2-6181-4586-8c65-74c47df21881.png)

**Comment by Bl4Cc4t** [comment]
> ![image](https://user-images.githubusercontent.com/28354083/145406748-1e2cad21-234a-4bf0-8c57-7f10887213d1.png) 
> Twitter broke square avatars once again. On the latest version for stable and I didn't see the bug report with the new version.
> Wish they stopped changing their site to keep the square pfps, which always look way better.

this is the 3rd time they have changed something that broke the square avatars now in 2-3 months, damn it's getting annoying...

> Thank you as always for this extensios, I love it and been using it ever since the old design was completely removed.

Thank you for your nice words.


> From what I can tell, it looks like Twitter introduced a new convoluted masking method. That clip-path is applied several times throughout the avatar's division. Hope this helps towards a solution. ![Untitled](https://user-images.githubusercontent.com/90468556/145413267-04688ae2-6181-4586-8c65-74c47df21881.png)

Interesting, I have never seen something like this before.
At least this method seems to be easier to edit than having this mess here...
https://github.com/Bl4Cc4t/GoodTwitter2/blob/fde4db3782754250ef8c73c0f75a68a2a2ad64cd/twitter.gt2eb.style.scss#L1196-L1254

new version:
https://github.com/Bl4Cc4t/GoodTwitter2/blob/f4448705f2ea801cf6008dfcc360e411981444d9/twitter.gt2eb.user.js#L2199-L2202
