### ISSUE TITLE
"Disable Auto Refresh" combines badly with disabled cache: image endlessly requested

### ISSUE THREAD

**Issue by phlummox** [Bl4Cc4t/GoodTwitter2#38]
Version of GoodTwitter2: 0.0.14  
Browser: Google Chrome on amd64 Linux  
Version: 83.0.4103.61-1   

I found that if "Disable Auto Refresh" is left enabled (the default), and you happen to have the browser cache disabled (e.g. due to having Developer Tools open), then images get repeatedly requested -- my browser kept requesting (what I believe was) the topmost jpeg and downloaded about 80MB in a few seconds.

To avoid this, perhaps it's better to make Disable Auto Refresh disabled, by default?

Other than that, no major issues - many thanks for the script :)

**Edited to add:**

Correction: The problem still seems to occur - I had to disable "Bigger Image Previews" as well, to fix it.

**Comment by Bl4Cc4t** [comment]
I can’t seem to reproduce this behaviour.
Please try again with v`0.0.17`

**Comment by phlummox** [comment]
I've just updated to `0.0.18` and it seems to be fixed. Cheers :)

**Comment by Bl4Cc4t** [comment]
That’s always good :)
