### ISSUE TITLE
Out of nowhere smaller profile pictures

### ISSUE THREAD

**Issue by rekvui** [Bl4Cc4t/GoodTwitter2#380]
There is a smaller profile picture in the profiles' navigation bar
![image](https://user-images.githubusercontent.com/93687310/145417260-ffecfcf4-86f0-43fa-987e-acfc37b5df35.png)

**Comment by rekvui** [comment]
I saw the "fixed in dev branch" tag and searched for new versions in violentmonkey, but the issue is still appearing to me
![image](https://user-images.githubusercontent.com/93687310/145586905-61771142-fa31-4d91-8838-2031dc484eae.png)

**Comment by Trit34** [comment]
> I saw the "fixed in dev branch" tag and searched for new versions in violentmonkey, but the issue is still appearing to me Replace the file with the fixed version (in TamperMonkey, it proposed me to reinstall the file after I asked for the raw version), and reload the tab.

But there is another problem: the little avatar is gone… and the “Edit profile” button too!

![Capture d’écran_2021-12-10_17-27-01](https://user-images.githubusercontent.com/90716575/145607868-5b0bf2ba-2fde-4030-8732-f8eea6b5be6e.png)

**Comment by rekvui** [comment]
Weird... neither of the 2 has gone for me and both of them are gone for you

**Comment by rekvui** [comment]
> Replace the file with the fixed version (in TamperMonkey, it proposed me to reinstall the file after I asked for the raw version), and reload the tab.
how do you do this?

**Comment by Bl4Cc4t** [comment]
I have not yet released a new version that includes this fix. For now it's only in the `dev` branch since I don't want to release unfinished stuff (or at least try to do so).
I'll probably release an update later today or maybe tomorrow.

Please only use the dev version if you know what you're doing, updates to the script may be broken if you modify the files yourself.
Other than that, thanks for noticing the other button disappearing!

**Comment by Trit34** [comment]
> Please only use the dev version if you know what you're doing, **updates to the script may be broken if you modify the files yourself**. Other than that, thanks for noticing the other button disappearing!

Thanks for the quick fix! Well, that’s the risk when we want test things too quickly… ^^
