### ISSUE TITLE
square icons not working, again.

### ISSUE THREAD

**Issue by rekvui** [Bl4Cc4t/GoodTwitter2#383]
- [x] Bug happens with the newest version of GT2
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the function is activated
The square icons are not working, only in the full profile view and in the small profile view on the timeline. I even deleted and reinstalled gt2 to make sure I hadn't modified anything. I don't know why this feature breaks so easily
![image](https://user-images.githubusercontent.com/93687310/146044913-bbfb0a6a-95ce-4bf1-829d-daa0cf579459.png)
![image](https://user-images.githubusercontent.com/93687310/146045259-0fb82a8c-9671-4211-b40a-b2c772917e73.png)
**Configuration**
 - Google Chrome v 96.0.4664.110
 - Violentmonkey v2.13.0

**Comment by Bl4Cc4t** [comment]
this is getting ridiculous

**Comment by rekvui** [comment]
> this is getting ridiculous

i completely agree.

**Comment by Trit34** [comment]
> > this is getting ridiculous
> 
> i definetively agree.

Me too: why does it seem that they absolutely want us to go with circled avatars, at the point they do everything they can to break whatever hack that could restore squared avatars??? They just can’t leave us alone, can they? Is it so important for them to force circled avatars by all means?!

**Comment by Bl4Cc4t** [comment]
I'm not sure if this is sarcasm, but these changes have nothing to do with this project.

They are just trying out other techniques with CSS and change the DOM in the process. Both of these things break the custom styling this script does unfortunately...

**Comment by Bl4Cc4t** [comment]
sorry for taking so long.
