### ISSUE TITLE
Adding watermarks with updates

### ISSUE THREAD

**Issue by Hatobird01** [Bl4Cc4t/GoodTwitter2#386]
Around the 14th, the watermark started to appear in the search window.
![wat](https://user-images.githubusercontent.com/95081486/146152507-303071cc-e4e7-4f48-a40c-2dfc85244c43.PNG)

**Comment by Bl4Cc4t** [comment]
can you specify what you mean with "watermark"? I don't understand what your issue is.

**Comment by Hatobird01** [comment]
The problem is that when the image comes behind the tab, you can see through it in a hazy way.
Before, it was not visible through.
I am using a translation machine, so I apologize for not conveying my intent.

**Comment by Bl4Cc4t** [comment]
Ah, thanks for explaining, now I got it.
