### ISSUE TITLE
Username field is overlapping profile tweet / following / follower statistics

### ISSUE THREAD

**Issue by nanakisan** [Bl4Cc4t/GoodTwitter2#39]
![image](https://user-images.githubusercontent.com/2136875/83494722-8cdd7100-a46b-11ea-9db8-ae7babac53af.png)

**Comment by Bl4Cc4t** [comment]
fixed in https://github.com/Bl4Cc4t/GoodTwitter2/commit/e88740f6018e390b0b862d2759b1c093a54052c9
