### ISSUE TITLE
Remove hexagon PFPs

### ISSUE THREAD

**Issue by aubymori** [Bl4Cc4t/GoodTwitter2#391]
**Please check the following before you continue**
- [*] Checked if the feature has not been requested before

**Describe the feature**
Revert the hexagon profile pictures back to circles.

**Comment by sks316** [comment]
I say we shouldn't, the hexagon profile pics make it easier to know who to block

**Comment by Luckkz** [comment]
Its useful but it breakes the legacy profile viewer and doesn't really fit in well with the vibe of GT2

**Comment by sks316** [comment]
I say we should have it be an option personally, just like with the square avatars

**Comment by Bl4Cc4t** [comment]
I'll add an option for the next update to disable them, I hope I'll get it done today or tomorrow
