### ISSUE TITLE
Update Message not going away

### ISSUE THREAD

**Issue by Luckkz** [Bl4Cc4t/GoodTwitter2#393]
The Updated to message will not go away 
It will go away when i click the X button but when I switch to a tweet, notifications, etc (Not Direct Messages). it comes back
![image](https://user-images.githubusercontent.com/60667751/150658387-99efde24-3117-4899-bbe0-8bf463bfd8a2.png)
I'm using Firefox Nightly 98.0a TamperMonkey v4.13.6136

**Comment by Luckkz** [comment]
It has appered that the issue has fixed itself I'll leave it open though

**Comment by Bl4Cc4t** [comment]
hm, I never had that happen before. I'll close this since it's fixed, if it happens again feel free to reopen/open a new issue.
