### ISSUE TITLE
Right Sidebar gets forced to the left side 

### ISSUE THREAD

**Issue by DarkTzitzimine** [Bl4Cc4t/GoodTwitter2#395]
- [ ] Bug happens with the newest version of GT2
- [ ] Checked [FAQ]
- [ ] Checked if the issue has not been reported before

I logged today to my Twitter and the right sidebar gets forced to the left side, and the tendencies sidebar is nowhere to be seen.

![image](https://user-images.githubusercontent.com/44504981/151423718-744d02d2-240d-4671-9bf6-5ba1e08db084.png)
![image](https://user-images.githubusercontent.com/44504981/151423771-518dc04c-8ab5-49ee-adca-19830f4c8ee7.png)

These are my setting for GoodTwitter
![image](https://user-images.githubusercontent.com/44504981/151423879-a16184db-ae63-4651-88bc-69dc024c5b32.png)
![image](https://user-images.githubusercontent.com/44504981/151423962-b3ce4996-0b22-4eb5-91d6-885b587265b7.png)
![image](https://user-images.githubusercontent.com/44504981/151423996-1172cf86-c66b-4d24-aa53-7b2f6ae73bc4.png)

**Your configuration**
 - Chrome Versión 97.0.4692.99 (Build oficial) (64 bits)
 - Tampermonkey v4.13

**Comment by Bl4Cc4t** [comment]
fixed in 43cbe1f0f670bcb2aa074d7f27074601b4f15459

**Comment by DarkTzitzimine** [comment]
Thank you so much!

**Comment by Bl4Cc4t** [comment]
No problem, I fixed this before you opened you issue :D
