### ISSUE TITLE
Feature Request: Removing new content warning prompts

### ISSUE THREAD

**Issue by MistressAshai** [Bl4Cc4t/GoodTwitter2#398]
Right now, even with the display sensitive media option checked in Twitter's settings, users will still have to click the content warning on posts right now. I've managed to remove it for now with a combination of stylish and ublock origin but figured it might be wanted in this as well.

For removing the content warning div
```
.css-1dbjc4n.r-drfeu3.r-1867qdf.r-1p0dtai.r-eqz5dr.r-16y2uox.r-1777fci.r-1d2f490.r-ymttw5.r-1f1sjgu.r-u8s1d.r-zchlnj.r-ipm5af {
    display: none !important;
}
```

Afterwards, the image blur will still be enabled, so you'll need to do something about the blur class that gets applied. In stylish, I did something like
```
.r-yfv4eo {
    filter: blur(0px) !important;
}
```

**Comment by Bl4Cc4t** [comment]
This was already added with the latest update yesterday :)
