### ISSUE TITLE
January Changelog dates aren't using the year 2022

### ISSUE THREAD

**Issue by Kosouda** [Bl4Cc4t/GoodTwitter2#402]
Just what the title says, in the changelog here: https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md
I think it's merely a simple accident that you're still using 2021 for the last few updates when it should be 2022.  I know this is such a very minor thing, so I'm sorry for bothering, but eh, maybe someone one day in the future will be looking at it and get confused?

Edit: Oh.  I just looked at Pull requests out of curiosity and saw someone address this very thing.  Nevermind then!

**Comment by Bl4Cc4t** [comment]
thanks for noticing :)
I feel so dumb lol
