### ISSUE TITLE
Profile picture shape bug

### ISSUE THREAD

**Issue by Dragonick-T-Hedgewing** [Bl4Cc4t/GoodTwitter2#403]
**Please check the following before you continue**
- [√] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [√] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [√] Checked if the issue has not been reported before

**Describe the bug**
When you click on an account's profile picture to enlarge it, even when the "square icons" setting is on, the picture appears as a circle.

**Screenshots**
![Image](https://user-images.githubusercontent.com/98646446/151660666-b62ec515-3aaf-4c69-9437-5fa00cecb49f.png)

**Your configuration**
 - Chrome 97
 - Tampermonkey v4.13

**Comment by Bl4Cc4t** [comment]
good catch!

**Comment by Dragonick-T-Hedgewing** [comment]
> good catch!


Thanks!
I also noticed a similar issue with messages in DMs. The circumstances are the same, so I'm entirely sure if I should make a new issue for it.
![image2](https://user-images.githubusercontent.com/98646446/151675922-1862de77-71f6-4f76-8e20-19668cba673e.png)
