### ISSUE TITLE
Option to remove the weird junk in the clipboard when pressing "Copy link to tweet"

### ISSUE THREAD

**Issue by sukerokushin** [Bl4Cc4t/GoodTwitter2#405]
self explanatory, add some sort of check box maybe to remove the weird (tracking?) alphanumerical string garbage after tweets when i copy them w the copy dialogue. if it is tracking, twitter does enough of it by itself, dont think any of us need any more of it lmao

example: ?s=20&t=mv6LafZ7A_TIMfk3POxHJQ (the ?s=20 bit is old and i dont really mind if you cant take that away but the long and ugly alphanumeric string is very annoying me lol)

**Comment by Bl4Cc4t** [comment]
Hm, I always copy a link to a tweet by right clicking on the date and then "copy link", so I never get that stuff.
It looks like it is some kind of tracking for the current session? not sure though. 

see [luca/1432780065109155855](https://twitter.com/luca/status/1432780065109155855)

---

I'll try to come up with something, I don't think this needs a toggle though.

**Comment by sukerokushin** [comment]
yeah it doesnt appear if you open a tweet and copy the link from the address bar, but only through the copy link to tweet dialog. thanks for the insight

**Comment by Bl4Cc4t** [comment]
I tried experimenting a bit, but I couldn't find a usable solution for this.
For obvious security reasons I have no access to the clipboard, so I have to get the current tweet myself which is screaming for lots of errors... I don't think it's that big of a deal if I leave it like this, but I will leave this issue open for the future.

For now, just right click on the date of a tweet and click on copy, it's also two clicks :)
You will probably use that on other pages as well, so it's not that hard to get into.

**Comment by Bl4Cc4t** [comment]
I found a solution, it was way easier once I debugged the site a bit more. Sorry that I didn't find that sooner :V

**Comment by sukerokushin** [comment]
thanks a ton!

**Comment by BrandtnerKPW** [comment]
I like this improvement and would like to suggest removing "?s=20" as well.
`.replace(/\?s=.*$/, "")`

**Comment by Bl4Cc4t** [comment]
> thanks a ton!

no problem!

> I like this improvement and would like to suggest removing "?s=20" as well. `.replace(/\?s=.*$/, "")`

I'm not opposed to this, but the links have had that part for a long time now...
Not sure if it's worth adding a yet another toggle for this. I'll have to think about it :)
