### ISSUE TITLE
Show the amount of new tweets in the page title

### ISSUE THREAD

**Issue by 8SomaCruzes** [Bl4Cc4t/GoodTwitter2#41]
Rather simple request, but a very important one for someone like me.
It's important, since without it, there's basically no point to keeping multiple twitter tabs open, since they don't give any indication when there is new tweets.

**Comment by Bl4Cc4t** [comment]
This has been requested before: https://github.com/Bl4Cc4t/GoodTwitter2/issues/14

**Comment by 8SomaCruzes** [comment]
> 
> 
> This has been requested before: #14

Does it work for twitter profiles too?

**Comment by Bl4Cc4t** [comment]
it should only work on `/home` for now.
