### ISSUE TITLE
Layout breaks when viewing specfic account

### ISSUE THREAD

**Issue by thatsprettygood** [Bl4Cc4t/GoodTwitter2#414]
**Please check the following before you continue**
- [x] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
What sites does it affect?
When using the legacy profile settings, the color get messed up on this specific profile.
https://twitter.com/massivetitty

**Screenshots**
For display issues, adding screenshots or even videos of your screen is recommended.
Normal account:
![image](https://user-images.githubusercontent.com/36249601/155070113-4e819adb-c920-4060-9c8d-fabd4844bd5e.png)
Linked account:
![image](https://user-images.githubusercontent.com/36249601/155070170-4b8d766e-1a2f-49d1-9e7d-818e6272caea.png)

**Your configuration**
 - Browser (e.g. Chrome 83)
 Firefox 97
 - Userscript Manager (e.g. Tampermonkey v4.10)
 Tampermoney Latest

**Comment by Bl4Cc4t** [comment]
with a username this long, the part that was supposed to be out of view was visible. thanks for reporting!
