### ISSUE TITLE
Weird empty gap when scrolling down profiles

### ISSUE THREAD

**Issue by rekvui** [Bl4Cc4t/GoodTwitter2#418]
**Please check the following before you continue**
- [x] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

When you scroll down profiles a bit, an empty gap appears between the first tweet and profile's informations

![image](https://user-images.githubusercontent.com/93687310/157731864-52595763-5c25-4168-885c-e44443ea9441.png)
![image](https://user-images.githubusercontent.com/93687310/157731893-ea00ee12-ac32-454b-97a5-1d9ac6e88982.png)

**Comment by Bl4Cc4t** [comment]
this should only be visible when you resize your window. is that correct?

**Comment by rekvui** [comment]
actually, I think you can close this issue, it's not frequent enough to actually bother me

**Comment by Bl4Cc4t** [comment]
okay then
