### ISSUE TITLE
Site unusable without being logged in

### ISSUE THREAD

**Issue by anonmon** [Bl4Cc4t/GoodTwitter2#42]
I hate to just make such a declaratory statement, but that's the best way to put it.
-It doesn't work/do anything on all pages, namely when you're on someone's main twitter page it does nothing.
-And when it does work, it looks like this.
![image](https://user-images.githubusercontent.com/66309432/83513764-48cd8900-a4ca-11ea-8fe0-a83b88ef5212.png)
-Looks like this before and after disabling the security.csp
Using Waterfox 2020.04 Classic (Portable) if that helps.

[Edit]
Tested with a fresh version of Waterfox 2020.05 Classic (Portable) and getting the exact same results.

**Comment by Bl4Cc4t** [comment]
This issue is not related to your browser.

When you are not logged in, it looks like this on every browser.

I did not take into account that some people use the site without being logged in, I need to change some things for that matter

**Comment by anonmon** [comment]
I see, as much as Twitter would like to datamine everybody profiled with user data tagged to user accounts, not all of us play to their game.
As an aside, don't know how feasible this would be, but it used to be you could type in "/media" into the URL without a forced login in order to get to the media tab. Would that functionality be possible with this extension? Even if there's no way to get access to the 'real' media tab, just being able to display all posts and replies by the owner of a profile only would make my, and I'm sure many people's, lives way easier for going through artist profiles and the like.

**Comment by Bl4Cc4t** [comment]
> Would that functionality be possible with this extension?

this would require some heavy reverse engineering of their uglified javascript and I doubt that I have the knowledge to do that.

> Even if there's no way to get access to the 'real' media tab, just being able to display all posts and replies by the owner of a profile

Isn’t it already possible? I only get the popup on `/media` and `/likes`.

**Comment by anonmon** [comment]
You can view the entire twitter feed of a single person just fine, but the media tab filters out every single post that doesn't have any media in it, and all retweets that otherwise have absolutely nothing to do with the user in question. Extremely useful when you want to find some specific photo from a specific user without having to shift through a ton of posts that aren't even from the user you're looking for, or literally just text bloating out the results. Or for artists who won't post elsewhere when you just want to view their stuff.

**Comment by Bl4Cc4t** [comment]
hm, a custom filter may be possible to do.
Please note that I probably will do other things before I look into that, sorry

**Comment by anonmon** [comment]
Of course, need to get the baseline working before extra features can be added.
Not needing an extra add-on or extension for making all hidden content show without having to click through "show" for every single one would be a boon for usability too for example, but things do need to be largely functional and stable long before that.

**Comment by Bl4Cc4t** [comment]
You can even switch to the dim mode when you click on the little moon at your profile!
