### ISSUE TITLE
usernames are missing in LPL

### ISSUE THREAD

**Issue by rekvui** [Bl4Cc4t/GoodTwitter2#420]
**Please check the following before you continue**
- [x] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

![image](https://user-images.githubusercontent.com/93687310/158486654-f1eb7cff-fdf8-459a-892d-50b027fc750d.png)

**Comment by ktg5** [comment]
this also breaks the correct tweets, followers, and following amounts.

**Comment by Bl4Cc4t** [comment]
just saw that too, gotta fix this fast. thanks for reporting in
