### ISSUE TITLE
Navbar tweet button sometimes blank

### ISSUE THREAD

**Issue by Bl4Cc4t** [Bl4Cc4t/GoodTwitter2#43]
![image](https://user-images.githubusercontent.com/6740726/83514589-31939900-a4d4-11ea-9fac-9279f0bb7314.png)

possible fix: creating own button, translations would be needed.

**Comment by arturo182** [comment]
Resizing the window until the button shows the quill icon and then resizing back fixes the issue.

**Comment by Bl4Cc4t** [comment]
It does, but we need a permanent fix :D
I cannot control this behaviour, since the text is removed from the dom.

**Comment by Bl4Cc4t** [comment]
fixed in https://github.com/Bl4Cc4t/GoodTwitter2/commit/5d80ba22dd178aa5ae815e1270ea81a112e582b0
