### ISSUE TITLE
Option to bring back sidebar media via profile

### ISSUE THREAD

**Issue by m3k1e** [Bl4Cc4t/GoodTwitter2#433]
Hey, I was scrolling through Twitter for a while just to check the profile until I noticed that sidebar media is silently removed. Due to this, this will affect artists and your tweak option, rendering "Left sidebar media" useless. Could you please readd the sidebar media? That feature was useful for artists and memes who want their audience to show their good stuff.

Here's what it looks like. Note that I removed the "Others you follow" and trending sidebar for obvious reasons.

Edit: Media preview sidebar is back. You may now close the issue as it is resolved.

![chrome_zAX3bXQV6u](https://user-images.githubusercontent.com/41316133/163914426-ef9f6bbb-cf6e-457f-87ad-19cf0c115139.png)

**Comment by Bl4Cc4t** [comment]
Good thing that most people disliked that change and they actually listened for once :D
