### ISSUE TITLE
Some ideas.

### ISSUE THREAD

**Issue by aubymori** [Bl4Cc4t/GoodTwitter2#434]
So, me and some friends have been recreating the old YouTube layout over at [Rehike/Rehike](https://github.com/Rehike/Rehike). Perhaps you could do something similar with Twitter? Basically, what I'm saying is, grab Twitter data from the API with PHP curl (NOT the public API, the one the site uses) and use that to rebuild the old site's HTML wth Twig. Now, there's only two issues I've noticed so far.

1. You cannot get profile-specific colors without requesting the actual old layout (which may go down in the future).
2. You cannot request worldwide trends without requesting the actual old layout's AJAX endpoint (which, again, will probably go down in the future).

Other than that, you're fine. You can request the old layout with the user agent `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36` logged out. Moments don't work but I'm sure you can either pump Explore data into it or cut it entirely.
If you want to learn the Twitter API (which I haven't bothered with personally), just fiddle around with the network tab until ya get it. If you have any questions or concerns or blahblahblah you can PM me on Discord at `aubrey#1523`.

**Comment by Bl4Cc4t** [comment]
This is **way** out of scope of this project. Like stated on the front page, this is not a recreation, it's a hybrid layout. There is a reason for this. I have no time for recreating an entire website from scratch when I already made this project to enhance the site, sorry.

If you want to do this, feel free to use parts of this project (only crediting me/this project would be nice if you do so).
Also, the script already utilizes the public api to some extend.

**Comment by aubymori** [comment]
ugh whatever im too fucking lazy to do anything anyways
