### ISSUE TITLE
Give an option to force the three-columns layout

### ISSUE THREAD

**Issue by elmagio** [Bl4Cc4t/GoodTwitter2#44]
Currently at my default zoom level, I only have the timeline (on the left) and the right sidebar, instead of the "legacy" layout with sidebars on each side of the timeline. If I zoom out, I get the three columns, but then the timeline feels cramped (I can adjust the text size but the timeline stays the same width).

It's probably an issue that with the default sidebar size I don't have enough room for the three columns (I have a 1920/1200 screen, and my default zoom level in Chrome is at 150%, so two 350px sidebar + 600px timeline at that zoom level doesn't fit), but with the small sidebars there's definitely room but it still goes to a two-columns layout unless I unzoom to 125%. 

Having the timeline on the left and only one sidebar isn't very "legacy twitter" so it would be great if there was an option to force the three-columns layout.

**Comment by Bl4Cc4t** [comment]
150% zoom? That’s pretty big.
Please send a screenshot, that makes things easier.

3 sidebars appear at 1350px screen width.
I will not change the width of the main column, but I can increase the tolerance when using the small columns (which actually makes sense).

1230px should be the minimum for 3 columns and the small sidebar setting enabled.
What dod you think?

**Comment by elmagio** [comment]
I find that at my resolution and screen size (13.4 inches, so that's 169PPI) 150% zoom for web pages is the sweet spot, but that's just me. Sorry for not the absence of screenshots, I thought about including some but I wasn't sure what to screenshot.

1230px would take into account the reduction in sidebar sizes so that does seem right to me. Also it would fix the issue in my particular case (1230 x 1.5 = 1845 so it would fit). It's possible that some people have a different use case though (can't think of one on the spot) so maybe it should a secondary toggle instead of the smaller siderbars settings automatically lowering the threshold?

**Comment by Bl4Cc4t** [comment]
> It's possible that some people have a different use case though (can't think of one on the spot) so maybe it should a secondary toggle instead of the smaller siderbars settings automatically lowering the threshold?

I am not really sure what you want to toggle though :/

**Comment by elmagio** [comment]
Thanks for the (very) quick fix, it seems to have introduced two smaller issues though:

- While there are now three columns at my zoom level if I use the small sidebars, the setting for "Left Sidebar Trends" doesn't work and the Trends stays on the right unless I zoom out to 125%.

- The timeline and left sidebar scroll horizontally too.

I've included two screenshots to show how the timeline and left sidebar move around a bit. In both of these the toggle for "Left Sidebar Trends" is also enabled yet the Trends are on the right.

![Capture d’écran de 2020-06-03 10-55-52](https://user-images.githubusercontent.com/14126056/83617319-2cdcec80-a589-11ea-9fe2-2c640b2ed26f.png)
![Capture d’écran de 2020-06-03 10-57-02](https://user-images.githubusercontent.com/14126056/83617329-2fd7dd00-a589-11ea-9c96-b855e44e136f.png)

**Comment by Bl4Cc4t** [comment]
I think this is #63/#75
