### ISSUE TITLE
Video Progress Bar Missing

### ISSUE THREAD

**Issue by Kosouda** [Bl4Cc4t/GoodTwitter2#442]
After the latest update, I noticed that while watching a video on Twitter, the progress bar has gone missing.  I mean the white part of the video player's seek bar showing the progress of the video.  The dot, rest of the seek bar, and everything else still shows and operates completely normally.  No issues there.  I confirmed that the white progress part does show for me if I disable the script, and it also shows in Discord embeds, so it's something to do with the script, not only Twitter itself.
This is in Chrome and using Tampermonkey.

It's not a big deal, but I miss it, and it seems like such a strange issue.

**Comment by Bl4Cc4t** [comment]
as always, I'm replying to this way too late... sorry about that :/

this issue does not happen for me, does this still happen on you end?

**Comment by Kosouda** [comment]
That's fine.  This isn't a big deal, just weird.  Even after the update just today, it is still happening, yes.  I temporarily disabled all other scripts in Tampermonkey just to see, and it was still happening.

Although I think you understand, I realize I should have attached screenshots to show exactly what I mean.  I've attached two cropped print screens here, using just any video I found in the moment, showing what it looks like when mousing over the video and then mousing over the seek bar, albeit you're unable to see my cursor.
![pandavideo](https://user-images.githubusercontent.com/7887151/181994742-41119a68-3c17-4315-a8f7-07defb6fc85b.png)
![pandavideo2](https://user-images.githubusercontent.com/7887151/181994743-a0a526e3-bf9d-4483-ba1d-ccabcc2a3338.png)

**Comment by Bl4Cc4t** [comment]
thanks for replying :)

would've helped if you specified what browser you use when reporting... there is a bug report template for a reason :/

can confirm that this bug happens on chrome, firefox has no issues. will investigate for the next update!

**Comment by Kosouda** [comment]
I did say Chrome and with Tampermonkey in the first post, but I should have put a blank line before that because I have a tendency to be wordy, haha.  But yep, with latest version.  Honestly, I should quit using Chrome, but it's a habit for now.

Thanks for looking into it!

**Comment by Bl4Cc4t** [comment]
Looks like my eyesight did get worse, I didn't see that :/

**Comment by Kosouda** [comment]
Well, it's also true I didn't follow the template due to thinking most of it didn't seriously apply, but I should just stick to it, not just here but for future things.  Anyway, thanks again for looking into it!  No rush for something so minor.
