### ISSUE TITLE
Square avatar images are broken again

### ISSUE THREAD

**Issue by nanopulga** [Bl4Cc4t/GoodTwitter2#443]
**Please check the following before you continue**
- [X] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [X] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [X] Checked if the issue has not been reported before

**Describe the bug**
The avatar images are round once again while seeing tweets and the timeline. Twitter pls stop breaking the the script I love my square avatars.

**Screenshots**
![2022-06-18 01_25_06-Latest Tweets _ Twitter](https://user-images.githubusercontent.com/28354083/174412213-84246d28-a3ae-42f9-bb69-d925b0d20635.png)

**Your configuration**
Google Chrome 102.0.5005.115
Violentmonkeyv2.13.0

**Comment by Trit34** [comment]
You can still use this user-style in Stylus as a workaround (apply to the domain `twitter.com`), it’s still working:

```
.r-sdzlij {
    border-radius: 5px;
}
```

**Comment by nanopulga** [comment]
> You can still use this user-style in Stylus as a workaround (applied to the URLs beginning by: `https://twitter.com`), it’s still working:
> 
> ```
> .r-sdzlij {
>     border-radius: 5px;
> }
> ```

Ooooh I didn't know about this at all, thank you so much!!!
