### ISSUE TITLE
Option: redirect/land user profile clicks to /username/media

### ISSUE THREAD

**Issue by GreenDotBlue99** [Bl4Cc4t/GoodTwitter2#446]
Some of the old extension(s) for old interface had this feature as an option, but since removed from Chrome Extension web store. 

Redirect/land user profile url clicks such as 
https://*.twitter.com/username/ to 
https://*.twitter.com/username/media

*username* meaning any twitter username url

But when clicked from https://*.twitter.com/username/media to such as /username/with_replies or /username/likes etc. then don't redirect. 

Also not to redirect from general twitter menu links such /settings/, /explore/, /bookmarks/ //lists/ etc adding /media to them.

**Comment by Bl4Cc4t** [comment]
Hm, not sure if I understand correctly, but you want to have an option to redirect every profile that gets visited to /username/media? ...why? What's the reasoning? Can't you just click on the media tab to get to that page?

I fail to understand the practical use of this, sorry

**Comment by GreenDotBlue99** [comment]
It's for people who wants to see that the user has posted, media, not the main "tweets" landing page where there is retweets, mentions, likes, comments etc from content that a user hasn't posted.

When people browse Twitter and open many userprofiles in a new tab, it's frustrating to click the media-link when the page could already be there redirected.

It's a good option. The main landing page is much of distraction and time consuming with all it's extra content.

Reddit Enhancement Suite (RES) has similar option, one can choose from its settings what userprofile/subpage to land. 

Chrome Web Store had an extension for old Twitter interface it had a small bunch of features, one was option to redirect to /media/.

**Comment by Bl4Cc4t** [comment]
okay then, I'll try to add that option for the next update then, thanks for the follow up comment.
