### ISSUE TITLE
/intent/follow uses new profile layout when legacy profile is enabled

### ISSUE THREAD

**Issue by aubymori** [Bl4Cc4t/GoodTwitter2#452]
**Please check the following before you continue**
- [*] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [*] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [*] Checked if the issue has not been reported before

**Describe the bug**
When going to `/intent/follow`, the profile uses the new layout, regardless of whether legacy layout is enabled or not.

**Screenshots**
![image](https://user-images.githubusercontent.com/44238627/182711248-7e7f8618-2d11-4b9a-98a6-f35992a666a0.png)

**Your configuration**
 - Browser: Firefox 78.15.0 ESR
 - Userscript Manager: Tampermonkey v4.17.6161

**Comment by Bl4Cc4t** [comment]
good catch!
