### ISSUE TITLE
Twitter refuses to load / Takes over 5 minutes to load

### ISSUE THREAD

**Issue by highesttt** [Bl4Cc4t/GoodTwitter2#456]
**Please check the following before you continue**
- [x] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [X] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [X] Checked if the issue has not been reported before

**Describe the bug**
- Twitter takes a LONG time to load or sometimes outright freezes and doesn't load at all. It started happening yesterday afternoon (CEST Timezone). I have tried both Tampermonkey and Violetmonkey.
I have also tried using only TamperMonkey + the script and no other addons
![image](https://user-images.githubusercontent.com/91629626/184101782-8d69ad8d-3dfa-4104-9780-fa8200490b7b.png)
What sites does it affect?
- Twitter itself.

**Screenshots**
![image](https://user-images.githubusercontent.com/91629626/184102157-86ea923b-4cb6-4b1e-855e-b845b5265907.png)
![image](https://user-images.githubusercontent.com/91629626/184102197-63c92609-12cf-48b3-bfdc-42f1d8527101.png)

**Your configuration**
 - Edge Version 103.0.1264.77 and 104.0.1293.47 on Windows 11 build 22000
 - VioletMonkey v2.13.0 + Tampermonkey 4.16.1

**Comment by Bl4Cc4t** [comment]
related #455

**Comment by Bl4Cc4t** [comment]
closing this in favor of #455
