### ISSUE TITLE
Navigation items on top hard refresh the page now

### ISSUE THREAD

**Issue by aubymori** [Bl4Cc4t/GoodTwitter2#458]
**Please check the following before you continue**
- [*] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [*] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [*] Checked if the issue has not been reported before

**Describe the bug**
In the past, when you clicked the navigation buttons on the top (Home, Notifications, Messages), it would smoothly navigate to them like any other Twitter page. Now, it reloads the entire page to go there as if it was a normal link.

**Your configuration**
 - Browser: Firefox 78.15.0 ESR
 - Userscript Manager: Tampermonkey v4.17.6161

**Comment by Bl4Cc4t** [comment]
related: #455 #459
