### ISSUE TITLE
Notifications on top doesn't show actual count

### ISSUE THREAD

**Issue by aubymori** [Bl4Cc4t/GoodTwitter2#459]
**Please check the following before you continue**
- [*] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [*] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [*] Checked if the issue has not been reported before

**Describe the bug**
The notifications navigation item doesn't show the real count (which in this case is 3).

**Screenshots**
![image](https://user-images.githubusercontent.com/44238627/184511174-98ea1c4d-a0fc-4679-82ba-25903985ba71.png)

**Your configuration**
 - Browser: Firefox 78.15.0 ESR
 - Userscript Manager: Tampermonkey v4.17.6161

**Comment by SleepyCatten** [comment]
I'm getting the exact same issue.

Browser: 103.0.2 (64-bit)
Userscript Manager: Tampermonkey 4.17.6161

**Comment by Bl4Cc4t** [comment]
related: #458 & #455

**Comment by arholt** [comment]
Same issue here for the past 2 days.

**Comment by Hannah-GBS** [comment]
This (and the related issues) started for me today. Twitter rolling out breaking changes I'd assume

**Comment by KreiserVII** [comment]
Same issue here.

**Comment by m3k1e** [comment]
Same issue here.

**Comment by Bl4Cc4t** [comment]
for everyone here having this issue, please check if the following script works for you: [test script](https://gist.github.com/Bl4Cc4t/d5eca35ad0e285c6aa1bff5e61831644/raw/27f1103081b83d33dc1711b382e87ce6c235e421/gt2eb.0.0.40.2-debug.user.js)

I hope this does not create #455 again...

**Comment by liseronberry** [comment]
Hi, I was having the same problem with the notification count not working.
I had the #455 freeze before, and now that I have installed the test script, I have the #455 problem again.
(Sorry, this text is using Deepl translation)

**Comment by arholt** [comment]
> It worked! Thanks so much!

**Comment by Bl4Cc4t** [comment]
> Hi, I was having the same problem with the notification count not working. I had the #455 freeze before, and now that I have installed the test script, I have the #455 problem again. (Sorry, this text is using Deepl translation)

that's not very good... thanks for checking.
gotta come up with something...

**Comment by LaurentChemla** [comment]
> Hi, I was having the same problem with the notification count not working. I had the #455 freeze before, and now that I have installed the test script, I have the #455 problem again. (Sorry, this text is using Deepl translation)

Same thing here :/

**Comment by Bl4Cc4t** [comment]
@liseronberry @LaurentChemla okay, how about this one then? [test script](https://gist.github.com/Bl4Cc4t/b8bbb21831aa615270646fbb55f98c50/raw/ee86087ea628013eb8a2ed0fc5cb6483aa9bdfff/gt2eb.0.0.40.2-debug.user.js)

**Comment by GOOPREALM5000** [comment]
Test script worked perfectly. Thanks.

**Comment by LaurentChemla** [comment]
> @liseronberry @LaurentChemla okay, how about this one then?

Same for me : freeze (maybe a little more).

**Comment by liseronberry** [comment]
> @liseronberry @LaurentChemla okay, how about this one then? 
I also tried this script but it did not solve the freezing problem.
Thanks for trying to fix the problem.

**Comment by liseronberry** [comment]
> @liseronberry @LaurentChemla okay, how about this one then? 

I also tried this script but it did not solve the freezing problem.
Thanks for trying to fix the problem.

**Comment by Bl4Cc4t** [comment]
@liseronberry @LaurentChemla 
I appreciate you two helping me out here :) Tried something different this time, I think it should work now. Please try testing if the notification count also updates. It worked for me, but just to be sure...
[test script](https://gist.github.com/Bl4Cc4t/07eec8691f72de5e1f5c2ac774f81dfa/raw/d130e7f8ee8c9e9fb3d1f13021200394a676a82a/gt2eb.0.0.40.2-debug.user.js)

**Comment by LaurentChemla** [comment]
> @liseronberry @LaurentChemla I appreciate you two helping me out here :) Tried something different this time, I think it should work now. Please try testing it once more. It worked for me, but just to be sure... 

YES ! Excellent work thank you. No more freezing and notifications restored for me.

**Comment by Bl4Cc4t** [comment]
great. I'll release an update then, since this is rather critical :D

**Comment by liseronberry** [comment]
> @liseronberry @LaurentChemla I appreciate you two helping me out here :) Tried something different this time, I think it should work now. Please try testing it once more. It worked for me, but just to be sure... 

After applying the script, the notifications are working fine and no longer freeze.
Thanks for the great job!

**Comment by JesperDramsch** [comment]
Just got the update in the wild. Thanks for the great work!
![image](https://user-images.githubusercontent.com/2620316/187047062-3a39f01a-cf9e-48ff-a58e-56229311c3ae.png)
