### ISSUE TITLE
Bigger Image Preview option not loading some pictures

### ISSUE THREAD

**Issue by Biggiepax** [Bl4Cc4t/GoodTwitter2#461]
It seems when I have the Bigger Image Preview option selected, certain pictures for tweets don't seem to load.
My guess is it might be the resizing twitter does with pictures if they're too big?
It started happening with the new twitter update that made things more square looking.

With Bigger Image Preview on:
![image](https://user-images.githubusercontent.com/54286287/184783802-bc72cc7a-8171-42e5-b4af-bb98ac0a15fb.png)
![image](https://user-images.githubusercontent.com/54286287/184783754-d98872ad-efc7-41d2-a3ce-d60371b56497.png)

With Bigger Image Preview off:
![image](https://user-images.githubusercontent.com/54286287/184783981-86d93688-ce8d-4009-9164-b34ce7085330.png)
![image](https://user-images.githubusercontent.com/54286287/184783989-d2ce0b84-dc6c-4db7-aeda-0876d26ea8be.png)

Using the latest version of GT2 and on Chrome

**Comment by Bl4Cc4t** [comment]
that option is definitely broken, it has been for a while now.
I'll try to look into it!
