### ISSUE TITLE
"Always show media with content warnings" stopped working

### ISSUE THREAD

**Issue by Manimap** [Bl4Cc4t/GoodTwitter2#462]
**Please check the following before you continue**
- [x] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
It seems like even when forcing to hide the content warnings in goodtwitter, it doesn't work anymore. I can confirm it used to work until maybe a few days ago.

**Screenshots**
![image](https://user-images.githubusercontent.com/13313380/185762875-451fc282-b211-48e4-84df-af2b5f3392eb.png)
![image](https://user-images.githubusercontent.com/13313380/185762889-bc1178d4-02a4-44af-850f-121a6df63d29.png)

I used this random old tweet to test it : 
https://twitter.com/JessiSheron/status/1486523506451963909

**Your configuration**
 - Brave Version 1.42.97/Chromium: 104.0.5112.102 and chrome 104.0.5112.102 64bits
 - Violentmonkey v2.13.0

Any help whether I'm the only one having the problem or not would be appreciated.

Thanks
Mani

**Comment by Bl4Cc4t** [comment]
sorry for taking so long to fix this.
I'm currently rewriting the script completely & try to fix some bad bugs with the current version while not having much free time :D

**Comment by Manimap** [comment]
OK that's maybe just me but I still see the content warnings?
For example another one for violence : 
https://twitter.com/pkfirelover69/status/1563036977485623296
![image](https://user-images.githubusercontent.com/13313380/188032597-840503f5-51fd-4fbc-ae97-2e211332b3be.png)

**Comment by Bl4Cc4t** [comment]
...

they changed the DOM (the website structure) right after I released the update.

thanks for notifying!
