### ISSUE TITLE
Full reload when switching from Home to Notifications

### ISSUE THREAD

**Issue by LaurentChemla** [Bl4Cc4t/GoodTwitter2#471]
Since #455 and its fix, I get a full reload of Twitter page when I switch from Home to Notification (and back). Not really a bug but annoying enough to report.

**Comment by Bl4Cc4t** [comment]
Hm, I thought I fixed that issue by fixing #458...
You're on the latest version (v0.0.40.3) right?

If yes, please check if this test script removes the reloading for you: [test script](https://gist.github.com/Bl4Cc4t/cfc1191f9d8056528f29037949720401/raw/90dda297c419519772bebe1c6f8d4556f095ae61/gt2eb.0.0.40.3-dev.user.js)

**Comment by LaurentChemla** [comment]
I wasn't, sorry...

**Comment by Bl4Cc4t** [comment]
okay then, good news :D
