### ISSUE TITLE
The new Twitter layout conflicts with GoodTwitter2

### ISSUE THREAD

**Issue by MistressAshai** [Bl4Cc4t/GoodTwitter2#474]
**Describe the bug**
In the new layout, it causes (presumably) images marked as sensitive to not appear in the feed.

**Screenshots**
![image](https://user-images.githubusercontent.com/8222603/188433643-c67ca604-d28b-4e4a-a131-03abf0422efd.png)

**Your configuration**
 - Chrome v104.0.5112.102 (Official Build) (64-bit)
 - Tampermonkey v4.16.1

**Comment by Bl4Cc4t** [comment]
cannot reproduce this sadly. does this happen with specific settings enabled?
and does this only happen to "recommended" tweets?

**Comment by MistressAshai** [comment]
It happens on a specific account so it's probably A/B testing.
And no, this happens throughout the whole site sadly.

**Comment by dnestico** [comment]
Can definitely confirm this, seems to be happening with every account today. Weird.

<img width="634" alt="Screen Shot 2022-09-23 at 1 15 15 PM" src="https://user-images.githubusercontent.com/3034555/192018320-2d4c703d-a61c-4f78-af65-3c893ec1c137.png">

**Comment by Bl4Cc4t** [comment]
Thanks a lot for reporting back. Was a simple fix!
