### ISSUE TITLE
Some images not loading now

### ISSUE THREAD

**Issue by NeucomRa** [Bl4Cc4t/GoodTwitter2#479]
Started happening right after the Legacy profile layout fix, some images are just a dot in the tl
![image](https://user-images.githubusercontent.com/94105626/192087215-4a1db869-e9d9-4d1e-876e-c82ba66c8018.png)

**Comment by CinderBH** [comment]
Same thing happened to me, I checked and it's the "bigger image previews" option that broke.

**Comment by Bl4Cc4t** [comment]
this should be #461. for now deactivate "biggerImagePreviews", I hope I can come up with a fix
