### ISSUE TITLE
Script does not run in Firefox Nightly 107.0a1

### ISSUE THREAD

**Issue by BrandtnerKPW** [Bl4Cc4t/GoodTwitter2#480]
Script does not run itself in Firefox Nightly 107.0a1 (64-bit).
But if I press Ctrl+F5 it helps to run the script.

**My configuration**
 - Browser: Mozilla Firefox Nightly 107.0a1 (64-bit). Builds in the last 3-4 days. For example 107.0a1 (2022-09-24) (64-bit).
 - Userscript Manager: Tampermonkey v4.17.6161 or Tampermonkey BETA 4.18.6168.
 - GoodTwitter2 from master and dev branches.

**Comment by BrandtnerKPW** [comment]
I installed Violentmonkey and it looks like the script is running as it should. Perhaps this is a Tampermonkey issue.

**Comment by Bl4Cc4t** [comment]
can reproduce.
maybe it is a tampermonkey issue. I can run a simple script like this without problems though:
```
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.mozilla.org/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==

(function() {
  console.log("test")
})();
```

**Comment by BrandtnerKPW** [comment]
The script is working again in Firefox Nightly 108.0a1 (2022-11-05) (64-bit) with Tampermonkey BETA 4.18.6168.
Perhaps it was fixed.

**Comment by Bl4Cc4t** [comment]
Hm, maybe it was a bug they fixed
