### ISSUE TITLE
Menu UI is broken when clicking profile image

### ISSUE THREAD

**Issue by hellojo011** [Bl4Cc4t/GoodTwitter2#484]
**Please check the following before you continue**
- [x] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
The menu UI is displayed inconsistently due to changes in the UI on Twitter.

**Screenshots**
![image](https://user-images.githubusercontent.com/15025232/193192394-5664e88a-3188-4496-a7db-a678c6fd9900.png)

**Your configuration**
 - Browser: Vivaldi Browser 5.4.2753.51 (Stable channel) (x64), (Chromium 104.0.5112.126 based)
 - Userscript Manager: Tampermonkey v4.16.1

**Comment by Bl4Cc4t** [comment]
![image](https://user-images.githubusercontent.com/6740726/193365200-dddcacd7-e20f-45da-8770-a6be15e238d0.png)
how does this look?

**Comment by hellojo011** [comment]
This looks more natural because the style of the text doesn't change suddenly.
