### ISSUE TITLE
Quote tweet images not showing with Bigger Image Previews enabled

### ISSUE THREAD

**Issue by Hannah-GBS** [Bl4Cc4t/GoodTwitter2#485]
**Please check the following before you continue**
- [x] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
Seems to be similar to the recently fixed issue with Bigger Image Previews. Toggling the CSS applied by that config off and back on fixes it until the next refresh, as shown in the video below

**Screenshots**
![](https://i.imgur.com/BQKDGCx.png)

https://user-images.githubusercontent.com/7504779/193417262-8505097f-a533-4409-ab02-bb4b3a890c6f.mp4

**Your configuration**
 - Browser: Firefox 105.0.1 (64-bit)
 - Userscript Manager: Tampermonkey 4.18.0

**Comment by Bl4Cc4t** [comment]
good catch, thanks!
