### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by MattABS** [Bl4Cc4t/GoodTwitter2#49]
On the main twitter page, the Avatar and top-right image can't load. The text is also missing off the tweet button.

Chrome: Version 83.0.4103.61 (Official Build) **(64-bit)**
Using V0.0.17

![Twitter](https://user-images.githubusercontent.com/15888363/83546211-3cf8bb80-a4f8-11ea-898d-746dda9d7d6a.png)

**Comment by Moragor** [comment]
Try ctrl+F5, solved it for me.

**Comment by MattABS** [comment]
> Try ctrl+F5, solved it for me.

First thing I tried, followed by clearing the cache. Neither worked.

**Comment by Bl4Cc4t** [comment]
please [install this older version](https://github.com/Bl4Cc4t/GoodTwitter2/issues/21#issuecomment-636542414) and send the output here: 
you can censor your name, I only need the `avatarUrl` string.

**Comment by MattABS** [comment]
Sure:

userInformation:
{
  "bannerUrl": "",
  "avatarUrl": "https://pbs.twimg.com/profile_images/1492988443/default_profile_5_normal_normal.jpg",
  "screenName": "Myname",
  "name": "Myname",
  "stats": {
    "tweets": "295",
    "followers": "1",
    "following": "96"
  }
}

**Comment by Bl4Cc4t** [comment]
Does this still happen with the latest version? Maybe I fixed it by accident :D

**Comment by MattABS** [comment]
I'm now using v0.0.20 and it's still occurring.

**Comment by Bl4Cc4t** [comment]
What a dumb error, should work with the next update
