### ISSUE TITLE
Verification reason not showing with legacy profile

### ISSUE THREAD

**Issue by thatsprettygood** [Bl4Cc4t/GoodTwitter2#492]
**Please check the following before you continue**
- [X] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [X] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [X] Checked if the issue has not been reported before

**Describe the bug**
The reason for verification when you click on a verified mark does not show with legacy profiles enabled.

**Your configuration**
Firefox (Violentmonkey)

**Comment by Bl4Cc4t** [comment]
(this issue is related to the recent icons update.)

**Comment by Bl4Cc4t** [comment]
ugh, that commit message mentioned the wrong issue actually, as you can see in the title of the commit...
It was meant to say #493 instead.
I'm sorry for the confusion.
