### ISSUE TITLE
"Force Latest Tweets" no longer working

### ISSUE THREAD

**Issue by CinderBH** [Bl4Cc4t/GoodTwitter2#493]
**Please check the following before you continue**
- [X] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [X] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [X] Checked if the issue has not been reported before

**Describe the bug**
"Force Latest Tweets" broke again. Somehow it always happens whenever I have to log out and back in (I usually don't, actually been months since last).

**Your configuration**
 - Browser: Firefox 106.0.5 (64 bit)
 - Userscript Manager: Tampermonkey v4.18.0

**Comment by Bl4Cc4t** [comment]
(this issue is related to the recent icons update.)
