### ISSUE TITLE
Distinguish between two versions of verification badge

### ISSUE THREAD

**Issue by geyerbri** [Bl4Cc4t/GoodTwitter2#494]
**Please check the following before you continue**
- [X] Checked if the feature has not been requested before

**Describe the feature**
The new Twitter Blue subscription adds a verification badge to accounts and can only be distinguished from "notable" verifications by going to the user's profile and clicking directly on the verification badge.

This request is for implementation of a visual distinction between the two 'types' of badges on tweets themselves, negating the need to navigate to an account's page.

Not sure if there's a way to integrate the following GH-hosted Chrome Extension into GoodTwitter2, but I thought I'd pass it along as potentially useful: https://github.com/wseagar/eight-dollars

**Comment by geyerbri** [comment]
Twitter is far too much in flux (and potentially not long for this world) for this enhancement to make any sense. Looks like a recent update has already addressed this idea, with a new badge color for accounts that are verified as "notable", so I'm closing this.

**Comment by Bl4Cc4t** [comment]
Hm, I fail to see a visual difference between the 2 verification thingies.

Could you please post a screenshot of what you're seeing?
More screenshots are always helpful.

---

related: #492

**Comment by geyerbri** [comment]
Oh it's already been changed yet again and they're no longer visually distinct. Apologies! I think some advertisers had something visually distinct on their tweets for a bit too, but that also appears to be gone now. If I see anything that would contribute to this issue though, I'll be sure to take screenshots to post here.

I still don't think it's worth anyone's time to implement this, given how in flux everything is. Musk has already canceled the subscription-based route of getting a checkmark (at least temporarily), so it's not clear if this will continue being an issue. But that GH project I linked to above might still be a starting point if you want to pursue this.

**Comment by geyerbri** [comment]
Alright, the day of the major change has arrived and Twitter is now no longer distinguishing between paid and legacy checkmarks (https://twitter.com/edzitron/status/1642632025470541825). If you have any interest in adding this enhancement now, I'd again suggest looking at the "eight-dollars" project I linked to when I opened this request to see if it's adaptable here.

**Comment by Bl4Cc4t** [comment]
thanks for the update!
I'll consider it for the rewrite I'm doing :)
(I wonder if that's ever gonna be finished, though :/)

**Comment by geyerbri** [comment]
Welp, no need for this anymore! I'm just going to close it, hope that's ok.

**Comment by Bl4Cc4t** [comment]
Hm, why is there no need anymore?

**Comment by geyerbri** [comment]
Well last week, on the 20th of April, Twitter removed all legacy checkmarks from the platform, removing them from all notable accounts that weren't also paying for Twitter Blue. So there is no longer two types of blue checkmarks to distinguish between, which is the feature I had requested with this issue.

**Comment by Bl4Cc4t** [comment]
Oh, cool. Well, that sucks then. Thanks for letting me know!
