### ISSUE TITLE
Profile spazzes out when I click on a tab

### ISSUE THREAD

**Issue by Korokenichi** [Bl4Cc4t/GoodTwitter2#497]
**Please check the following before you continue**
- [x] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
The profile spazzes out the moment I click a tab (like the media tab or likes tab). The page simply doesn't refresh to the tab's page and some values goes crazy for some reason.

Oh, and it only happens on the legacy design.

**Screenshots**
![60fps](https://user-images.githubusercontent.com/79259221/203083312-e03dc378-7f16-4cb4-a4d9-2c5157ca6707.mp4)

![2022-11-21 22-39-55](https://user-images.githubusercontent.com/79259221/203087222-10be9753-0561-409a-b3c4-1d93baa7b0f6.gif)

**Your configuration**
 - Firefox 107.0 and Chrome 107.0.5
 - Tampermonkey 4.18.1 and Violentmonkey 2.13.3

**Comment by Bl4Cc4t** [comment]
Thanks for noticing. Good thing I always test the script before changing something... 🤦 

This is related to making #492 work, since I move the element in the dom.

**Comment by Korokenichi** [comment]
lets gooooooo
