### ISSUE TITLE
Request: Force "Latest Tweets" view

### ISSUE THREAD

**Issue by buggleston** [Bl4Cc4t/GoodTwitter2#5]
I'm not sure if this is something that can even be done with a userscript, but it would be amazing if we could force the "Latest Tweets" view. If not, would it be possible to make it more obvious when the view has silently switched back to "Home" yet again?

**Comment by Bl4Cc4t** [comment]
Hm, I need some information for that matter.
When does this switching happen? By idling without scrolling?
When scrolling for some time?
Or after opening the site after a certain amount of time? (that would be ideal)

**Comment by buggleston** [comment]
I've only had it change on me when opening the site, not while actively using it
