### ISSUE TITLE
Twitter handle name issue when using small sidebars

### ISSUE THREAD

**Issue by MrCelroy** [Bl4Cc4t/GoodTwitter2#50]
Seen here:
![image](https://user-images.githubusercontent.com/66327074/83550762-ed3ae400-a539-11ea-950e-0395a726c7d9.png)
![image](https://user-images.githubusercontent.com/66327074/83550776-f3c95b80-a539-11ea-8231-cb92b841ed5b.png)

**Comment by Bl4Cc4t** [comment]
Only one report per issue please. The first one is already known: #43

**Comment by Bl4Cc4t** [comment]
You have along name, what should happen to it? should it be truncated?

**Comment by Atari-Dude** [comment]
In the old Twitter, when your name was long (like mine is) it would just cut off part of it. Like mine is "Atari-Dude" Riley Bajda but it would cut it off and display like this. 
![image](https://user-images.githubusercontent.com/66316465/83563218-6dccf680-a4e0-11ea-9dcb-5b7fc94690d3.png)

**Comment by MrCelroy** [comment]
![image](https://user-images.githubusercontent.com/66327074/83562687-92f74e80-a54c-11ea-9dc8-6aba2e136e54.png)
This is how it shows up when I use the larger sidebar, maybe changing it so it doesnt clash with the text at the bottom?

**Comment by Bl4Cc4t** [comment]
related: #72
