### ISSUE TITLE
Restore tweet source label

### ISSUE THREAD

**Issue by nnn1590** [Bl4Cc4t/GoodTwitter2#505]
**Please check the following before you continue**
- [x] Checked if the feature has not been requested before

**Describe the feature**
Recently, Twitter removed source label from https://twitter.com and I would like it back.

Twitter for Android app v8.68.0:
![0票・最終結果 2018年07月16日 19:50・Twitter for Advertisers. 345リツイート 76引用ツイート 323いいね](https://user-images.githubusercontent.com/28985763/205371371-55cf0868-8499-43ad-ab0c-1cc32f912383.png)
Twitter.com as of 2022/12/2 19:38 UTC:
![0票・最終結果 午後7:50・2018年7月16日 345件のリツイート 76件の引用ツイート 323件のいいね](https://user-images.githubusercontent.com/28985763/205372762-de1ce836-5912-487f-b5ea-fcbf78536c79.png)

**Comment by Bl4Cc4t** [comment]
Wow, neat. Yet another change nobody asked for.

**Comment by geyerbri** [comment]
It appears that this solution now puts the source label on one's main wall, after first clicking on the tweet, then returning back to the wall.

Tweet from wall before clicking:
![image](https://user-images.githubusercontent.com/5496867/205521668-e7c2542b-3b04-4f2e-9a6d-b7b5f52d05a4.png)

Tweet from wall after clicking then returning to wall:
![image](https://user-images.githubusercontent.com/5496867/205521703-5e4446f0-ec9e-4440-be88-7c538d10715f.png)

**Comment by Bl4Cc4t** [comment]
huh, thanks for spotting.
