### ISSUE TITLE
Feed Does Not Load Properly When Scrolling Through

### ISSUE THREAD

**Issue by Emijx-Cawthorn** [Bl4Cc4t/GoodTwitter2#507]
**Please check the following before you continue**
- [Yup] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [Mhm] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [Yes] Checked if the issue has not been reported before

**Describe the bug**
On the Latest Tweets section of the Home tab, my feed is not automatically updated until I manually pull something from it (I.E. Translating a tweet in a Non-English language or opening an image. Afterwards it shows a handful of tweets before I have to do it again. This didn't happen on 12/5/22, so it was a recent change that caused this.

**Screenshots**
*An Image of the bottom of my feed before opening an image/translating a tweet.*
![image](https://user-images.githubusercontent.com/112293531/206363581-c7ccbc1b-5e90-4eda-9ebe-da53d0d8782f.png)

**Your configuration**
 - Firefox 107.0.1 (64-Bit)
 - Tampermonkey 4.18.1

**Comment by Emijx-Cawthorn** [comment]
Okay a small little update, but it seems to have fixed itself for the time being? I know it wasn't my internet or my computer causing load issues because my internet is stellar and my pc has plenty of space and ram, so maybe it was just an issue on twitter's back end that wasn't cooperating for whatever reason.

**Comment by Bl4Cc4t** [comment]
Sorry for not responding earlier.

Good to hear that the issue disappeared!
If it decides to come back, please reopen this issue. Thanks!
