### ISSUE TITLE
profile preview(?) does not appear on right sidebar

### ISSUE THREAD

**Issue by dankxen0n** [Bl4Cc4t/GoodTwitter2#508]
profile preview(? is that what it's called?) does not appear on sidebar as it used to

![image](https://user-images.githubusercontent.com/71655697/206814833-75c62e3f-4766-4763-b0ae-dc77c3182d57.png)
screenshot of right sidebar with lack of profile preview

![image](https://user-images.githubusercontent.com/71655697/206815166-10ea9d39-f974-4b13-b6fd-02ccad2e9b97.png)
sidebar without GT2 loaded for reference

latest versions of firefox and violentmonkey are currently being used

**Comment by Bl4Cc4t** [comment]
these screenshots don't help much, what page are you on exactly?

**Comment by dankxen0n** [comment]
im on the page i get after clicking on a tweet. did notice that the profile preview appears briefly before disappearing though.

**Comment by dankxen0n** [comment]
important update. issue is fixed permanently if follow suggestions are turned back on it GT2's settings.

**Comment by Bl4Cc4t** [comment]
oh... now I get it. you didn't mean this sidebar profile of yourself but rather the suggestions for other people... 
![image](https://user-images.githubusercontent.com/6740726/206898654-aea2a7d2-117b-462d-ab86-3b8308baf58d.png)

Yes, these "relevant people" elements are considered follow suggestions, so they are hidden if you check the "Hide follow suggestions" setting along with "sidebar" as location sub setting.

So it's working as intended :)
