### ISSUE TITLE
Favorite/like isnt showing on preview

### ISSUE THREAD

**Issue by TheArticToxic9** [Bl4Cc4t/GoodTwitter2#509]
For some reason when i go into my notifications or when i preview a tweet from my provile it doesnt show the likes displayed? Im on good twitter 0.0.42 btw

![image](https://user-images.githubusercontent.com/38593949/208817531-b1a59492-2348-4515-9016-91f6cfc3a6c1.png)
![image](https://user-images.githubusercontent.com/38593949/208817717-745acfb9-4045-4bd7-9b32-8c4ccedbbd35.png)

**Comment by TheArticToxic9** [comment]
i am come to notice that it isnt a bug but in fact a update on elon's part. I will change the label to enchantment request so i wouldnt see this abysmal ui design anymore

**Comment by Bl4Cc4t** [comment]
hey, sorry for being absent for so long.
do you still have this issue? if yes, what browser are you using?

**Comment by TheArticToxic9** [comment]
> hey, sorry for being absent for so long.
> 
> cannot reproduce this issue, do you still have it? if yes, what browser are you using?

I dont have that one, i'm currently using windows 10

however i do have another issue 
![image](https://user-images.githubusercontent.com/38593949/213075113-14aff8c0-f50e-49b7-ae7b-0cac42e4b85a.png)
(not my screenshot)
the replies feature is hidden which is annoying if i wanted to reply to tweets quickly, idk if its a glitch on the goodtwitter2 or the og twitter's case
