### ISSUE TITLE
Hide tweet view count

### ISSUE THREAD

**Issue by nnn1590** [Bl4Cc4t/GoodTwitter2#511]
**Please check the following before you continue**
- [x] Checked if the feature has not been requested before

**Describe the feature**
Recently, Twitter added tweet view count which is even shows up in tweets that are not own and bad for mental health.
So, I would like it to be hidden.
![ーーー/KTnnn1590(@nnn1590)'s tweet・9 mins ago・閲覧数表示いらない(確信)・表示数57](https://user-images.githubusercontent.com/28985763/209282969-3524a734-5b16-4158-b601-732d219b886b.png)
![Details page for tweet in above image・63件の表示(this text is a link to analytics page)](https://user-images.githubusercontent.com/28985763/209283673-bfce2e45-5129-472c-9337-c4f7f8ecf09f.png)
![A tweet of Prime numbers @_primes_・2 hours ago・1027027・viewed 2,041 times・4 RTs・28 likes](https://user-images.githubusercontent.com/28985763/209285461-1b7acc13-39a5-446f-be77-37ce59162780.png)
(I don't own `@_primes_`, but even it shows up(!) and this is not limited to bots)

**Comment by Lastorder-DC** [comment]
#510

**Comment by nnn1590** [comment]
Oh, sorry for the duplicate request...

**Comment by Bl4Cc4t** [comment]
no need to change the title and description, you can just add the "duplicate" tag :D
