### ISSUE TITLE
Revert For You / Following tab to be a small toggle button again

### ISSUE THREAD

**Issue by nanakisan** [Bl4Cc4t/GoodTwitter2#519]
Twitter just rolled out a forced update that makes the timeline default to For You mode (the new form of Home) unless you specifically toggle it to Following mode (the new form of Latest Tweets). This used to be toggled via a small unintrusive button to the top right of the timeline. That's effectively gone now.

**Comment by Michpem** [comment]
Today Twitter also made it so even if you swapped to the Following tab, it reverts back to For You every time you refresh/open the page, so a way to force it to always show Following (similar to the now broken Force “Latest Tweets First” option) would be nice too.

**Comment by Bl4Cc4t** [comment]
hm, at least with change I can throw away a lot of lines that are not needed anymore :D

---

btw, if anyone is interested:
looking at the code I previously wrote for that purpose, it looks like they have previously AB tested turning that setting into tabs about a year ago...
