### ISSUE TITLE
Profile box in left sidebar

### ISSUE THREAD

**Issue by cszabla** [Bl4Cc4t/GoodTwitter2#52]
Any way to keep it there when zoomed to 100%? Currently in Chrome it moves to the right unless I zoom to 90% or less. Also disappears when I look at profile view. A lesser issue: the screenname being underlined, which wasn't the case in old / good twitter.

**Comment by cszabla** [comment]
Ah I fixed most of this issue when I updated and changed the sidebar and text size, but it would still be great to have a three-column layout in profile view, including the profile box and photos in the left column!

**Comment by Bl4Cc4t** [comment]
Sorry that I didn’t get back to you here.

> Ah I fixed most of this issue when I updated and changed the sidebar and text size,

That’s good to hear :D

> but it would still be great to have a three-column layout in profile view, including the profile box and photos in the left column

hm, I guess I can close this in favor of https://github.com/Bl4Cc4t/GoodTwitter2/issues/8, what do you think?

**Comment by cszabla** [comment]
Yes, the three column layout is working for me now. The one issue I have now though is I can't see the rest of the left trends column when I scroll down the timeline; it just stays frozen.

**Comment by Bl4Cc4t** [comment]
I already fixed that for the next version :)
