### ISSUE TITLE
Replies button doesnt show

### ISSUE THREAD

**Issue by TheArticToxic9** [Bl4Cc4t/GoodTwitter2#521]
hey, sorry for being absent for so long.

cannot reproduce this issue, do you still have it? 
if yes, what browser are you using?

I dont have that one, i'm currently using windows 10

however i do have another issue
![image](https://user-images.githubusercontent.com/38593949/213075744-509947c5-8437-466a-9df3-e0d386085d58.png)
(not my screenshot)

For some reason the reply is hidden which is tedious for me with how much i use it. I dont know if its a goodtwitter2 problem or a original twitter glitch 
_Originally posted by @Bl4Cc4t in https://github.com/Bl4Cc4t/GoodTwitter2/issues/509#issuecomment-1372132907_

**Comment by TheArticToxic9** [comment]
Also for some reason i dont get notflications for your replies so sorry if i take too long to respond im new in github

**Comment by TheArticToxic9** [comment]
update: Nothing shows on the bottom when i click on a tweet not the likes, retweets or qrts

**Comment by Bl4Cc4t** [comment]
hey, please post what browser & version you're using, along with the userscript manager and its version

**Comment by TheArticToxic9** [comment]
> hey, please post what browser & version you're using, along with the userscript manager and its version

As  I said before

Windows 10

Google Chrome: 106.0.5259 (planning on switching to ungoogled chrome soon)

Goodtwitter2: 0.0.43

Tampermonkey: 4.18.1

**Comment by Bl4Cc4t** [comment]
Cannot reproduce this issue. Have you tried disabling other extensions (like uBlock Origin) and check if it still occurs?

**Comment by TheArticToxic9** [comment]
> Cannot reproduce this issue. Have you tried disabling other extensions (like uBlock Origin) and check if it still occurs?

I disabled tweek new twitter and ublock and apparently it happens when ublock is enabled so i disabled it 

Tweak new twitter is fine though

tysm
