### ISSUE TITLE
ever since the change it keeps refreshing to "for you"

### ISSUE THREAD

**Issue by DcSensai** [Bl4Cc4t/GoodTwitter2#527]
**Describe the bug**
ever since "for you" and "following" has been added to the top to replace the star on pc. every time the tab refreshes it switches back from "following" to "for you" and yes i have the "Force “Latest Tweets First” mode" checked in the settings. 

**My configuration**
 - Browser: Firefox v109.0 (64-bit)
 - Userscript Manager: Tampermonkey v4.18.1

**Comment by Bl4Cc4t** [comment]
are you on the latest version of the script (currently v0.0.43.1)?
this feature has been added just a bit ago

**Comment by DcSensai** [comment]
forgot to check for updates. sorry.

**Comment by Bl4Cc4t** [comment]
great!
