### ISSUE TITLE
URL and highlighted tab mismatche actual page

### ISSUE THREAD

**Issue by arturo182** [Bl4Cc4t/GoodTwitter2#528]
I'm having a very weird issue navigating between the Home and Notifications sections. It's hard to explain in words but luckily I can reproduce it 100% even after reloading the tab, or restarting the browser.

Here it is:
![gt2](https://user-images.githubusercontent.com/249082/214180653-223dde19-c7f6-41c0-b86c-cb9d4a999af6.gif)

Basically:
If I'm at Home and click Notifications, the page navigates to /notifications as expected, you can see I'm in the "All" tab. Then when I click to go back Home, the Home section is loaded, but the URL is /notifications/verified and the Notifications item in the menu is highlighted as if I was still on the Notifications page. Clicking the Home link does nothing, the only way to fix it is to click the "Following" tab.

Let me know if you need any more info or testing from my side.

**Your configuration**
 - Opera 94.0.4606.38
 - Violentmonkey v2.13.9
 - GT2 0.0.43.1
 - Windows 11

**Comment by arturo182** [comment]
One more related issue, a lot more annoying: when I'm in this "/notifications/verified but actually Home" state and I click a photo to open it in the fullscreen view and then close it with the X in the corner, I get taken to the actual /notifications/verified page and it shows me the Verified Notifications tab. Clicking Home from this state takes me to the correct /home. 

Here's a gif:
![gt2_2](https://user-images.githubusercontent.com/249082/214183178-779c84a4-83c7-4666-be55-2488d20bfd83.gif)

**Comment by Bl4Cc4t** [comment]
thank you for reporting! what a dumb oversight...

**Comment by arturo182** [comment]
But what an elegant fix :)
