### ISSUE TITLE
Disable scrolling animation when moving through media

### ISSUE THREAD

**Issue by shootlazer** [Bl4Cc4t/GoodTwitter2#53]
One of the things I dislike the most about the new twitter.
Being able to disable that animation would be nice. 
The one that shows when you move left/right on a tweet with 2 or more pictures for example.

**Comment by Bl4Cc4t** [comment]
unfortunately, this behaviour is written in JS and I cannot intercept that in some easy way.

**Comment by lread31** [comment]
You can turn that off in settings > accessibility > reduce motion

**Comment by Bl4Cc4t** [comment]
Oh, I did not know that. Thanks for that!
