### ISSUE TITLE
Twitter icon renders as a blue square on Chrome

### ISSUE THREAD

**Issue by BluSpring** [Bl4Cc4t/GoodTwitter2#538]
**Please check the following before you continue**
- [x] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
The doge to Twitter icon fix does not render, and is instead just a blue square.

**Screenshots**
![image](https://user-images.githubusercontent.com/20620191/229937052-c7cc5d0e-cb0a-4d3d-b91c-abeac4e032cd.png)

**Your configuration**
 - Chrome 112
 - Tampermonkey 4.18.1

**Comment by NekoSam395** [comment]
Well, how about an option to put custom Twitter logo? Not only skeumorph/flat/neumorph blue bird, but it can be **anything.**

**Comment by IWarriors** [comment]
Is it possible this could be an option please? I don't mind the Dodge icon.

**Comment by Bl4Cc4t** [comment]
@NekoSam395 great idea, I'll put it on the list for stuff that I'll add to the new version I'm slowly developing (1.x)

@IWarriors option has been added

**Comment by NekoSam395** [comment]
> @NekoSam395 great idea, I'll put it on the list for stuff that I'll add to the new version I'm slowly developing (1.x)

That's cool! I will waiting for it. 🥰
