### ISSUE TITLE
GoodTwitter2 v0.0.44 has stopped working for me on 04/04/2023

### ISSUE THREAD

**Issue by Quesito35** [Bl4Cc4t/GoodTwitter2#539]
Hello.
I am writing to you from Spain.
I have GoodTwitter2 v0.0.44 installed on a desktop computer.
Installed Violentmonkey Version 2.14.0
I use Windows 11Pro 22H2.
I have Google Chrome Version 112.0.5615.50 , Microsoft Edge Chromium Version 111.0.1661.62 and Brave browsers. Version 1.49.132 Chromium: 111.0.5563.147
Yesterday, 04/3/2023, everything was working correctly on the twitter.com website.
Today 4/4/2023 the script no longer works, Twitter shows as if it had no script installed. (screenshot attached)
I have tried in all three browsers and none of them work.
Waiting for help.
![GoodTwitter2 v-0044](https://user-images.githubusercontent.com/67263381/229928866-762baf0e-b2d7-4fa8-ab65-52896fbb1c19.png)
![1](https://user-images.githubusercontent.com/67263381/229933620-7653ca85-afb2-4937-a53b-745b2ec6b56a.png)

**Comment by go2tom42** [comment]
Same here

**Comment by nanakisan** [comment]
As of just now the plugin ceased to function.

**Comment by nanakisan** [comment]
As of 2 hours the plugin has ceased function for me

**Comment by dankxen0n** [comment]
huh, sometimes it doesnt load fully for me either but a refresh of the page fixes it

**Comment by nanakisan** [comment]
Seems clearing cache for Twitter solved my problem.

**Comment by Quesito35** [comment]
Hello again.
The bug seems to be in GoodTwitter2 v.0.0.44.
I have been in contact with a friend of mine and her in v.0.0.43.2 the script works correctly. (Attachment screenshot).
The question is: If I have GoodTwitter2 v.0.0.44, how can I go back and install version 0.0.43.2 in Google Chrome, Microsoft Edge Chromium and Brave browsers?
If I go to the link https://github.com/Bl4Cc4t/GoodTwitter2 "Installation" I always get version 0.0.44.
Waiting for some help.
Thank you.
![Inked13_LI](https://user-images.githubusercontent.com/67263381/230252324-965f5d9e-aa05-427a-8c74-321bfe1e1ee8.jpg)

**Comment by Bl4Cc4t** [comment]
I reverted the line that broke the site, please update and let me know if something breaks again (feel free to reopen/create a new issue)

**Comment by Quesito35** [comment]
Hello @Bl4Cc4t
Fixed.
With the new version 0.0.44.1 GoodTwitter2 works again in all browsers.
And although it is not important, the icon of the blue bird has returned.
Thank you very much
All the best.
![13](https://user-images.githubusercontent.com/67263381/230495558-a7a30560-f80f-4951-8061-5cd9b7756f4b.jpg)

**Comment by Bl4Cc4t** [comment]
great to hear, thanks for reporting back!

**Comment by nanakisan** [comment]
Looks like it's working on my end as well. Good job!
