### ISSUE TITLE
Profile appears in the right sidebar

### ISSUE THREAD

**Issue by MCNMikeTV** [Bl4Cc4t/GoodTwitter2#54]
Cosmetic issues:

-Themes are inconsistent (a bit of dark theme but mostly light theme)
-Profile shows up on right side of screen
-No UI change was seemingly made (still looks like modern Twitter)

Coding issues:
Lines 86-90 - "eslint: no-undef - 'i18n' is not defined."
Line 708 - eslint: no-undef - 'jQuery' is not defined."
Line 876 - "eslint: no-undef - 'jQuery' is not defined."
Line 876 - "eslint: no-undef - 'waitForKeyElements' is not defined."

**Comment by Bl4Cc4t** [comment]
> -Themes are inconsistent (a bit of dark theme but mostly light theme)

change the background in your display settings or update the script.

> -Profile shows up on right side of screen

it sometimes does that, I have to look into that

> -No UI change was seemingly made (still looks like modern Twitter)

I state on the front page that this is not a full recreation. It is a hybrid between the old and the new version. I am not capable of working on this project 24/7.

> Coding issues:
Lines 86-90 - "eslint: no-undef - 'i18n' is not defined."
Line 708 - eslint: no-undef - 'jQuery' is not defined."
Line 876 - "eslint: no-undef - 'jQuery' is not defined."
Line 876 - "eslint: no-undef - 'waitForKeyElements' is not defined."

These are not issues, ignore this.
