### ISSUE TITLE
Profile sometimes shows as not logged in

### ISSUE THREAD

**Issue by BluSpring** [Bl4Cc4t/GoodTwitter2#540]
**Please check the following before you continue**
- [x] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
Sometimes the profile shows as not logged in, but upon refreshing it will be fine.
This seems to occur when you load a new Twitter tab, and when you refresh it will be fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/20620191/229975759-4a16bac0-f647-42db-bb87-29e11762a027.png)

**Your configuration**
 - Chrome 112
- Tampermonkey 4.18.1

**Comment by qfoxb** [comment]
Same

**Comment by kamikazilucas** [comment]
Same

**Comment by Bl4Cc4t** [comment]
should be same issue as #539

**Comment by Bl4Cc4t** [comment]
I reverted the line that broke the site, please update and let me know if something breaks again (feel free to reopen/create a new issue)
