### ISSUE TITLE
Loading into a Direct Message directly by URL has styling broken

### ISSUE THREAD

**Issue by BluSpring** [Bl4Cc4t/GoodTwitter2#541]
**Please check the following before you continue**
- [x] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
When loading directly into a Direct Message's URL (looks like this: https://twitter.com/messages/1323366620761186305), it loads being broken. This only happens when loading into it from a new tab, and is fixed on reload.

**Screenshots**
![image](https://user-images.githubusercontent.com/20620191/230288758-089b324c-7188-4c34-abb9-ace8216f89d3.png)

**Your configuration**
 - Chrome 112.0.5615.50
 - Tampermonkey 4.18.1

**Comment by Bl4Cc4t** [comment]
should be #539

**Comment by Bl4Cc4t** [comment]
I reverted the line that broke the site, please update and let me know if something breaks again (feel free to reopen/create a new issue)
