### ISSUE TITLE
I can't find "Settings" on Twitter with GoodTwitter2.

### ISSUE THREAD

**Issue by Quesito35** [Bl4Cc4t/GoodTwitter2#551]
Hello.
I have an OMEN by HP 880-023ns desktop computer.
I use Windows 11 Pro. v. 22H2 22621.1555.
I have Google Chrome browsers Version 112.0.5615.138 (Official Build) (64 bit). Microsoft Edge Version 112.0.1722.58 (Official Build) (64-bit).
I have GoodTwitter2 v0.0.44.1 script installed.
The problem I have is that when I enter my Twitter account I can't access both Twitter and GoodTwitter2 "Settings". (if I remember correctly, in the past you could enter by clicking on the top photo of the Twitter website)
On the other hand, if I enter Twitter without logging in, "Settings" appears at the top.
What, having not logged into my account, in "Settings" I cannot make changes to my Twitter account, in the "GoodTwitter2 Settings it does let me enter, what I do not know is that since I have not logged in, if I want to make any changes, those changes are saved when you log in.
What interests me the most is how do I enter the Twitter settings (once I'm logged in) to be able to make account changes?
Waiting for your help.

**Comment by Bl4Cc4t** [comment]
Works for me in both chrome and edge. Could you please disable all other extensions you have installed and try again?
I suspect one of  your extensions breaks something, but I could be wrong.

Let me know if you find an extension that does break the site :)

**Comment by Quesito35** [comment]
Hello.
Thank you very much for answering.
I have done what you tell me in your comment.
And I have found that it is due to an extension as you indicate. The extension is "Ace Script". Both in Chrome, Edge, etc. browsers.
By deactivating it, I can enter the Twitter settings by clicking on my profile photo.
Thank you very much.
All the best.
![Sin título](https://user-images.githubusercontent.com/67263381/236689048-57fb5349-6507-4aee-972b-ce9166b6860a.png)

**Comment by Quesito35** [comment]
Hello.
Thank you very much for answering.
I have done what you tell me in your comment.
And I have found that it is due to an extension as you indicate. The 
extension is "Ace Script" for "Ace Stream". Both in Chrome, Edge, etc. 
browsers.
By deactivating it, I can enter the Twitter settings by clicking on my 
profile photo.
Thank you very much.
All the best.


------ Mensaje original ------
De "Bl4Cc4t" ***@***.***>
Para "Bl4Cc4t/GoodTwitter2" ***@***.***>
Cc "Quesito35" ***@***.***>; "Author" 
***@***.***>
Fecha 06/05/2023 17:37:25
Asunto Re: [Bl4Cc4t/GoodTwitter2] I can't find "Settings" on Twitter 
with GoodTwitter2. (Issue #551)
