### ISSUE TITLE
Translate Tweet stopped working  

### ISSUE THREAD

**Issue by Harumoon** [Bl4Cc4t/GoodTwitter2#555]
**Please check the following before you continue**
- [ ] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [ ] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [ ] Checked if the issue has not been reported before

**Describe the bug**
What sites does it affect?

**Screenshots**
For display issues, adding screenshots or even videos of your screen is recommended.

**Your configuration**
 - Browser (e.g. Chrome 83)
 - Userscript Manager (e.g. Tampermonkey v4.10)

Translate Tweet stopped working. It was working fine until today, but when I click it now in the [Following](https://twitter.com/home) feed nothing happens [Capture 1]. 
If I open the actual tweet it tries to 'fetch' the translation but fails [Capture 2].
Something kind of similar but not exactly the same happened a while ago and you were able to fix it, which was excellent.

Firefox ESR 102.11.0
It's the same with Violent Monkey or Tampermonkey
As far as I can tell everything is up to date.

![Capture 1](https://github.com/Bl4Cc4t/GoodTwitter2/assets/101605071/4a27c32a-86e4-4ec3-9f3f-a26c408b3906)

![Capture 1](https://github.com/Bl4Cc4t/GoodTwitter2/assets/101605071/9bad8eb7-2df6-4f88-a1aa-5b91e566d752)

**Comment by Harumoon** [comment]
It seems to have uploaded the first pic twice...I'll try 2 again

![Capture 2](https://github.com/Bl4Cc4t/GoodTwitter2/assets/101605071/b6dcefc4-7505-4e8c-a558-14372406722b)

**Comment by Harumoon** [comment]
It's working again now, thanks :)

**Comment by Bl4Cc4t** [comment]
Hello, sorry for not replying earlier.
The translation feature being broken is sadly out of my control, so it working again wasn't my doing :D 
Regardless of that, I added some error messages, so that you know when it doesn't work.

I'll close this issue now, feel free to open another one if you have another problem!
