### ISSUE TITLE
On "regular twitter" it shows up as Home / Twitter on the tab header but it shows up as Latest Tweets / Twitter on GoodTwitter

### ISSUE THREAD

**Issue by MrCelroy** [Bl4Cc4t/GoodTwitter2#56]
A little nitpicky I know so I'm unsure if this would even be an issue.
![image](https://user-images.githubusercontent.com/66327074/83606966-0466e980-a5ad-11ea-82cd-91a8eb4facc9.png)
![image](https://user-images.githubusercontent.com/66327074/83607037-1b0d4080-a5ad-11ea-9adf-92722a048324.png)

**Comment by Bl4Cc4t** [comment]
This is expected behaviour. You have the `forceLatest` option activated.

**Comment by MrCelroy** [comment]
Actually I had already turned it off when I posted that.

Mustve been a bug because it only went away after I logged out

**Comment by Bl4Cc4t** [comment]
That sounds weird. Please report back if you get the issue again. I do not know what could cause that to happen.
