### ISSUE TITLE
[v1.0-beta.1] Site refreshes when selecting some buttons

### ISSUE THREAD

**Issue by BluSpring** [Bl4Cc4t/GoodTwitter2#570]
**Please check the following before you continue**
- [x] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
When you select the buttons on the left side (and the bird button) of the navbar, the website refreshes. This also happens in the profile button dropdown, when you select on Profile, Lists and Communities. Does not appear to happen on Bookmarks.

**Screenshots**
(unable to get any, recording seems to be blue-screening my computer)

**Your configuration**
Chrome 115
Tampermonkey v4.19.0

**Comment by plissken1138** [comment]
confirming this on FF 117 / Violentmonkey 2.15.0

reverted back to electric boogasloo for now.

**Comment by BluSpring** [comment]
Fixed in v1.0.0-beta.3
