### ISSUE TITLE
Message Box no longer able to be hidden

### ISSUE THREAD

**Issue by Spabobin** [Bl4Cc4t/GoodTwitter2#571]
[x] Bug happens with the newest version of GT2
[x] Checked FAQ
[x] Checked if the issue has not been reported before

The "Messages" box on the bottom right is no longer hidden when the option is selected. Happens everywhere on Twitter as far as I can tell, starting within the last few days.

Chrome 116.0.5845.96 / Firefox 116.0.3
Tampermonkey v4.19.0

**Comment by RealymanLP** [comment]
Same problem here.
But it disappears for me when clicking the "open arrows".

**Comment by Bl4Cc4t** [comment]
Sorry for the long absence (again)
fixed it in e5700e7764738d387ddaf015dfe4e3feb27ae709
see https://github.com/Bl4Cc4t/GoodTwitter2/releases/tag/v1.0.0-beta.2 for latest beta
