### ISSUE TITLE
when click icon pop up at top left 

### ISSUE THREAD

**Issue by keroberos-s** [Bl4Cc4t/GoodTwitter2#577]
**Please check the following before you continue**
- [ v] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [ v] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [v ] Checked if the issue has not been reported before

**Describe the bug**
What sites does it affect?

**Screenshots**
![ddd](https://github.com/Bl4Cc4t/GoodTwitter2/assets/71687755/44f1d479-d8fb-4469-b87d-bb6b67105074)

also after a few clicks TREND part, not anymore work

**Your configuration**
Chrome 119.0.6045.160(Official Build) (64bit)
Tampermonkey v.5.0.6190

**Comment by AndrewPSSP** [comment]
Same with me -- monetisation pops up when clicking the user icon

**Comment by AndrewPSSP** [comment]
https://www.twitter.com/i/bookmarks

**Comment by MrCelroy** [comment]
![image](https://github.com/Bl4Cc4t/GoodTwitter2/assets/66327074/d26a2715-2f79-47d4-93c5-5f7af510e4e6)
Yeah i'm getting the same thing here

Chrome: Version 119.0.6045.200 (Official Build) (64-bit)
Tapermonkey: v4.19.0

**Comment by ni1chigo2115** [comment]
same

**Comment by DGnie** [comment]
@MrCelroy I see only Monetization and the lower ones when clicking on my profile, there's no shortcut for Bookmarks somehow 
![image](https://github.com/Bl4Cc4t/GoodTwitter2/assets/129951229/b4b85031-e5ab-43c3-9ed8-7635c2aa34fe)

@AndrewPSSP thx for the link

**Comment by Bl4Cc4t** [comment]
Sorry for the long absence (again)
fixed it in 54fcea112647156d8ca6741dcb0f3d6f14739bd3
see https://github.com/Bl4Cc4t/GoodTwitter2/releases/tag/v1.0.0-beta.2 for latest beta!
