### ISSUE TITLE
Post button is dead

### ISSUE THREAD

**Issue by ni1chigo2115** [Bl4Cc4t/GoodTwitter2#580]
simply

**Comment by nanakisan** [comment]
Signed in to confirm that the Tweet button is also broken. Posting tweets from the "What's happening" interface does however still work.

**Comment by SuitYourself** [comment]
Edit the script, search for "/compose/tweet" replace with "/compose/post"

**Comment by Bl4Cc4t** [comment]
Sorry for the long absence (again)
fixed it in 7e17dc45dfbdda8ad99a577892292ccbea57adfb
see https://github.com/Bl4Cc4t/GoodTwitter2/releases/tag/v1.0.0-beta.2 for latest beta
