### ISSUE TITLE
[v1.0.0-beta.3] Twitter feed and profiles are broken

### ISSUE THREAD

**Issue by Sora-yx** [Bl4Cc4t/GoodTwitter2#584]
**Please check the following before you continue**
- [x] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
Starting with 1.0.0-beta.2, (but also happen with beta.3), the Twitter feed breaks and we can't see any tweet, this also happens with any profile with always the same message **"something went wrong, try reloading"**.

![image](https://github.com/Bl4Cc4t/GoodTwitter2/assets/50106301/1eeb342c-b103-4aa5-9519-ab2b1bb2534a)

This can be temporary fixed by clearing the cache or swapping the language in the settings, but as soon as you close the browser or close the tab and re open twitter, the issue will be back.

**Configuration**
 - Browser: Mozilla Firefox 123.0.1 (64 Bits)
 - Userscript Manager: Tampermonkey v5.1

Let me know if you need any extra detail and thanks for your hardwork on this project!

**Comment by Bl4Cc4t** [comment]
Hello, thanks for your report. This should be the same issue as #583. 

I found the solution to that yesterday and will release a new beta version later this week. Until then, you can try out this test version if you want to see if the fix works for you: [gt2.v1.0.0-beta.4-pre.user.js](https://gist.github.com/Bl4Cc4t/86ddfc42b22cb5429340311b778b74f3/raw/ef371b468d3b0b4a565b02611d5396e99679b88d/gt2.v1.0.0-beta.4-pre.user.js)

**Comment by Sora-yx** [comment]
Yeah everything seems to work now thank you! I should have thought that those issues were the same, I didn't put it together because they were talking about the group chat and not tweet feed. I'll close this to avoid duplicate.
