### ISSUE TITLE
Right small sidebar keeps 350px width

### ISSUE THREAD

**Issue by geyerbri** [Bl4Cc4t/GoodTwitter2#63]
Appears that, with small sidebar enabled, the right sidebar keeps a class that maintains the 350px width, despite the content within being restricted to 290px. The class appears to be `.r-1hycxz`.

![Capture1](https://user-images.githubusercontent.com/5496867/83685522-cf5f9480-a5b6-11ea-9b99-ab92390705d1.PNG)

**Comment by geyerbri** [comment]
Forgot to add, this is on version 0.0.18. 

Also forgot to add that, even as-is this has been an incredible tool! Thank you!

**Comment by Bl4Cc4t** [comment]
You are looking at the wrong stuff.
This is only the property which the element is set to. This does *not* mean that is also appears like that! 

You can see the actual size by hovering over the respective html part:
![image](https://user-images.githubusercontent.com/6740726/83695892-5b93ab00-a5fb-11ea-8854-55956828df5c.png)

Or take a look at the box model, located at the bottom of the right tab of the developer tools:
![image](https://user-images.githubusercontent.com/6740726/83695971-8ed63a00-a5fb-11ea-973a-bf2e46e91e40.png)

**Comment by geyerbri** [comment]
This does not account for how the right small sidebar is a _child_ of the div container I highlighted here, thus causing the clearly-visible overflow problem. Notice the horizontal scrollbar confirming.
