### ISSUE TITLE
Permanent display of 10 trends

### ISSUE THREAD

**Issue by Bl4Cc4t** [Bl4Cc4t/GoodTwitter2#64]
via [Reddit](https://www.reddit.com/r/Twitter/comments/gngewq/i_created_a_legacynew_twitter_hybrid/fss9gxv/)

**Comment by zetorplugger** [comment]
Sorry if this is a dumb question  but how can we know when this feature will be available?

**Comment by Bl4Cc4t** [comment]
I guess when this issue is closed. Will be included in v0.0.20!
