### ISSUE TITLE
save image directly 

### ISSUE THREAD

**Issue by nohar7** [Bl4Cc4t/GoodTwitter2#70]
is there a way to save image directly without opening the link? 
![image](https://user-images.githubusercontent.com/66399211/83709078-3755bf80-a637-11ea-87c1-cce334e7a209.png)

**Comment by lread31** [comment]
Probably related: middle clicking an image opens the tweet again in a new tab instead of opening the image.

**Comment by Bl4Cc4t** [comment]
Hm, I am able to save images this way by default (latest chrome and firefox).
Not sure why you don’t have that option, what browser and version do you use?
![image](https://user-images.githubusercontent.com/6740726/85200137-1f4b9480-b2f5-11ea-95a8-ab8da55fc9e8.png)

**Comment by lread31** [comment]
You can save images if you're on the tweet page or if there's more than one image, but if you're in a timeline looking at a tweet with a single image you can't save it.

**Comment by Bl4Cc4t** [comment]
that screen was taken from the timeline though :V

**Comment by lread31** [comment]
Well that's how it seems to work for me in firefox.
