### ISSUE TITLE
Adding options to hide who to follow and what's happening 

### ISSUE THREAD

**Issue by A7medme** [Bl4Cc4t/GoodTwitter2#74]
Adding options to hide who to follow and what's happening 

```
//hide Who to Follow
waitForKeyElements("aside[aria-label='Who to follow']", () => {
     $("aside[aria-label='Who to follow']").parent().css("display", "none");
})

//hide What’s happening
 waitForKeyElements("div[aria-label='Timeline: Trending now']", () => {
      $("div[aria-label='Timeline: Trending now").parents().eq(3).css("display", "none");
})
```

**Comment by Bl4Cc4t** [comment]
what should happen to the right sidebar once these two are not shown?

**Comment by spodermenpls** [comment]
> what should happen to the right sidebar once these two are not shown?

Maybe just let the "Bedingungen - Datenschutzrichtlinien - Cookies - Impressum - Anzeigen - Info - Mehr - © 2020 Twitter, Inc." box sit atop then? Or there could be an option to move it to the bottom of the left sidebar (to empty the right sidebar completely - maybe including a "re-centering" option for the left and center?), or the option hide it too, if someone doesn't want to see the "Twitter TOS and Misc"-section at all.
