### ISSUE TITLE
Right small sidebar keeps 350px width redux

### ISSUE THREAD

**Issue by geyerbri** [Bl4Cc4t/GoodTwitter2#75]
**Please check the following before you continue**
- [X] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [X] Checked if the issue has not been reported before (re-report of incorrectly-discounted bug #63 ; prefer this merged there)

**Describe the bug**
As I stated in the first reporting of this, with small sidebars enabled, the right sidebar retains a class that keeps the width at 350px. Given the confusion, I will be more clear: one of the right sidebar's _parent_ divs retains the class and has its width set to 350px, causing page overflow. I am attaching additional screenshots to show the overflow once again. Notice the horizontal scroll bar, present because of the problem. In the second screenshot, notice that the highlighted div - containing the smaller sidebar - is _within_ the previously-highlighted div that has the larger pixel width.

The result of this bug is that the page overflows despite it appearing wide enough to still display all three columns.

**Screenshots**
![Capture3](https://user-images.githubusercontent.com/5496867/83698941-b532b000-a5d0-11ea-96e2-d94b350e2c13.PNG)

![Capture7](https://user-images.githubusercontent.com/5496867/83699123-430e9b00-a5d1-11ea-8e22-f3b899759ef4.PNG)

**Your configuation**
 - Opera Version 68
 - Tampermonkey Version 4.9.6091

**Comment by Bl4Cc4t** [comment]
Why do you have to open a new issue though, that was very unnecessary

**Comment by geyerbri** [comment]
I was unsure if you were checking comments on issue's you've already closed is all. This is a bug, so whichever of these two you'd like to keep open to acknowledge is fine, as long as it's acknowledged.

**Comment by Bl4Cc4t** [comment]
Also, I did not mean to be rude or something, it’s just that I did not really got what you meant.
So sorry again, I can be a bit dumb sometimes

Also, this a very quick fix as it is only one selector that is missing from the css :)

**Comment by geyerbri** [comment]
Apologies, I too did not intend to be rude. Looking forward to 0.0.20 to see this fix. Thank you!

**Comment by geyerbri** [comment]
Fixed, thank you!
