### ISSUE TITLE
Latest Tweets keeps showing up on tab header despite turning it off, logging off fixes it

### ISSUE THREAD

**Issue by MrCelroy** [Bl4Cc4t/GoodTwitter2#76]
**Describe the bug**
Latest Tweets keeps showing up on tab header despite me turning it off, logging off fixes the issue

**Video**
[Video trimmed to hide personal info](https://www.youtube.com/watch?v=i6VtqGK8cXA)

**Your configuation**
 - Chrome Version 83.0.4103.97 (Official Build) (64-bit)
 - Tapermonkey v4.10

**Comment by Bl4Cc4t** [comment]
You have to manually switch back to “Home”.

Click on the spark button
![image](https://user-images.githubusercontent.com/6740726/83815523-a9beb200-a6c0-11ea-914a-53f7a1160301.png)

and select “Go back Home”
![image](https://user-images.githubusercontent.com/6740726/83815606-dd014100-a6c0-11ea-9dcf-fda5b2a1c052.png)

**Comment by MrCelroy** [comment]
I'm probably blind but where is the spark button located at?

**Comment by Bl4Cc4t** [comment]
top right corner of your timeline
![image](https://user-images.githubusercontent.com/6740726/83905729-75033700-a762-11ea-9cdd-8dc6254dc414.png)
