### ISSUE TITLE
Move direct message div to center on fullscreen 

### ISSUE THREAD

**Issue by zetorplugger** [Bl4Cc4t/GoodTwitter2#77]
On full screen the profile info box appears when you are on the direct message page
pushing the message div to the left 

it would be better if the profile box did not appear but instead the user list was where the profile
box is putting the message box in the middle 

Full screen: https://i.postimg.cc/MHX9JWq9/full-screen1.jpg

**Comment by Bl4Cc4t** [comment]
so should the user list only be moved or should it be expanded?

**Comment by zetorplugger** [comment]
The user list can be made wider of course that would not hurt but the main point is that the message section should be centered so it would look like this on full screen

https://postimg.cc/4nMqBLC8

thanks

**Comment by Bl4Cc4t** [comment]
err, but then there would be an empty right sidebar...

**Comment by zetorplugger** [comment]
if that is a problem maybe you could put  the profile box there
or the trend box if possible
I just think it would be a good idea to put the message section in the middle because that's where
your eyes gravitate when you are typing, like on this very site

**Comment by Bl4Cc4t** [comment]
I cannot put the trends there since they do not exist on that page.
and switching the position of the dashboard profile is also kinda confusing.
I agree that the space should be used for something, so what if we extend the main message section instead?

**Comment by zetorplugger** [comment]
OK, to some extend the message section should be expanded 

what about this? https://i.postimg.cc/G9wXMqbK/expand.png

**Comment by Bl4Cc4t** [comment]
yeah, that’s kinda what I meant.
I’ll play around with it

**Comment by zetorplugger** [comment]
Great, thanks
