### ISSUE TITLE
legacy profile layout

### ISSUE THREAD

**Issue by Bl4Cc4t** [Bl4Cc4t/GoodTwitter2#8]
recreate the full-width profile banner layout

**Comment by Aridow** [comment]
I think the sticky part of the banner when scrolling wasn't as low as that in Legacy Twitter : 
![image](https://user-images.githubusercontent.com/65539338/86499481-c4ea1380-bd8b-11ea-965e-d5fd915c7441.png)
In this video at 4:00, we can see the heigth : 
https://www.youtube.com/watch?v=lp_2-Usa5hQ
