### ISSUE TITLE
Bug when clicking on a trend with an apostrophe

### ISSUE THREAD

**Issue by Aridow** [Bl4Cc4t/GoodTwitter2#81]
**Screenshots**
For instance, there is this trend : 
![image](https://user-images.githubusercontent.com/65539338/83950219-587e0200-a829-11ea-8dfb-6c5f95faadbf.png)
And when I click on it : 
![image](https://user-images.githubusercontent.com/65539338/83950222-66cc1e00-a829-11ea-9286-d926e198dad8.png)
It redirects to https://twitter.com/search?q=%22L

**Your configuation**
 - Browser : Firefox 77
 - Userscript Manager : Tampermonkey v4.10

**Comment by Bl4Cc4t** [comment]
the feature of switching your trend location is pretty useful for debugging things like that :D

**Comment by Aridow** [comment]
I don't know if opening a new issue is worth it, but there's the same bug with quotation mark : 
![image](https://user-images.githubusercontent.com/65539338/83980765-8f7f1100-a918-11ea-9e2b-536742fc5b76.png)
which redirects to https://twitter.com/search?q=%22

**Comment by Bl4Cc4t** [comment]
that makes no sense, why would they put already quoted strings in the trends...
they get quoted automatically when searching with them...

**Comment by Aridow** [comment]
It seems trends with % symbol doesn't work. For example, when i click on this trend : 
![image](https://user-images.githubusercontent.com/65539338/85040261-e8f10680-b188-11ea-926c-38ea3ffd32a6.png)
I access to this page : 
https://twitter.com/search?q=%2285%%20du%20SMIC%22
but it instantly redirects to twitter.com/explore. When I disable Tampermonkey, the link is this one and it works correctly : 
https://twitter.com/search?q=%2285%25%20du%20SMIC%22

**Comment by Bl4Cc4t** [comment]
gonna escape the % as well then :D

**Comment by Aridow** [comment]
Thanks for the fix. It's not that big of an issue, but it seems now when we click on a trend with a space, it's replaced with %20 in the searchbar.

**Comment by Bl4Cc4t** [comment]
seems like I messed the order of the replacements up :/
I also found another issue that I fixed (not all trends were wrapped when clicking on show more)
(I accidentally pushed to master, so the change should be visible when you update)
