### ISSUE TITLE
Google Chrome	83.0.4103.97 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by AmigaGPU** [Bl4Cc4t/GoodTwitter2#83]
The script fails to work in 

Google Chrome | 83.0.4103.97 (Official Build) (64-bit)

**Please check the following before you continue**
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
What sites does it affect?

**Screenshots**
For display issues, adding screenshots or even videos of your screen is recommended.

**Your configuation**
 - Browser (e.g. Chrome 83)
 - Userscript Manager (e.g. Tampermonkey v4.10)

**Comment by Bl4Cc4t** [comment]
Please upgrade to v0.0.20 I just released :)
If this does not help: what do you see? a broken layout or no change at all?
send a screenshot please.

**Comment by AmigaGPU** [comment]
You can close this issue the patch you released after my report fixed the problem

**Comment by AmigaGPU** [comment]
- Google Chrome | **83.0.4103.97** (Official Build) (64-bit)
- Tampermonkey **V4.10**
- Chrome in Linux Debian based MX Linux distro

Issue crept up again with a side effect https://twitter.com/settings/gt2 also not even appearing as if the script cant even spawn

This happened after I **closed** the browser.
While chrome was running I did notice a higher need for refreshing before the script worked.

![good_twitter2_07_jun_err_Screenshot](https://user-images.githubusercontent.com/38816309/84025441-f2e16100-a961-11ea-938b-1575ca740059.png)

**Comment by Bl4Cc4t** [comment]
Does this also happen when you disable all other extensions?
I do not get the issue and I really doubt it is related to your OS

**Comment by AmigaGPU** [comment]
I will try this now. 
It also happens with all other extensions disabled. The script does not seem to start

**Comment by AmigaGPU** [comment]
I love beta_testing()
Since I just tested the firefox functionality (works fine) I synchronized my moves and did the following:

- I  installed **TamperMonkey BETA** _v4.11.61.13_  in chrome
- I disabled the regular TamperMonkey

the  GoodTwitter2 script **now spawns!**
I haven't dug into why it did not invoke on the _regular_ Tampermonkey but I am a happy camper again.

Google Chrome | 83.0.4103.97 (Official Build) (64-bit)
Tampermonkey **BETA** _v4.11.61.13_

![good_twitter2_07_jun_beta_monkey_fix_Screenshot](https://user-images.githubusercontent.com/38816309/84029389-acdbcb80-a968-11ea-94f9-154c76f51d25.png)

**Comment by Bl4Cc4t** [comment]
weird. let’s hope it now decides to stay that way :D

**Comment by ratboypest** [comment]
not to reopen, but i had the exact same issue on the same chrome version, and it was fixed the same way. a look at the tampermonkey changelogs showed that not much seems to have been changed, but the biggest thing was that in 4.10 they added an experimental GM_addScript support to workaround page CSP issues, and then in 4.11 (the beta) they replaced GM_addScript with GM_addElement. 

the other changes were simple fixes to GM.setClipboard and GM_deleteValue, which didnt seem like theyd matter.

im not really familiar with tampermonkey or javascript, so im honestly not sure if this info helps, but i thought id offer it anyway.
