### ISSUE TITLE
Use full legacy navbar with smaller window widths (including those with small sidebars enabled)

### ISSUE THREAD

**Issue by geyerbri** [Bl4Cc4t/GoodTwitter2#84]
**Please check the following before you continue**
- [X] Checked if the feature has not been requested before

**Describe the feature**
This is very low priority, in my opinion.
It appears that the full legacy navbar requires a window width of 1265px. The view doesn't change to single-column when small sidebars is selected until the window width is below 1215px. This is just a suggestion to set the full legacy navbar's minimum width to 1215px when small sidebars is selected to match this behavior.
Screen grabs to show cutoff point for navbar (using body width as the indicator, to correspond to single-column screengrabs below):
Legacy navbar with labels above 1265px:
![Capture3](https://user-images.githubusercontent.com/5496867/83951735-a7b03c80-a801-11ea-8474-ece3d277e965.PNG)
Legacy navbar without labels below 1265px:
![Capture5](https://user-images.githubusercontent.com/5496867/83951742-aed74a80-a801-11ea-90a9-ef48b6818f94.PNG)
Screen grabs to show cutoff point for single-column view:
3-column display:
![Capture6](https://user-images.githubusercontent.com/5496867/83951847-99aeeb80-a802-11ea-9728-5fff91a1399a.PNG)
Single-column display:
![Capture7](https://user-images.githubusercontent.com/5496867/83951857-a03d6300-a802-11ea-9117-e8df50ae6662.PNG)

**Comment by Bl4Cc4t** [comment]
Hm, I’m having a bit of a hard time following you (yet again), but I guess you are talking about the text next to the icons disappearing at some random point when resizing.

I edited the icons to display my own text now (instead of an unreliable one which decides to disappear when it decides to do so) @ a63a0cc96aae85bd5b758c61ce40c369d8961b67

**Comment by geyerbri** [comment]
Yes the text next to icons disappearing when the width is under 1265px is what I was referring to. I'll try to figure out a different way to describe things moving forward!

I'll wait for 0.22 goes live to check things.

**Comment by geyerbri** [comment]
I just got back to this. Your adjustments achieved what I requested! Thank you!
