### ISSUE TITLE
"Show $ new Tweets" in Russian

### ISSUE THREAD

**Issue by BrandtnerKPW** [Bl4Cc4t/GoodTwitter2#85]
**Please check the following before you continue**
- [*] Checked if the feature has not been requested before

**Describe the feature**
In Russian, the end of the word "твит" ("tweet") in the line “Show 2+ new tweets” changes depending on the last digit of the number.
For 2 to 4, one ending is used. 5 to 0 is another.
The exception is 11-14 (also 111-114, 211-214 and so on), there is used same ending as 5-10 and 15-20.

For example:
2 new tweets = 2 новых твита
3 new tweets = 3 новых твита
4 new tweets = 4 новых твита
5 new tweets = 5 новых твитов
6 new tweets = 6 новых твитов
...
20 new tweets = 20 новых твитов
21 new tweets = 21 новый твит
22 new tweets =  22 новых твита
23 new tweets = 23 новых твита
24 new tweets = 24 новых твита
25 new tweets = 25 новых твитов

In this regard, when translating "showNewMulti" I did not write the translation exactly, in the old Twitter UI there was "Посмотреть $ новых твитов" ("Show $ new Tweets"), I had to adapt it.
If possible, please make an additional text output option for "showNewMulti". The original "showNewMulti" in Russian can be used for endings 5-0, also 11-14, 15-20, 25-30, 35-40 and so on. The new parameter will be able to use for 2-4, 22-24, 32-34 and so on.

It is not very necessary, but if it is possible.

**Comment by Bl4Cc4t** [comment]
okay, but what about 21, 31, 41, etc? do they all translate to новый твит?

**Comment by BrandtnerKPW** [comment]
Yes it is.
I forgot about it.

**Comment by Bl4Cc4t** [comment]
perfect, I think I have it done :)

**Comment by Bl4Cc4t** [comment]
you can copy the `getRusShowNew` function and paste it in your browser console if you want to try it out

**Comment by BrandtnerKPW** [comment]
Yes, it works. Thank you!
But there is a typo in the line
`     if (t1 >= 2 && t1 <= 4)               end = "овых твита" `
It should be like that:
`     if (t1 >= 2 && t1 <= 4)               end = "новых твита" `

**Comment by Bl4Cc4t** [comment]
oh yeah, I forgot that letter... and now it even aligns nicely :D
