### ISSUE TITLE
Left sidebar trends not working

### ISSUE THREAD

**Issue by jgk381** [Bl4Cc4t/GoodTwitter2#87]
I check/uncheck the setting and makes no difference. Trends always appear on right side.

I'm using Vivaldi as browser

**Comment by shootlazer** [comment]
Are you on latest version? It was fixed for me with last version

**Comment by daleylife411** [comment]
Same issue, just downloaded the extension, so I have the latest version. I am on the Brave browser.

**Comment by spodermenpls** [comment]
I have the same problem, it used to work initially but after I've found GT2's settings section, I've played around with them and now (despite "Left sidebar trends"'s checkbox being ticked at all times) the "Trends" column stays at the right side no matter what (tried restart, enabling/disabling various settings, cache clearing).

**Comment by shootlazer** [comment]
It was working for me a few days ago, but now it's broken again with 0.0.21.1

**Comment by Bl4Cc4t** [comment]
should be fixed for 0.0.22 :D

**Comment by hipichic** [comment]
I installed it yesterday (6/15) and the trending topics were still on the right side. Today the extension isn't working at all.

**Comment by Bl4Cc4t** [comment]
@hipichic As I said, it is fixed for the next version.
