### ISSUE TITLE
The old Twitter still there on Internet Archive...

### ISSUE THREAD

**Issue by MrMysteryMan** [Bl4Cc4t/GoodTwitter2#88]
Well, after I was making this Twitter back to the legacy version, there is still the old layout on Internet Archive, It looks like that:
https://web.archive.org/web/20200606232858/https://twitter.com/WaluigiMan764
Well, I hope there will be a Chrome extension to remove this cookie and no legacy version no longer supported error message for this.

**Comment by shootlazer** [comment]
It's true, there seems to be a way to enforce the old twitter design.
But I don't see why is this related to this project.

**Comment by shootlazer** [comment]
It's true, seems like there's still a way to enforce the old twitter design.
But I don't see why is this related to this project.

**Comment by Bl4Cc4t** [comment]
Yeah, I do not see any relation to this too, this project is for the new layout only.
Also, I am only able to use the site when logged out using that method.

But, on another note, this is helpful for taking a look at the old layout.
For anyone curious, change your user agent to the one the Internet Archive uses for their bot: 
```
archive.org_bot
```

[Here is a post on Reddit](https://www.reddit.com/r/Twitter/comments/gy0tlf/you_can_get_the_exact_look_of_the_old_ui_back_and/) with some more details.

**Comment by cszabla** [comment]
One thing this makes clear to me is that tweet font is a different size and type in NuTwitter; any way to take care of that?

**Comment by shootlazer** [comment]
> One thing this makes clear to me is that tweet font is a different size and type in NuTwitter; any way to take care of that?

Settings -> Display -> Font size

**Comment by cszabla** [comment]
Yes, I'm aware of that, but despite combining different font sizes and zooms with new Twitter I can't get it to match.

**Comment by MrMysteryMan** [comment]
Also, this was even still on the Google Web Cache:
https://webcache.googleusercontent.com/search?q=cache:oazshhgRw0QJ:https://twitter.com/waluigiman764+&cd=1&hl=en&ct=clnk&gl=us
