### ISSUE TITLE
Firefox CSP reenable warning appears on Violentmonkey

### ISSUE THREAD

**Issue by jerbear64** [Bl4Cc4t/GoodTwitter2#96]
**Please check the following before you continue**
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
The new sidebar notification for upgrading Tampermonkey and reenabling CSP appears on Violentmonkey. Violentmonkey never needed CSP to be disabled and does not need to be updated.

**Screenshots**
![violentmonkey](https://user-images.githubusercontent.com/6520237/83969467-2fe41f80-a89e-11ea-847c-749b409128df.png)

**Your configuation**
 - Firefox 76.0.1
 - Violentmonkey v2.12.7

**Comment by Bl4Cc4t** [comment]
Oh, VM works for you without it being enabled?
I couldn’t get it to work earlier, but it is indeed working now...
I’m sorry that you have to see it, I will remove it.

**Comment by Bl4Cc4t** [comment]
on a related note, the messages page behaves weirdly with Violentmonkey...
can you confirm this too?

**Comment by jerbear64** [comment]
The messages page looks like this in my case:
![f4b387b1](https://user-images.githubusercontent.com/6520237/83978483-c253e580-a8d5-11ea-8435-2c55fb521049.png)

**Comment by S-ed** [comment]
Happening to me as well.
![image](https://user-images.githubusercontent.com/3008353/84089219-14405c80-a9f7-11ea-9d77-a2a9c255f92a.png)

Just out of curiosity, why use Tampermonkey over Violentmonkey?
TM is a closed source.
VM is open source and no telemetry/analytics collected (since the new update of TOS).

**Comment by Bl4Cc4t** [comment]
> Messages window works fine:

That looks pretty broken to me.

> Just out of curiosity, why use Tampermonkey over Violentmonkey?

Well it did not work for me when I tried it...

Also, I cannot change the content of external resources which is crucial for developing the CSS I need.
It has other cool functions though, like seeing what values are currently set by script.

**Comment by tophf** [comment]
**For users of Violentmonkey**

The problem is caused by a [Firefox bug](https://bugzil.la/1267027). Tampermonkey circumvents it by disabling/augmenting CSP. Since VM doesn't do it, the users can disable CSP either globally via `security.csp.enable` in about:config or use another extension like [Header Editor](https://addons.mozilla.org/en-US/firefox/addon/header-editor/?src=search) to remove `Content-Security-Header` on that twitter site.

**For userscript authors**

The page context can be accessed via wrappedJSObject  in Violentmonkey/Greasemonkey/Firemonkey, the code should be compatible with Tampermonkey as well:
```js
const exportFunc = typeof exportFunction === 'function' ? exportFunction : (fn => fn)
const pageWindow = unsafeWindow.wrappedJSObject || unsafeWindow
const pageHistory = pageWindow.history.prototype
const origPush = pageHistory.pushState
pageHistory.pushState = exportFunction(function () {
  origPush.apply(this, arguments)
  urlChange()
}, pageWindow)

const origRepl = pageHistory.replaceState
pageHistory.replaceState = exportFunction(function () {
  origRepl.apply(this, arguments)
  urlChange()
}, pageWindow)
```

**Comment by Bl4Cc4t** [comment]
Hey, thanks for helping.
I think 
```
const pageHistory = pageWindow.history.prototype
```
should be
```
const pageHistory = pageWindow.history
```
(or else it says it is undefined).

---

I sadly cannot get it to work with Firefox.
It behaves the same under TM (not firing the push and replace events at all).

With VM, links do not work anymore.
I get this error:

```
Error: Permission denied to access property "length"
    pushState moz-extension://1721c892-9e8f-44a0-b674-8caf9cfa2774/GoodTwitter 2 - Electric Boogaloo.user.js#1:287
    push https://abs.twimg.com/responsive-web/web/main.5c0baa34.js:1
    confirmTransitionTo https://abs.twimg.com/responsive-web/web/main.5c0baa34.js:1
    push https://abs.twimg.com/responsive-web/web/main.5c0baa34.js:1
    push https://abs.twimg.com/responsive-web/web/main.5c0baa34.js:1
    push https://abs.twimg.com/responsive-web/web/main.5c0baa34.js:14
    l https://abs.twimg.com/responsive-web/web/main.5c0baa34.js:20
    o https://abs.twimg.com/responsive-web/web/main.5c0baa34.js:1
    d/</e[t]< https://abs.twimg.com/responsive-web/web/vendors~main.55bd4704.js:5
    a https://abs.twimg.com/responsive-web/web/vendors~main.55bd4704.js:57
    p https://abs.twimg.com/responsive-web/web/vendors~main.55bd4704.js:57
    y https://abs.twimg.com/responsive-web/web/vendors~main.55bd4704.js:57
    y https://abs.twimg.com/responsive-web/web/vendors~main.55bd4704.js:57
    it https://abs.twimg.com/responsive-web/web/vendors~main.55bd4704.js:57
    ut https://abs.twimg.com/responsive-web/web/vendors~main.55bd4704.js:57
    at https://abs.twimg.com/responsive-web/web/vendors~main.55bd4704.js:57
    pt https://abs.twimg.com/responsive-web/web/vendors~main.55bd4704.js:57
    F https://abs.twimg.com/responsive-web/web/vendors~main.55bd4704.js:57
    U https://abs.twimg.com/responsive-web/web/vendors~main.55bd4704.js:57
    $t https://abs.twimg.com/responsive-web/web/vendors~main.55bd4704.js:57
    Zt https://abs.twimg.com/responsive-web/web/vendors~main.55bd4704.js:57
    bind_applyFunctionN self-hosted:1042
    Zt self-hosted:1005
    unstable_runWithPriority https://abs.twimg.com/responsive-web/web/main.5c0baa34.js:9
    Yu https://abs.twimg.com/responsive-web/web/vendors~main.55bd4704.js:57
    D https://abs.twimg.com/responsive-web/web/vendors~main.55bd4704.js:57
    Xt https://abs.twimg.com/responsive-web/web/vendors~main.55bd4704.js:57
    bind_applyFunctionN self-hosted:1042
    Xt self-hosted:1005
```

I tried modifying the headers and disabling CSP again; did not help.
Am I doing something wrong? Or do you have another trick up your sleeve? ;)

**Comment by tophf** [comment]
A typo indeed, it should be an uppercase `H` in `pageWindow.History.prototype`. As for the errors, AFAICT all functions that are called from the page context should be exported manually via exportFunction, including your `urlChange`. For more info see [this article on MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts).

In case you disable CSP, Violentmonkey will be able to use [`page` mode](https://violentmonkey.github.io/posts/inject-into-context/) so none of these wrappedJSObject tricks will be needed in VM.

**Comment by Bl4Cc4t** [comment]
> A typo indeed, it should be an uppercase `H` in `pageWindow.History.prototype`.

Oh yeah, that makes more sense. 

> As for the errors, AFAICT all functions that are called from the page context should be exported manually via exportFunction, including your `urlChange`.

Well I don’t even have the `urlChange` function included when testing, just some log outputs to test it.
<details>
<summary>Script</summary>

```
// ==UserScript==
// @name          VM Test
// @version       0.0.1
// @author        schwarzkatz
// @match         https://twitter.com/*
// ==/UserScript==

(function() {
  "use strict"
  
  const exportFunc = typeof exportFunction === 'function' ? exportFunction : (fn => fn)
  const pageWindow = unsafeWindow.wrappedJSObject || unsafeWindow
  const pageHistory = pageWindow.History.prototype
  const origPush = pageHistory.pushState
  pageHistory.pushState = exportFunc(function () {
    origPush.apply(this, arguments)
    console.log("push")
    // urlChange()
  }, pageWindow)

  const origRepl = pageHistory.replaceState
  pageHistory.replaceState = exportFunc(function () {
    origRepl.apply(this, arguments)
    console.log("replace")
    // urlChange()
  }, pageWindow)

  window.addEventListener("popstate", function(event) {
    console.log("pop")
    // urlChange()
  })
})()
```
</details>

**Comment by tophf** [comment]
Turns out the originals should be exported as well:
```js
const origPush = exportFunc(pageHistory.pushState, pageWindow)
const origRepl = exportFunc(pageHistory.replaceState, pageWindow)
```
This is really weird but I'm not a specialist on Firefox so maybe there's a better way.

**Comment by Bl4Cc4t** [comment]
Cool, that works indeed! I don’t even need to export `urlChange` though...
Thank you very much, now Violentmonkey users can use the script as well :D
