### ISSUE TITLE
Tweet Analytics unreadable on dim theme.

### ISSUE THREAD

**Issue by fid3lito** [Bl4Cc4t/GoodTwitter2#97]
![unreadeable](https://user-images.githubusercontent.com/66445863/83972192-2b773100-a8b5-11ea-8c0d-d54da8024d7d.png)

**Comment by Bl4Cc4t** [comment]
they do not apply the dim theme to that modal, that’s pretty weird
will be changed, thx for the report

**Comment by fid3lito** [comment]
No probs... On another note, is there anything that can be done to that incredibly ugly font at the top? What were they thinking...

**Comment by Bl4Cc4t** [comment]
you want to change the whole font family?

**Comment by fid3lito** [comment]
Is it the same font all through the site? Idk, maybe make it not bold...
